export const earningsPayoutsCardStyles = {
  container: "border border-line bg-surface shadow-elevation-1",
  header: "border-b border-line bg-paper/55 px-5 py-4 md:px-6",
  headerTop: "flex items-center gap-2",
  headerIcon: "size-4 text-brand",
  headerEyebrow: "!mb-0",
  title: "mt-1 font-display text-[1.125rem] font-medium text-ink",
  subtitle: "mt-1 text-[0.875rem] text-ink-muted",
  body: "space-y-4 p-5 md:p-6",
  emptyText: "text-body-sm text-ink-muted",
  tableWrapper: "overflow-x-auto",
  table: "w-full min-w-[520px] text-body-sm",
  theadRow: "border-b border-line text-left text-ink-muted",
  th: "py-2 pr-3 font-medium",
  tr: "border-b border-line/60",
  tdText: "py-2 pr-3 text-ink-muted",
  tdMono: "py-2 pr-3 font-mono",
  tdStatus: "py-2 pr-3",
  downloadButton:
    "inline-flex items-center gap-1 font-medium text-brand hover:underline disabled:opacity-50",
  downloadIcon: "size-3.5",
  recentSection: "border-t border-line/60 pt-4",
  recentTitle: "mb-2 text-body-sm font-medium text-ink",
  recentList: "space-y-1",
  recentItem: "flex items-center justify-between text-body-sm text-ink-muted",
  recentAmount: "font-mono text-ink",
} as const;
