export const walletTransactionsTableStyles = {
  colDateHeader: "lg:w-[16%]",
  colDateCell: "lg:w-[16%]",
  dateCell: "flex items-baseline justify-between gap-3 lg:block",
  dateText: "min-w-0 font-medium text-ink lg:font-normal lg:whitespace-nowrap",
  mobileAmount: "shrink-0 lg:hidden",
  colDescriptionHeader: "lg:w-[46%]",
  colDescriptionCell: "lg:w-[46%]",
  descriptionWrapper: "min-w-0",
  sourceLabel: "font-medium text-ink",
  detailLabel: "mt-0.5 text-body-sm text-ink-muted break-words",
  mobileDescriptionRow: "grid-cols-1 gap-y-1",
  colAmountHeader: "lg:w-[16%] text-right",
  colAmountCell: "lg:w-[16%] whitespace-nowrap text-right",
  creditAmountPositive: "font-semibold tabular-nums text-success",
  creditAmountNegative: "font-semibold tabular-nums text-ink",
  colBalanceHeader: "lg:w-[16%] text-right",
  colBalanceCell:
    "lg:w-[16%] whitespace-nowrap text-right tabular-nums text-ink-muted",
  tableTitle: "text-body font-semibold text-ink",
} as const;
