export const ORDER_SUMMARY_ASIDE_STYLES = {
  root: "relative border border-line bg-surface-raised p-5 shadow-elevation-1",
  accentBorder:
    "pointer-events-none absolute inset-x-0 top-0 h-0.5 bg-gradient-to-r from-brand via-brand/70 to-transparent",
  itemCountText: "text-[0.875rem] text-ink-muted",
  dotSeparator: "mx-2 text-line",
  totalAmount: "font-medium text-ink",
  eyebrow: "mt-4",
  title: "mt-1 font-display text-[1.25rem] text-ink",
  itemsRow: "mt-5 space-y-2.5 text-[0.875rem]",
  itemsDl: "flex items-center justify-between gap-4",
  itemsLabel: "text-ink-muted",
  itemsValue: "tabular-nums text-ink",
  paymentSummary: "mt-5 border-t border-line pt-5",
  actionsContainer: "mt-5 border-t border-line pt-5 space-y-2",
  multiSellersContainer: "space-y-2",
  downloadTitle: "text-body-sm font-medium text-ink",
  fullWidthButton: "w-full",
  invoiceError: "text-body-sm text-danger",
  shippingAddressContainer: "mt-5 border-t border-line pt-5",
  shippingHeader: "flex items-center gap-2",
  shippingIcon: "h-3.5 w-3.5 text-ink-muted",
  shippingEyebrow: "!mb-0",
  address: "mt-2 not-italic text-[0.875rem] leading-relaxed text-ink",
  addressLineBlock: "block",
  addressLineMuted: "block text-ink-muted",
} as const;
