export const skeletonPrimitivesStyles = {
  rowsContainer: "space-y-2",
  defaultRowHeight: "h-10 w-full",
  gridContainer:
    "grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 lg:gap-6",
  gridItem: "space-y-3",
  defaultAspect: "aspect-square",
  imageRounded: "rounded-md w-full",
  cardContainer: "space-y-4",
  defaultCardHeight: "h-32 w-full",
  roundedMd: "rounded-md",
  categoryGrid:
    "grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 md:gap-4",
  categoryItem: "aspect-[4/3] w-full rounded-md",
  chartCard: "space-y-3 rounded-md border border-line bg-surface p-6",
  defaultChartHeight: "h-64",
  chartSkeleton: "w-full rounded-md",
  reviewList: "space-y-4",
  reviewCard: "space-y-3 rounded-md border border-line bg-surface p-4",
  reviewHeader: "flex items-center gap-3",
  wFull: "w-full",
  h3w16: "h-3 w-16",
  h3w24: "h-3 w-24",
  h3wFull: "h-3 w-full",
  h3w5_6: "h-3 w-5/6",
  h4w24: "h-4 w-24",
  h4w40: "h-4 w-40",
  h4wFull: "h-4 w-full",
} as const;
