export const myReviewsPageStyles = {
  container: "storefront-container py-8 md:py-10",
  header: "mb-8 max-w-2xl",
  title: "font-display text-[1.75rem] text-ink md:text-[2rem]",
  subtitle: "mt-2 text-body text-ink-muted",
  loadingSkeletonStack: "space-y-3",
  skeleton: "h-24 w-full",
  errorContainer: "border border-line bg-surface-raised px-5 py-10 text-center",
  emptyContainer: "border border-dashed border-line bg-paper/50",
  emptyState: "py-14",
  reviewsList: "divide-y divide-line border border-line bg-surface-raised",
  reviewItem: "px-5 py-5",
  reviewHeader: "flex flex-wrap items-start justify-between gap-3",
  productInfo: "min-w-0",
  productLink: "font-medium text-ink hover:text-brand",
  productFallback: "font-medium text-ink",
  ratingRow: "mt-1 flex items-center gap-1 text-body-sm text-ink-muted",
  starIcon: "fill-brand text-brand",
  dateText: "text-ink-faint",
  reviewTitle: "mt-3 font-medium text-ink",
  reviewBody: "mt-1 text-body text-ink-muted whitespace-pre-wrap",
} as const;
