/** Frontend API path builders — must stay aligned with backend mounts under `/api`. */
export const API = {
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    me: '/api/auth/me',
    refresh: '/api/auth/refresh',
    logout: '/api/auth/logout',
    forgotPassword: '/api/auth/forgot-password',
    resetPassword: '/api/auth/reset-password',
    changePassword: '/api/auth/change-password',
    sessions: '/api/auth/sessions',
    session: (family: string) => `/api/auth/sessions/${family}`,
  },
  users: {
    list: (query = '') => `/api/users${query ? `?${query}` : ''}`,
    assignees: (query = '') => `/api/users/assignees${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/users/${id}`,
    status: (id: string) => `/api/users/${id}/status`,
  },
  products: {
    list: (query = '') => `/api/products${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/products/${id}`,
    bySlug: (slug: string) => `/api/products/slug/${slug}`,
    approve: (id: string) => `/api/products/${id}/approve`,
    reject: (id: string) => `/api/products/${id}/reject`,
    archive: (id: string) => `/api/products/${id}/archive`,
    submit: (id: string) => `/api/products/${id}/submit`,
    variants: (productId: string) => `/api/products/${productId}/variants`,
    variant: (variantId: string) => `/api/products/variants/${variantId}`,
    images: (productId: string) => `/api/products/${productId}/images`,
    image: (imageId: string) => `/api/products/images/${imageId}`,
    imagePrimary: (imageId: string) => `/api/products/images/${imageId}/primary`,
  },
  categories: {
    list: '/api/categories',
    detail: (id: string) => `/api/categories/${id}`,
    resolve: (path: string) => `/api/categories/resolve?path=${encodeURIComponent(path)}`,
    facets: (idOrSlug: string, query = '') =>
      `/api/categories/${idOrSlug}/facets${query ? `?${query}` : ''}`,
    productCount: (id: string) => `/api/categories/${id}/product-count`,
    reorder: '/api/categories/reorder',
    reassignProducts: '/api/categories/reassign-products',
    attributes: (categoryId: string) => `/api/categories/${categoryId}/attributes`,
    attribute: (categoryId: string, attributeId: string) =>
      `/api/categories/${categoryId}/attributes/${attributeId}`,
    attributesReorder: (categoryId: string) =>
      `/api/categories/${categoryId}/attributes/reorder`,
  },
  vendors: {
    list: (query = '') => `/api/vendors${query ? `?${query}` : ''}`,
    directory: (query = '') => `/api/vendors/directory${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/vendors/${id}`,
    bySlug: (slug: string) => `/api/vendors/slug/${slug}`,
    me: '/api/vendors/me',
    approve: (id: string) => `/api/vendors/${id}/approve`,
    reject: (id: string) => `/api/vendors/${id}/reject`,
    suspend: (id: string) => `/api/vendors/${id}/suspend`,
    delete: (id: string) => `/api/vendors/${id}`,
    dashboardSummary: '/api/vendors/dashboard/summary',
    register: '/api/vendors/register',
    documentRequirements: (query = '') =>
      `/api/vendors/document-requirements${query ? `?${query}` : ''}`,
    meKycChecklist: '/api/vendors/me/kyc-checklist',
    kycChecklist: (id: string) => `/api/vendors/${id}/kyc-checklist`,
  },
  cart: {
    root: '/api/cart',
    items: '/api/cart/items',
    item: (id: string) => `/api/cart/items/${id}`,
    merge: '/api/cart/merge',
    clear: '/api/cart/clear',
  },
  checkout: {
    quote: '/api/checkout/quote',
    create: '/api/checkout',
    cancel: '/api/checkout/cancel',
    verify: '/api/checkout/verify',
  },
  wallet: {
    balance: '/api/wallet/balance',
    transactions: '/api/wallet/transactions',
  },
  orders: {
    list: (query = '') => `/api/orders${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/orders/${id}`,
    status: (id: string) => `/api/orders/${id}/status`,
  },
  suborders: {
    list: (query = '') => `/api/suborders${query ? `?${query}` : ''}`,
    status: (id: string) => `/api/suborders/${id}/status`,
  },
  returns: {
    list: '/api/returns',
    admin: '/api/returns/admin',
    create: '/api/returns',
    transition: (id: string) => `/api/returns/${id}/transition`,
    detail: (id: string) => `/api/returns/${id}`,
    delete: (id: string) => `/api/returns/${id}`,
  },
  reviews: {
    forProduct: (productId: string) => `/api/reviews/product/${productId}`,
    create: '/api/reviews',
    mine: '/api/reviews/my-reviews',
    vote: (id: string) => `/api/reviews/${id}/vote`,
    approve: (id: string) => `/api/reviews/${id}/approve`,
    reject: (id: string) => `/api/reviews/${id}/reject`,
    moderation: '/api/reviews/moderation',
    respond: (id: string) => `/api/reviews/${id}/respond`,
  },
  coupons: {
    apply: '/api/coupons/apply',
    remove: '/api/coupons/remove',
    eligible: '/api/coupons/eligible',
    list: '/api/coupons',
    create: '/api/coupons',
    detail: (id: string) => `/api/coupons/${id}`,
    status: (id: string) => `/api/coupons/${id}/status`,
    analytics: (id: string) => `/api/coupons/${id}/analytics`,
    bulk: '/api/coupons/bulk',
    batches: '/api/coupons/batches',
    vendor: {
      list: '/api/coupons/vendor',
      create: '/api/coupons/vendor',
      absorbedSummary: '/api/coupons/vendor/absorbed-summary',
      detail: (id: string) => `/api/coupons/vendor/${id}`,
      status: (id: string) => `/api/coupons/vendor/${id}/status`,
      analytics: (id: string) => `/api/coupons/vendor/${id}/analytics`,
    },
  },
  commissions: {
    list: '/api/commissions',
    vendor: (vendorId: string) => `/api/commissions/vendor/${vendorId}`,
  },
  payouts: {
    list: '/api/payouts',
    process: '/api/payouts/process',
  },
  reports: {
    catalog: '/api/reports/catalog',
    run: (type: string, query = '') =>
      `/api/reports/run/${encodeURIComponent(type)}${query ? `?${query}` : ''}`,
    exportDownload: (id: string) => `/api/reports/exports/${id}/download`,
    exportStatus: (id: string) => `/api/reports/exports/${id}`,
    customerOrderHistory: (query = '') =>
      `/api/reports/customer/order-history${query ? `?${query}` : ''}`,
    customerOrderInvoice: (orderId: string) => `/api/reports/customer/order-invoice/${orderId}`,
    adminSummary: '/api/reports/admin/summary',
    adminVendors: '/api/reports/admin/vendors',
    adminReconciliation: '/api/reports/admin/reconciliation',
    adminWalletLiability: '/api/reports/admin/wallet-liability',
    adminCashbackWriteOffs: '/api/reports/admin/cashback-write-offs',
    vendor: (vendorId: string) => `/api/reports/vendor/${vendorId}`,
  },
  shipping: {
    rates: '/api/shipping/rates',
    zones: '/api/shipping/zones',
    zone: (id: string) => `/api/shipping/zones/${id}`,
    adminRates: '/api/shipping/rates/admin',
    createRate: '/api/shipping/rates',
    tracking: (trackingNumber: string) => `/api/shipping/tracking/${trackingNumber}`,
  },
  tax: {
    rules: '/api/tax/rules',
    rule: (id: string) => `/api/tax/rules/${id}`,
  },
  settings: {
    public: '/api/settings/public',
    root: '/api/settings',
  },
  homepage: {
    banners: '/api/homepage/banners',
    adminBanners: '/api/homepage/admin/banners',
    adminBanner: (id: string) => `/api/homepage/admin/banners/${id}`,
  },
  admin: {
    dashboard: '/api/admin/dashboard',
    analytics: '/api/admin/analytics/platform',
  },
  audit: {
    list: '/api/audit',
  },
  wishlist: {
    root: '/api/wishlist',
    items: '/api/wishlist/items',
    item: (productId: string) => `/api/wishlist/items/${productId}`,
    moveToCart: (productId: string) => `/api/wishlist/items/${productId}/move-to-cart`,
  },
  search: {
    root: '/api/search',
    autocomplete: (term: string) => `/api/search/autocomplete?q=${encodeURIComponent(term)}`,
    query: (term: string, page: number) =>
      `/api/search?q=${encodeURIComponent(term)}&page=${page}`,
  },
  newsletter: {
    subscribe: '/api/newsletter/subscribe',
  },
  supportTickets: {
    root: '/api/support-tickets',
    mine: (query = '') => `/api/support-tickets/mine${query ? `?${query}` : ''}`,
    vendor: (query = '') => `/api/support-tickets/vendor${query ? `?${query}` : ''}`,
    admin: (query = '') => `/api/support-tickets/admin${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/support-tickets/${id}`,
    messages: (id: string, query = '') =>
      `/api/support-tickets/${id}/messages${query ? `?${query}` : ''}`,
    reply: (id: string) => `/api/support-tickets/${id}/messages`,
    resolve: (id: string) => `/api/support-tickets/${id}/resolve`,
    reopen: (id: string) => `/api/support-tickets/${id}/reopen`,
    close: (id: string) => `/api/support-tickets/${id}/close`,
    reassign: (id: string) => `/api/support-tickets/${id}/reassign`,
    priority: (id: string) => `/api/support-tickets/${id}/priority`,
    escalate: (id: string) => `/api/support-tickets/${id}/escalate`,
    rate: (id: string) => `/api/support-tickets/${id}/rate`,
  },
  bugReports: {
    root: '/api/bug-reports',
    mine: (query = '') => `/api/bug-reports/mine${query ? `?${query}` : ''}`,
    admin: (query = '') => `/api/bug-reports/admin${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/bug-reports/${id}`,
    triage: (id: string) => `/api/bug-reports/${id}/triage`,
    assignment: (id: string) => `/api/bug-reports/${id}/assignment`,
    status: (id: string) => `/api/bug-reports/${id}/status`,
    duplicate: (id: string) => `/api/bug-reports/${id}/duplicate`,
    wontFix: (id: string) => `/api/bug-reports/${id}/wont-fix`,
    verify: (id: string) => `/api/bug-reports/${id}/verify`,
    comments: (id: string, query = '') =>
      `/api/bug-reports/${id}/comments${query ? `?${query}` : ''}`,
  },
  inventory: {
    lowStock: '/api/inventory/low-stock',
    variantStock: (variantId: string) => `/api/inventory/variants/${variantId}/stock`,
  },
  notifications: {
    logs: '/api/notifications/logs',
    test: '/api/notifications/test',
  },
  usersMe: {
    profile: '/api/users/me',
    export: '/api/users/me/export',
    addresses: '/api/users/addresses',
    address: (id: string) => `/api/users/addresses/${id}`,
    addressDefault: (id: string) => `/api/users/addresses/${id}/default`,
  },
  uploads: {
    root: '/api/uploads',
    bulk: '/api/uploads/bulk',
    presign: '/api/uploads/presign',
    presignBulk: '/api/uploads/presign/bulk',
  },
  vendorDocs: {
    list: (vendorId: string) => `/api/vendors/${vendorId}/documents`,
    create: (vendorId: string) => `/api/vendors/${vendorId}/documents`,
    meList: '/api/vendors/me/documents',
    meCreate: '/api/vendors/me/documents',
    verify: (documentId: string) => `/api/vendors/documents/${documentId}/verify`,
    reject: (documentId: string) => `/api/vendors/documents/${documentId}/reject`,
    viewUrl: (documentId: string) => `/api/vendors/documents/${documentId}/view-url`,
  },
} as const
