/** Frontend API path builders — must stay aligned with backend mounts under `/api`. */
export const API = {
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    me: '/api/auth/me',
    refresh: '/api/auth/refresh',
    logout: '/api/auth/logout',
    forgotPassword: '/api/auth/forgot-password',
    resetPassword: '/api/auth/reset-password',
    changePassword: '/api/auth/change-password',
    sessions: '/api/auth/sessions',
    session: (family: string) => `/api/auth/sessions/${family}`,
  },
  users: {
    list: (query = '') => `/api/users${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/users/${id}`,
    status: (id: string) => `/api/users/${id}/status`,
  },
  products: {
    list: (query = '') => `/api/products${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/products/${id}`,
    bySlug: (slug: string) => `/api/products/slug/${slug}`,
    approve: (id: string) => `/api/products/${id}/approve`,
    reject: (id: string) => `/api/products/${id}/reject`,
    archive: (id: string) => `/api/products/${id}/archive`,
    submit: (id: string) => `/api/products/${id}/submit`,
    variants: (productId: string) => `/api/products/${productId}/variants`,
    variant: (variantId: string) => `/api/products/variants/${variantId}`,
    images: (productId: string) => `/api/products/${productId}/images`,
    image: (imageId: string) => `/api/products/images/${imageId}`,
    imagePrimary: (imageId: string) => `/api/products/images/${imageId}/primary`,
  },
  categories: {
    list: '/api/categories',
    detail: (id: string) => `/api/categories/${id}`,
  },
  vendors: {
    list: (query = '') => `/api/vendors${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/vendors/${id}`,
    bySlug: (slug: string) => `/api/vendors/slug/${slug}`,
    approve: (id: string) => `/api/vendors/${id}/approve`,
    reject: (id: string) => `/api/vendors/${id}/reject`,
    suspend: (id: string) => `/api/vendors/${id}/suspend`,
    dashboardSummary: '/api/vendors/dashboard/summary',
    register: '/api/vendors/register',
  },
  cart: {
    root: '/api/cart',
    items: '/api/cart/items',
    item: (id: string) => `/api/cart/items/${id}`,
    merge: '/api/cart/merge',
    clear: '/api/cart/clear',
  },
  checkout: {
    quote: '/api/checkout/quote',
    create: '/api/checkout',
    cancel: '/api/checkout/cancel',
    verify: '/api/checkout/verify',
  },
  orders: {
    list: (query = '') => `/api/orders${query ? `?${query}` : ''}`,
    detail: (id: string) => `/api/orders/${id}`,
    status: (id: string) => `/api/orders/${id}/status`,
  },
  suborders: {
    list: (query = '') => `/api/suborders${query ? `?${query}` : ''}`,
    status: (id: string) => `/api/suborders/${id}/status`,
  },
  returns: {
    list: '/api/returns',
    admin: '/api/returns/admin',
    create: '/api/returns',
    transition: (id: string) => `/api/returns/${id}/transition`,
  },
  reviews: {
    forProduct: (productId: string) => `/api/reviews/product/${productId}`,
    create: '/api/reviews',
    mine: '/api/reviews/my-reviews',
    vote: (id: string) => `/api/reviews/${id}/vote`,
    approve: (id: string) => `/api/reviews/${id}/approve`,
    reject: (id: string) => `/api/reviews/${id}/reject`,
    moderation: '/api/reviews/moderation',
    respond: (id: string) => `/api/reviews/${id}/respond`,
  },
  coupons: {
    apply: '/api/coupons/apply',
    remove: '/api/coupons/remove',
    list: '/api/coupons',
    create: '/api/coupons',
  },
  commissions: {
    list: '/api/commissions',
    vendor: (vendorId: string) => `/api/commissions/vendor/${vendorId}`,
  },
  payouts: {
    list: '/api/payouts',
    process: '/api/payouts/process',
  },
  shipping: {
    rates: '/api/shipping/rates',
    zones: '/api/shipping/zones',
    zone: (id: string) => `/api/shipping/zones/${id}`,
    adminRates: '/api/shipping/rates/admin',
    createRate: '/api/shipping/rates',
    tracking: (trackingNumber: string) => `/api/shipping/tracking/${trackingNumber}`,
  },
  tax: {
    rules: '/api/tax/rules',
    rule: (id: string) => `/api/tax/rules/${id}`,
  },
  settings: {
    public: '/api/settings/public',
    root: '/api/settings',
  },
  admin: {
    dashboard: '/api/admin/dashboard',
    analytics: '/api/admin/analytics/platform',
  },
  audit: {
    list: '/api/audit',
  },
  wishlist: {
    root: '/api/wishlist',
    items: '/api/wishlist/items',
    item: (productId: string) => `/api/wishlist/items/${productId}`,
    moveToCart: (productId: string) => `/api/wishlist/items/${productId}/move-to-cart`,
  },
  search: {
    root: '/api/search',
    autocomplete: (term: string) => `/api/search/autocomplete?q=${encodeURIComponent(term)}`,
    query: (term: string, page: number) =>
      `/api/search?q=${encodeURIComponent(term)}&page=${page}`,
  },
  help: {
    tickets: '/api/help/tickets',
  },
  inventory: {
    lowStock: '/api/inventory/low-stock',
    variantStock: (variantId: string) => `/api/inventory/variants/${variantId}/stock`,
  },
  notifications: {
    logs: '/api/notifications/logs',
    test: '/api/notifications/test',
  },
  usersMe: {
    profile: '/api/users/me',
    export: '/api/users/me/export',
    avatar: '/api/users/me/avatar',
    addresses: '/api/users/addresses',
    address: (id: string) => `/api/users/addresses/${id}`,
    addressDefault: (id: string) => `/api/users/addresses/${id}/default`,
  },
  vendorDocs: {
    list: (vendorId: string) => `/api/vendors/${vendorId}/documents`,
    create: (vendorId: string) => `/api/vendors/${vendorId}/documents`,
    verify: (documentId: string) => `/api/vendors/documents/${documentId}/verify`,
  },
} as const
