/** Shared UI labels — single source for nav, footer, and repeated CTAs. */
export const LABELS = {
  // CTAs / commerce
  continueShopping: 'Continue shopping',
  outOfStock: 'Out of stock',
  addToWishlist: 'Add to wishlist',
  removeFromWishlist: 'Remove from wishlist',
  addToCart: 'Add to cart',
  approvalQueue: 'Approval queue',
  newArrivals: 'New Arrivals',
  topRated: 'Top Rated',
  allProducts: 'All Products',
  shop: 'Shop',
  goToMyOrders: 'Go to my orders',
  allOrders: 'All orders',

  // Auth
  logIn: 'Log in',
  backToLogin: 'Back to login',
  alreadyHaveAccount: 'Already have an account?',
  welcomeBack: 'Welcome back',
  logInToAccount: 'Log in to your account',
  dontHaveAccount: "Don't have an account?",
  register: 'Register',
  loginFailed: 'Login failed',

  // Footer sections
  company: 'Company',
  customerService: 'Customer Service',
  sellOnMarketplace: 'Sell on Marketplace',
  connect: 'Connect',

  // Footer / nav link labels
  about: 'About',
  contact: 'Contact',
  blog: 'Blog',
  faq: 'FAQ',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  trackOrder: 'Track Order',
  helpCenter: 'Help Center',
  becomeSeller: 'Become a Seller',
  vendorDashboard: 'Vendor Dashboard',

  // Admin nav
  vendors: 'Vendors',
  products: 'Products',
  categories: 'Categories',
  orders: 'Orders',
  returnsRefunds: 'Returns / Refunds',
  coupons: 'Coupons',
  reviews: 'Reviews',
  tax: 'Tax',
  shipping: 'Shipping',
  financePayouts: 'Finance / Payouts',
  users: 'Users',
  analytics: 'Analytics',
  analyticsHint:
    'Commerce health, growth trends, and queues that need attention — tuned for the marketplace.',
  analyticsGmv: 'Gross merchandise volume',
  analyticsPaidGmv: 'Paid GMV',
  analyticsAov: 'Average order value',
  analyticsTotalOrders: 'Orders',
  analyticsCustomers: 'Customers',
  analyticsVendors: 'Vendors',
  analyticsCancellationRate: 'Cancellation rate',
  analyticsReturnRate: 'Return rate',
  analyticsOrderTrend: 'Order & revenue trend',
  analyticsOrderTrendHint: 'Non-cancelled orders over the last 30 days',
  analyticsOrdersByStatus: 'Orders by status',
  analyticsPaymentsByStatus: 'Payments by status',
  analyticsPaymentsTotal: 'Payments',
  analyticsTopVendors: 'Top vendors',
  analyticsTopCategories: 'Top categories',
  analyticsRatingDistribution: 'Approved review ratings',
  analyticsOpsQueues: 'Needs attention',
  analyticsPendingProducts: 'Pending products',
  analyticsPendingVendors: 'Pending vendors',
  analyticsPendingReviews: 'Pending reviews',
  analyticsGrowthOrders: 'Orders (14d)',
  analyticsGrowthRevenue: 'Revenue (14d)',
  analyticsNoData: 'No analytics data available',
  analyticsOrdersSeries: 'Orders',
  analyticsRevenueSeries: 'Revenue',
  analyticsRankShare: '{value}% of top total',
  analyticsEmptyChart: 'Not enough data to chart yet.',
  analyticsStarRating: '{rating}★',
  analyticsVsPriorPeriod: 'vs prior 14 days',
  percentValue: '{value}%',
  audit: 'Audit',
  settings: 'Settings',

  // Vendor / account nav
  overview: 'Overview',
  payouts: 'Payouts',
  personalInfo: 'Personal info',
  security: 'Security',
  addresses: 'Addresses',
  privacy: 'Privacy',

  // Return reasons
  returnReasonDamaged: 'Damaged',
  returnReasonWrongItem: 'Wrong item',
  returnReasonNotAsDescribed: 'Not as described',
  returnReasonNoLongerNeeded: 'No longer needed',
  returnReasonOther: 'Other',

  // Unavailable item badges
  unavailableReasonOutOfStock: 'Out of stock',
  unavailableReasonProductUnpublished: 'No longer available',
  unavailableReasonVendorUnavailable: 'Shop unavailable',
  unavailableGeneric: 'Unavailable',

  // Cart / checkout unavailability
  removeUnavailableToCheckout: 'Remove unavailable items to continue',

  // Vendor storefront unavailable
  shopUnavailableHeading: 'This shop is unavailable',
  shopUnavailableBody: 'The shop you are looking for is no longer active or has been removed.',
  browseOtherShops: 'Browse other shops',

  // Coupon messages
  couponRemovedUnavailable: 'Coupon was removed because some items are no longer available.',
  couponRemovedCartChange: 'Your coupon was removed due to cart changes.',
  applyCoupon: 'Apply',
  removeCoupon: 'Remove',
  couponCodePlaceholder: 'Enter coupon code',
  couponApplied: 'Coupon applied — ₹{amount} off',
  couponAppliedCheckout: 'Coupon applied — discount will be calculated at checkout',
  couponInvalid: 'Invalid or expired coupon code',
  couponAppliedLabel: 'Applied: {code}',
  couponDiscount: 'Discount',
  availableOffers: 'Available offers',
  noAvailableOffers: 'No offers available for this cart.',
  applyOffer: 'Apply offer',
  offersAtCheckout: 'Offers available at checkout',
  autoAppliedOffer: 'Best available offer applied automatically.',
  signInToApplyCoupon: 'Sign in to apply coupon codes to your order.',
  enterCouponCodeToApply: 'Enter a coupon code to apply it.',
  couponSectionBasics: 'Basics',
  couponSectionValue: 'Value',
  couponSectionScope: 'Scope',
  couponSectionConstraints: 'Constraints',
  couponSectionRestrictions: 'Restrictions',
  discountBearer: 'Discount bearer',
  discountBearerPlatform: 'Platform',
  discountBearerVendor: 'Vendor',
  applicableScope: 'Applicable scope',
  scopeTypeAll: 'All products',
  scopeTypeVendor: 'Vendor',
  scopeTypeProduct: 'Products',
  scopeTypeCategory: 'Categories',
  scopeIds: 'Scope IDs (comma-separated UUIDs)',
  minQuantity: 'Min quantity',
  usageLimitTotal: 'Total usage limit',
  usageLimitPerUser: 'Per-user usage limit',
  stackable: 'Stackable',
  priority: 'Priority',
  userRestriction: 'User restriction',
  userRestrictionAll: 'All users',
  userRestrictionFirstOrder: 'First order only',
  userRestrictionSpecific: 'Specific users',
  userRestrictionSegment: 'Segment',
  pauseCoupon: 'Pause',
  activateCoupon: 'Activate',
  archiveCoupon: 'Archive',
  viewAnalytics: 'Analytics',
  couponAnalytics: 'Coupon analytics',
  redemptionCount: 'Redemptions',
  discountTotal: 'Discount cost',
  absorbedDiscounts: 'Absorbed discounts',
  absorbedDiscountsSummary: 'You absorbed ₹{amount} in discounts',
  bulkGenerate: 'Bulk generate',
  bulkGenerateTitle: 'Generate coupon batch',
  bulkBatchName: 'Batch name',
  bulkCount: 'Number of codes',
  bulkPrefix: 'Code prefix',
  couponBatches: 'Coupon batches',
  noCouponBatches: 'No coupon batches yet',
  batchGeneratedCount: 'Generated',
  vendorCoupons: 'Vendor coupons',
  platformCoupons: 'Platform coupons',
  allCoupons: 'All coupons',
  vendorId: 'Vendor',
  confirmPauseCouponTitle: 'Pause this coupon?',
  confirmPauseCouponBody: '"{code}" will stop accepting new redemptions until reactivated.',
  confirmActivateCouponTitle: 'Activate this coupon?',
  confirmActivateCouponBody: '"{code}" will become available for eligible carts.',
  confirmArchiveCouponTitle: 'Archive this coupon?',
  confirmArchiveCouponBody: '"{code}" will be archived and no longer usable.',
  couponCodeRequired: 'Code is required',
  couponCodeTooLong: 'Code must be 64 characters or fewer',
  couponTypeRequired: 'Type is required',
  couponValueNegative: 'Value cannot be negative',
  couponMaxDiscountNegative: 'Max discount cannot be negative',
  couponMinOrderNegative: 'Min order value cannot be negative',
  couponStartDateRequired: 'Start date is required',
  couponStartDateInvalid: 'Start date is invalid',
  couponEndDateRequired: 'End date is required',
  couponEndDateInvalid: 'End date is invalid',
  couponValueRequired: 'Value is required for this coupon type',
  couponPercentageMax: 'Percentage value cannot exceed 100',
  couponEndAfterStart: 'End date must be after start date',
  couponScopeTypeRequired: 'Scope type is required',
  couponBearerRequired: 'Discount bearer is required',
  couponBatchNameRequired: 'Batch name is required',
  couponBulkCountInvalid: 'Enter a count between 1 and 500',
  couponAppliedReview: 'Coupon {code} applied (−{amount})',
  vendorTotal: 'Vendor total',
  subtotal: 'Subtotal',
  freeShipping: 'Free',
  payableNow: 'Payable now',
  includingShippingTaxes: 'Including shipping and taxes',
  placeOrder: 'Place order',
  backToPayment: 'Back to payment',
  preparingSummary: 'Preparing your summary',
  calculatingShippingTaxes: 'Calculating shipping and taxes for your order…',
  couponCodeLabel: 'Coupon code',
  yourCart: 'Your Cart',
  closeCart: 'Close cart',
  cartEmptyHeading: 'Your cart is empty',
  cartEmptyMessage: 'Add some items to get started.',
  checkout: 'Checkout',
  viewFullCart: 'View full cart',
  total: 'Total',
  qtyLabel: 'Qty {count}',
  taxIgst: 'IGST',
  taxCgstSgst: 'CGST + SGST',
  enterBatchName: 'Enter a batch name.',
  enterBulkCount: 'Enter how many codes to generate.',
  bulkGenerateHint: 'Complete the batch fields to generate codes.',
  createVendorCoupon: 'Create vendor coupon',
  noVendorCoupons: 'No vendor coupons',
  couponVendorScopeLocked: 'Scope is locked to your vendor catalog.',
  usageUnlimited: '∞',

  // Tables / pagination
  refresh: 'Refresh',
  loading: 'Loading…',
  noRecordsFound: 'No records found.',
  recordDetails: 'Record details',
  recordDetailsHint: 'Full fields for this row, including values not shown in the table.',
  noDetailFields: 'No fields to display.',
  viewRecordDetails: 'View record details',
  close: 'Close',
  noCoupons: 'No coupons',
  actions: 'Actions',
  moreActions: 'More actions',
  pageOf: 'Page {current} of {total}',
  showingResults: 'Showing {from}–{to} of {total}',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  firstPageHint: "You're on the first page.",
  lastPageHint: "You're on the last page.",
  couldNotLoadData: 'Could not load data',
  approve: 'Approve',
  reject: 'Reject',
  cancel: 'Cancel',
  suspend: 'Suspend',
  archive: 'Archive',
  activate: 'Activate',
  block: 'Block',
  delete: 'Delete',
  edit: 'Edit',
  confirm: 'Confirm',
  processPayouts: 'Process payouts',
  commissions: 'Commissions',
  couponCode: 'Code',
  couponType: 'Type',
  couponUsage: 'Usage',
  status: 'Status',
  expires: 'Expires',
  businessName: 'Business Name',
  vendorName: 'Vendor',
  productName: 'Product',
  customerName: 'Customer',
  actorName: 'Actor',
  category: 'Category',
  email: 'Email',
  role: 'Role',
  createdAt: 'Created',
  basePrice: 'Price',
  totalAmount: 'Total',
  rating: 'Rating',
  title: 'Title',
  body: 'Review',
  reason: 'Reason',
  reasonCode: 'Reason code',
  refundAmount: 'Refund',
  saleAmount: 'Sale amount',
  commissionRate: 'Commission rate',
  commissionAmount: 'Commission',
  amount: 'Amount',
  periodStart: 'Period start',
  periodEnd: 'Period end',
  action: 'Action',
  entityType: 'Entity',
  hsnCode: 'HSN',
  states: 'States',
  pincodePrefixes: 'Pincode prefixes',
  yes: 'Yes',
  no: 'No',
  slug: 'Slug',
  rejectionReason: 'Rejection reason',
  suspensionReason: 'Suspension reason',
  product: 'Product',
  price: 'Price',
  rejectionNote: 'Rejection note',
  reasonRequired: 'Reason required',
  enterRejectionNote: 'Enter a rejection note before rejecting.',
  enterRejectionReason: 'Enter a rejection reason before rejecting.',
  vendorApprovalQueue: 'Vendor Approval Queue',
  productModerationQueue: 'Product Moderation Queue',
  noPendingVendorApprovals: 'No pending vendor approvals',
  noPendingProductApprovals: 'No pending product approvals',
  pendingReview: 'Pending review',
  allVendors: 'All vendors',
  countOverflow: '99+',
  confirmApproveVendorTitle: 'Approve this vendor?',
  confirmApproveVendorBody: '"{name}" will be approved and can sell on the marketplace.',
  confirmRejectVendorTitle: 'Reject this vendor?',
  confirmRejectVendorBody: '"{name}" will be rejected. Share a clear reason for the seller.',
  confirmApproveProductTitle: 'Approve this product?',
  confirmApproveProductBody: '"{name}" will go live for customers once approved.',
  confirmRejectProductTitle: 'Reject this product?',
  confirmRejectProductBody: '"{name}" will be sent back to the vendor. Include a rejection note.',
  thisItem: 'this item',
  confirmSuspendVendorTitle: 'Suspend this vendor?',
  confirmSuspendVendorBody: '"{name}" will be suspended and hidden from customers. Provide a reason.',
  confirmArchiveProductTitle: 'Archive this product?',
  confirmArchiveProductBody: '"{name}" will be archived and removed from the live catalog.',
  confirmOrderTitle: 'Confirm this order?',
  confirmOrderBody: 'Mark order "{name}" as confirmed?',
  confirmApproveReturnTitle: 'Approve this return?',
  confirmApproveReturnBody: 'Approve return request "{name}" and continue the refund flow?',
  confirmApproveReviewTitle: 'Approve this review?',
  confirmApproveReviewBody: 'Publish review "{name}" for shoppers to see?',
  confirmRejectReviewTitle: 'Reject this review?',
  confirmRejectReviewBody: 'Reject review "{name}"? It will not appear publicly.',
  confirmDeleteCategoryTitle: 'Delete this category?',
  confirmDeleteCategoryBody:
    'Delete "{name}"? Categories with products or subcategories cannot be deleted.',
  confirmDeleteTaxTitle: 'Delete this tax rule?',
  confirmDeleteTaxBody: 'Delete tax rule "{name}"? This cannot be undone.',
  confirmDeleteShippingTitle: 'Delete this shipping zone?',
  confirmDeleteShippingBody: 'Delete shipping zone "{name}"? Rates in this zone will be affected.',
  confirmBlockUserTitle: 'Block this user?',
  confirmBlockUserBody: 'Block "{name}"? They will no longer be able to sign in.',
  confirmActivateUserTitle: 'Activate this user?',
  confirmActivateUserBody: 'Activate "{name}" and restore account access?',
  confirmDeleteUserTitle: 'Delete this user?',
  confirmDeleteUserBody: 'Delete "{name}"? This cannot be undone.',
  confirmProcessPayoutsTitle: 'Process payouts?',
  confirmProcessPayoutsBody: 'Process pending payouts for eligible vendors now?',
  enterSuspendReason: 'Enter a suspension reason before continuing.',
  create: 'Create',
  save: 'Save',
  newCategory: 'New category',
  createCategory: 'Create category',
  createCategoryHint: 'Add a catalog category with optional parent, image, and status.',
  enterCategoryName: 'Enter a category name to create.',
  editCategoryTitle: 'Edit category',
  editCategoryBody: 'Update name, parent, image, and status for this category.',
  categoryName: 'Category name',
  categoryNameRequired: 'Category name is required',
  enterCategoryNameToSave: 'Enter a category name to save.',
  imageNotAvailable: 'Image not available',
  parentCategory: 'Parent category',
  parentCategoryNone: 'None (top-level)',
  selectParentCategory: 'Select a parent category',
  categoryImageUrl: 'Image URL',
  categoryImageUrlPlaceholder: 'https://…',
  categoryImageUrlInvalid: 'Enter a valid image URL',
  categoryStatus: 'Status',
  categoryStatusActive: 'Active',
  categoryStatusArchived: 'Archived',
  categorySeoTitle: 'SEO title',
  categorySeoDescription: 'SEO description',
  categoryCommissionRate: 'Category commission %',
  categoryCommissionRateHint: 'Optional override; leaves inherit from parents, then vendor default.',
  categoryAttributes: 'Filter attributes',
  categoryAttributesHint: 'Define category-specific filters (Material, Size, etc.).',
  addCategoryAttribute: 'Add attribute',
  attributeName: 'Attribute name',
  attributeType: 'Attribute type',
  attributeOptions: 'Options (comma-separated)',
  attributeTypeEnum: 'Enum',
  attributeTypeRange: 'Range',
  attributeTypeBoolean: 'Boolean',
  manageAttributes: 'Attributes',
  editCategoryAttribute: 'Edit attribute',
  saveCategoryAttribute: 'Save attribute',
  cancelEditAttribute: 'Cancel',
  couldNotReorderAttributes: 'Could not save attribute order.',
  couldNotSaveAttribute: 'Could not save attribute.',
  couldNotDeleteAttribute: 'Could not delete attribute.',
  deleteCategoryAttribute: 'Delete attribute',
  reassignProducts: 'Reassign products',
  reassignProductsTitle: 'Bulk reassign products',
  reassignProductsBody: 'Move all products from one category to another.',
  reassignFrom: 'From category',
  reassignTo: 'To category',
  reassignConfirm: 'Reassign',
  selectCategory: 'Select category',
  archiveCategory: 'Archive',
  reactivateCategory: 'Reactivate',
  confirmArchiveCategoryTitle: 'Archive this category?',
  confirmArchiveCategoryBody:
    'Archive "{name}"? It will leave navigation and filters. {count} product(s) stay visible via direct links.',
  confirmReactivateCategoryTitle: 'Reactivate this category?',
  confirmReactivateCategoryBody: 'Restore "{name}" to active navigation and filters?',
  categoryReorderHint: 'Drag rows to change display order.',
  couldNotReorderCategories: 'Could not save category order.',
  couldNotReassignProducts: 'Could not reassign products.',
  productsReassigned: 'Reassigned {count} product(s).',
  name: 'Name',
  imageUrl: 'Image',
  parentId: 'Parent',
  parentName: 'Parent',
  displayOrder: 'Order',
  seoTitle: 'SEO title',
  seoDescription: 'SEO description',
  shopCategory: 'Shop {name}',
  shopCategoryDescription: 'Browse {name} on {site}.',
  filteredCategoryNoindex: 'Filtered category results',
  categoryBreadcrumbHome: 'Home',
  breadcrumb: 'Breadcrumb',
  clearFacetFilters: 'Clear filters',
  facetResults: '{count} results',
  facetDisabledHint: 'No products match with current filters',
  allCategories: 'All categories',
  categoryPlpEmpty: 'No products in this category yet.',
  categoryPlpEmptyEyebrow: 'Empty category',
  categoryPlpEmptyHeading: 'No products in "{name}"',
  categoryPlpEmptyBody:
    'This category has no items listed right now. Try a parent category, or browse the full catalog.',
  categoryPlpNoFilterMatchesEyebrow: 'No matches',
  categoryPlpNoFilterMatchesHeading: 'Nothing matches in "{name}"',
  categoryPlpNoFilterMatchesBody:
    'No products in this category match your current filters. Clear filters to see everything available here.',
  browseParentCategory: 'Back to {name}',
  categoryNotFound: 'Category not found.',
  pageNotFound: 'Page not found',
  pageNotFoundBody: "The page you're looking for doesn't exist or has been moved.",
  goToHomepage: 'Go to homepage',
  dragToReorder: 'Drag to reorder',
  featured: 'Featured',
  shopNewArrivals: 'Shop new arrivals',
  filters: 'Filters',
  refine: 'Refine',
  clearRating: 'Clear rating',
  showResults: 'Show results',
  sort: 'Sort',
  compare: 'Compare',
  sortTrending: 'Trending',
  sortNewest: 'Newest',
  sortPriceLowHigh: 'Price: Low to High',
  sortPriceHighLow: 'Price: High to Low',
  sortTopRated: 'Top Rated',
  productCountSingular: '{count} product',
  productCountPlural: '{count} products',
  updatingEllipsis: 'Updating…',
  browseCollection: 'Browse collection',
  starsAndUp: '{count}+ stars',
  // Platform settings
  platformSettings: 'Platform Settings',
  platformSettingsHint:
    'Manage commission, returns, shipping thresholds, support contact, and moderation defaults.',
  settingsCommerce: 'Commerce',
  settingsCommerceHint: 'Commission and product moderation defaults.',
  settingsFulfillment: 'Fulfillment',
  settingsFulfillmentHint: 'Returns, free shipping, and payout timing.',
  settingsSupport: 'Support',
  settingsSupportHint: 'Customer-facing contact details.',
  defaultCommissionRate: 'Default commission rate',
  autoApproveProducts: 'Auto-approve products',
  autoApproveEnabled: 'Enabled (auto-approve)',
  autoApproveDisabled: 'Disabled (moderated)',
  defaultReturnWindow: 'Default return window',
  freeShippingThreshold: 'Free shipping threshold',
  payoutCycle: 'Payout cycle',
  payoutCycleWeekly: 'Weekly',
  payoutCycleBiweekly: 'Bi-weekly',
  payoutCycleMonthly: 'Monthly',
  payoutCycleWeeklyLegacy: 'Weekly (legacy)',
  supportEmail: 'Support email',
  supportHours: 'Support hours',
  saveSettings: 'Save settings',
  settingsSaved: 'Settings saved.',
  couldNotSaveSettings: 'Could not save settings.',
  couldNotLoadSettings: 'Could not load platform settings from the server.',
  settingsUnavailable: 'Settings unavailable.',
  loadingPlatformSettings: 'Loading platform settings…',
  addTaxRule: 'Add tax rule',
  enterGstPercentage: 'Enter a GST percentage to continue.',
  gstPercentage: 'GST %',
  hsnOptional: 'HSN (optional)',
  addShippingZone: 'Add shipping zone',
  enterZoneName: 'Enter a zone name to continue.',
  zoneName: 'Zone name',
  decreaseValue: 'Decrease value',
  increaseValue: 'Increase value',
  pickDateTime: 'Pick date & time',
  previousMonth: 'Previous month',
  nextMonth: 'Next month',
  hour: 'Hour',
  minute: 'Minute',
  done: 'Done',
  createCoupon: 'Create coupon',
  couponValue: 'Value',
  maxDiscountCap: 'Max discount cap',
  minOrderValue: 'Min order value',
  startDate: 'Start date',
  endDate: 'End date',
  couponTypePercentage: 'Percentage',
  couponTypeFlat: 'Flat amount',
  couponTypeFreeShipping: 'Free shipping',
  couponTypeBogo: 'Buy one get one',
  couponTypeTiered: 'Tiered',
  couponTypeCashback: 'Cashback',
  couponTypeBundle: 'Bundle',
  daysShort: 'days',
  completeCouponFields: 'Add a code, type, start date, and end date to create a coupon.',
  fieldRequired: 'Required',
  enterCouponCode: 'Enter a coupon code.',
  enterCouponValue: 'Enter a value for this coupon type.',
  enterCouponStartDate: 'Choose a start date and time.',
  enterCouponEndDate: 'Choose an end date and time after the start.',
  couponCreateHint: 'Complete all required fields to create this coupon.',
  adminPanel: 'Admin Panel',
  brandName: 'Marketplace',
  menu: 'Menu',
  closeMenu: 'Close menu',
  search: 'Search',
  cart: 'Cart',
  wishlist: 'Wishlist',
  profile: 'Profile',
  account: 'Account',
  themeLight: 'Light',
  themeDark: 'Dark',
  openAccountMenu: 'Open account menu',
  browseCategories: 'Browse categories',
  browse: 'Browse',
  viewAll: 'View all',
  shopByCategory: 'Shop by category',
  noCategoriesYet: 'No categories yet',
  browseProducts: 'Browse products',
  digDeeper: 'Dig deeper',
  subcategories: 'Subcategories',
  shopInCategory: 'Browse',
  shopAll: 'Shop all',
  categoriesIndexHint:
    'Explore every collection on {site} — from makers and studios across the country.',
  categoryImageUnavailable: '{name} image not available',
  minPricePlaceholder: 'Min',
  maxPricePlaceholder: 'Max',
  minimumPrice: 'Minimum price',
  maximumPrice: 'Maximum price',
  help: 'Help',
  productNamePlaceholder: 'Product name',
  pricePlaceholder: 'Price',
  shortDescription: 'Short description',
  creatingEllipsis: 'Creating…',
  createProduct: 'Create product',
  moreCategoriesCount: '+{count} more',
  privacyPreferences: 'Preferences',
  privacyAndData: 'Privacy & data',
  appearance: 'Appearance',
  appearanceHintCustomer: 'Light or dark for the storefront. Saved on this device.',
  appearanceHintWorkspace: 'Light or dark for the admin and vendor consoles. Saved on this device.',
  downloadMyData: 'Download my data',
  downloadMyDataHintCustomer:
    'Export a JSON copy of your profile, addresses, orders, reviews, returns, and wishlist.',
  download: 'Download',
  signOut: 'Sign out',
  signOutHint: 'End this session on this device.',
  signOutConfirmTitle: 'Sign out?',
  signOutConfirmBody: "You'll need to sign in again to access your account on this device.",
  dangerZone: 'Danger zone',
  deleteAccount: 'Delete account',
  deleteAccountHintCustomer:
    'Permanently deactivate your account. This cannot be undone from the storefront.',
  deleteAccountHintWorkspace: 'Permanently deactivate your account. This cannot be undone.',
  deleteAccountBody: "Your profile will be deactivated and you'll be signed out immediately.",
  deleteAccountConfirmTitle: 'Delete your account?',
  deleteAccountConfirmBody: 'Type DELETE to confirm. Your profile will be deactivated and you’ll be signed out.',
  confirmation: 'Confirmation',
  couldNotExportAccount: 'Could not export account data.',
  couldNotDeleteAccount: 'Could not delete account.',
  phoneOptionalDelivery: 'Optional — used for delivery updates.',
  phoneOptionalContact: 'Optional — used for account recovery contact.',
  personalInfoFooterCustomer:
    'Keep your name, phone, and email current for orders and account recovery.',
  personalInfoFooterWorkspace:
    'Keep your name, phone, and email current for account recovery.',
  emailFixedStorefront: 'Email addresses are fixed on this account and cannot be changed from the storefront.',
  emailFixedWorkspace: 'Email addresses are fixed on this account and cannot be changed here.',
  accountSettingsHintCustomer:
    'Manage your profile, security, addresses, and preferences — quietly, clearly.',
  accountSettingsHintWorkspace:
    'Manage your profile, security, and preferences — quietly, clearly.',
  privacyAndDataHintCustomer:
    'Control appearance on this device, export your data, or end your session.',
  privacyAndDataHintWorkspace: 'Control appearance on this device or end your session.',
  privacySectionDescCustomer: 'Data and account deletion',
  privacySectionDescWorkspace: 'Appearance, sign out, and account deletion',
} as const

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_ORDER_MANAGER: 'ADMIN_ORDER_MANAGER',
  ADMIN_CATALOG_MANAGER: 'ADMIN_CATALOG_MANAGER',
  VENDOR_OWNER: 'VENDOR_OWNER',
  VENDOR_STAFF: 'VENDOR_STAFF',
  CUSTOMER: 'CUSTOMER',
} as const

export type RoleName = (typeof ROLES)[keyof typeof ROLES]
export const ROLE_VALUES = Object.values(ROLES) as [RoleName, ...RoleName[]]

export const ROLE_LABELS: Record<RoleName, string> = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.ADMIN_ORDER_MANAGER]: 'Order Manager',
  [ROLES.ADMIN_CATALOG_MANAGER]: 'Catalog Manager',
  [ROLES.VENDOR_OWNER]: 'Vendor Owner',
  [ROLES.VENDOR_STAFF]: 'Vendor Staff',
  [ROLES.CUSTOMER]: 'Customer',
}

export const ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN_ORDER_MANAGER,
  ROLES.ADMIN_CATALOG_MANAGER,
] as const

export const VENDOR_ROLES = [ROLES.VENDOR_OWNER, ROLES.VENDOR_STAFF] as const
