/** Shared UI labels — single source for nav, footer, and repeated CTAs. */
export const LABELS = {
  // CTAs / commerce
  continueShopping: 'Continue shopping',
  outOfStock: 'Out of stock',
  addToWishlist: 'Add to wishlist',
  removeFromWishlist: 'Remove from wishlist',
  addToCart: 'Add to cart',
  approvalQueue: 'Approval queue',
  newArrivals: 'New Arrivals',
  topRated: 'Top Rated',
  allProducts: 'All Products',
  shop: 'Shop',
  goToMyOrders: 'Go to my orders',
  allOrders: 'All orders',

  // Auth
  logIn: 'Log in',
  backToLogin: 'Back to login',
  alreadyHaveAccount: 'Already have an account?',
  welcomeBack: 'Welcome back',
  logInToAccount: 'Log in to your account',
  dontHaveAccount: "Don't have an account?",
  register: 'Register',
  loginFailed: 'Login failed',

  // Footer sections
  company: 'Company',
  customerService: 'Customer Service',
  sellOnMarketplace: 'Sell on Marketplace',
  connect: 'Connect',

  // Footer / nav link labels
  about: 'About',
  contact: 'Contact',
  blog: 'Blog',
  faq: 'FAQ',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  trackOrder: 'Track Order',
  helpCenter: 'Help Center',
  becomeSeller: 'Become a Seller',
  vendorDashboard: 'Vendor Dashboard',

  // Admin nav
  vendors: 'Vendors',
  products: 'Products',
  categories: 'Categories',
  orders: 'Orders',
  returnsRefunds: 'Returns / Refunds',
  coupons: 'Coupons',
  reviews: 'Reviews',
  tax: 'Tax',
  shipping: 'Shipping',
  financePayouts: 'Finance / Payouts',
  users: 'Users',
  analytics: 'Analytics',
  analyticsHint:
    'Commerce health, growth trends, and queues that need attention — tuned for the marketplace.',
  analyticsGmv: 'Gross merchandise volume',
  analyticsPaidGmv: 'Paid GMV',
  analyticsAov: 'Average order value',
  analyticsTotalOrders: 'Orders',
  analyticsCustomers: 'Customers',
  analyticsVendors: 'Vendors',
  analyticsCancellationRate: 'Cancellation rate',
  analyticsReturnRate: 'Return rate',
  analyticsOrderTrend: 'Order & revenue trend',
  analyticsOrderTrendHint: 'Non-cancelled orders over the last 30 days',
  analyticsOrdersByStatus: 'Orders by status',
  analyticsPaymentsByStatus: 'Payments by status',
  analyticsPaymentsTotal: 'Payments',
  analyticsTopVendors: 'Top vendors',
  analyticsTopCategories: 'Top categories',
  analyticsRatingDistribution: 'Approved review ratings',
  analyticsOpsQueues: 'Needs attention',
  analyticsPendingProducts: 'Pending products',
  analyticsPendingVendors: 'Pending vendors',
  analyticsPendingReviews: 'Pending reviews',
  analyticsGrowthOrders: 'Orders (14d)',
  analyticsGrowthRevenue: 'Revenue (14d)',
  analyticsNoData: 'No analytics data available',
  analyticsOrdersSeries: 'Orders',
  analyticsRevenueSeries: 'Revenue',
  analyticsRankShare: '{value}% of top total',
  analyticsEmptyChart: 'Not enough data to chart yet.',
  analyticsStarRating: '{rating}★',
  analyticsVsPriorPeriod: 'vs prior 14 days',
  percentValue: '{value}%',
  audit: 'Audit',
  settings: 'Settings',

  // Vendor / account nav
  overview: 'Overview',
  payouts: 'Payouts',
  personalInfo: 'Personal info',
  security: 'Security',
  addresses: 'Addresses',
  privacy: 'Privacy',

  // Return reasons
  returnReasonDamaged: 'Damaged',
  returnReasonWrongItem: 'Wrong item',
  returnReasonNotAsDescribed: 'Not as described',
  returnReasonNoLongerNeeded: 'No longer needed',
  returnReasonOther: 'Other',

  // Unavailable item badges
  unavailableReasonOutOfStock: 'Out of stock',
  unavailableReasonProductUnpublished: 'No longer available',
  unavailableReasonVendorUnavailable: 'Shop unavailable',
  unavailableGeneric: 'Unavailable',

  // Cart / checkout unavailability
  removeUnavailableToCheckout: 'Remove unavailable items to continue',

  // Vendor storefront unavailable
  shopUnavailableHeading: 'This shop is unavailable',
  shopUnavailableBody: 'The shop you are looking for is no longer active or has been removed.',
  browseOtherShops: 'Browse other shops',

  // Coupon messages
  couponRemovedUnavailable: 'Coupon was removed because some items are no longer available.',
  couponRemovedCartChange: 'Your coupon was removed due to cart changes.',

  // Tables / pagination
  refresh: 'Refresh',
  loading: 'Loading…',
  noRecordsFound: 'No records found.',
  recordDetails: 'Record details',
  recordDetailsHint: 'Full fields for this row, including values not shown in the table.',
  noDetailFields: 'No fields to display.',
  viewRecordDetails: 'View record details',
  close: 'Close',
  noCoupons: 'No coupons',
  actions: 'Actions',
  pageOf: 'Page {current} of {total}',
  showingResults: 'Showing {from}–{to} of {total}',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  firstPageHint: "You're on the first page.",
  lastPageHint: "You're on the last page.",
  couldNotLoadData: 'Could not load data',
  approve: 'Approve',
  reject: 'Reject',
  cancel: 'Cancel',
  suspend: 'Suspend',
  archive: 'Archive',
  activate: 'Activate',
  block: 'Block',
  delete: 'Delete',
  edit: 'Edit',
  confirm: 'Confirm',
  processPayouts: 'Process payouts',
  commissions: 'Commissions',
  couponCode: 'Code',
  couponType: 'Type',
  couponUsage: 'Usage',
  status: 'Status',
  expires: 'Expires',
  businessName: 'Business Name',
  vendorName: 'Vendor',
  productName: 'Product',
  customerName: 'Customer',
  actorName: 'Actor',
  category: 'Category',
  email: 'Email',
  role: 'Role',
  createdAt: 'Created',
  basePrice: 'Price',
  totalAmount: 'Total',
  rating: 'Rating',
  title: 'Title',
  body: 'Review',
  reason: 'Reason',
  reasonCode: 'Reason code',
  refundAmount: 'Refund',
  saleAmount: 'Sale amount',
  commissionRate: 'Commission rate',
  commissionAmount: 'Commission',
  amount: 'Amount',
  periodStart: 'Period start',
  periodEnd: 'Period end',
  action: 'Action',
  entityType: 'Entity',
  hsnCode: 'HSN',
  states: 'States',
  pincodePrefixes: 'Pincode prefixes',
  yes: 'Yes',
  no: 'No',
  slug: 'Slug',
  rejectionReason: 'Rejection reason',
  suspensionReason: 'Suspension reason',
  product: 'Product',
  price: 'Price',
  rejectionNote: 'Rejection note',
  reasonRequired: 'Reason required',
  enterRejectionNote: 'Enter a rejection note before rejecting.',
  enterRejectionReason: 'Enter a rejection reason before rejecting.',
  vendorApprovalQueue: 'Vendor Approval Queue',
  productModerationQueue: 'Product Moderation Queue',
  noPendingVendorApprovals: 'No pending vendor approvals',
  noPendingProductApprovals: 'No pending product approvals',
  pendingReview: 'Pending review',
  allVendors: 'All vendors',
  countOverflow: '99+',
  confirmApproveVendorTitle: 'Approve this vendor?',
  confirmApproveVendorBody: '"{name}" will be approved and can sell on the marketplace.',
  confirmRejectVendorTitle: 'Reject this vendor?',
  confirmRejectVendorBody: '"{name}" will be rejected. Share a clear reason for the seller.',
  confirmApproveProductTitle: 'Approve this product?',
  confirmApproveProductBody: '"{name}" will go live for customers once approved.',
  confirmRejectProductTitle: 'Reject this product?',
  confirmRejectProductBody: '"{name}" will be sent back to the vendor. Include a rejection note.',
  thisItem: 'this item',
  confirmSuspendVendorTitle: 'Suspend this vendor?',
  confirmSuspendVendorBody: '"{name}" will be suspended and hidden from customers. Provide a reason.',
  confirmArchiveProductTitle: 'Archive this product?',
  confirmArchiveProductBody: '"{name}" will be archived and removed from the live catalog.',
  confirmOrderTitle: 'Confirm this order?',
  confirmOrderBody: 'Mark order "{name}" as confirmed?',
  confirmApproveReturnTitle: 'Approve this return?',
  confirmApproveReturnBody: 'Approve return request "{name}" and continue the refund flow?',
  confirmApproveReviewTitle: 'Approve this review?',
  confirmApproveReviewBody: 'Publish review "{name}" for shoppers to see?',
  confirmRejectReviewTitle: 'Reject this review?',
  confirmRejectReviewBody: 'Reject review "{name}"? It will not appear publicly.',
  confirmDeleteCategoryTitle: 'Delete this category?',
  confirmDeleteCategoryBody:
    'Delete "{name}"? Categories with products or subcategories cannot be deleted.',
  confirmDeleteTaxTitle: 'Delete this tax rule?',
  confirmDeleteTaxBody: 'Delete tax rule "{name}"? This cannot be undone.',
  confirmDeleteShippingTitle: 'Delete this shipping zone?',
  confirmDeleteShippingBody: 'Delete shipping zone "{name}"? Rates in this zone will be affected.',
  confirmBlockUserTitle: 'Block this user?',
  confirmBlockUserBody: 'Block "{name}"? They will no longer be able to sign in.',
  confirmActivateUserTitle: 'Activate this user?',
  confirmActivateUserBody: 'Activate "{name}" and restore account access?',
  confirmDeleteUserTitle: 'Delete this user?',
  confirmDeleteUserBody: 'Delete "{name}"? This cannot be undone.',
  confirmProcessPayoutsTitle: 'Process payouts?',
  confirmProcessPayoutsBody: 'Process pending payouts for eligible vendors now?',
  enterSuspendReason: 'Enter a suspension reason before continuing.',
  create: 'Create',
  save: 'Save',
  newCategory: 'New category',
  createCategory: 'Create category',
  createCategoryHint: 'Add a catalog category with optional parent, image, and status.',
  enterCategoryName: 'Enter a category name to create.',
  editCategoryTitle: 'Edit category',
  editCategoryBody: 'Update name, parent, image, and status for this category.',
  categoryName: 'Category name',
  categoryNameRequired: 'Category name is required',
  enterCategoryNameToSave: 'Enter a category name to save.',
  imageNotAvailable: 'Image not available',
  parentCategory: 'Parent category',
  parentCategoryNone: 'None (top-level)',
  selectParentCategory: 'Select a parent category',
  categoryImageUrl: 'Image URL',
  categoryImageUrlPlaceholder: 'https://…',
  categoryImageUrlInvalid: 'Enter a valid image URL',
  categoryStatus: 'Status',
  categoryStatusActive: 'Active',
  categoryStatusArchived: 'Archived',
  name: 'Name',
  imageUrl: 'Image',
  parentId: 'Parent',
  parentName: 'Parent',
  // Platform settings
  platformSettings: 'Platform Settings',
  platformSettingsHint:
    'Manage commission, returns, shipping thresholds, support contact, and moderation defaults.',
  settingsCommerce: 'Commerce',
  settingsCommerceHint: 'Commission and product moderation defaults.',
  settingsFulfillment: 'Fulfillment',
  settingsFulfillmentHint: 'Returns, free shipping, and payout timing.',
  settingsSupport: 'Support',
  settingsSupportHint: 'Customer-facing contact details.',
  defaultCommissionRate: 'Default commission rate',
  autoApproveProducts: 'Auto-approve products',
  autoApproveEnabled: 'Enabled (auto-approve)',
  autoApproveDisabled: 'Disabled (moderated)',
  defaultReturnWindow: 'Default return window',
  freeShippingThreshold: 'Free shipping threshold',
  payoutCycle: 'Payout cycle',
  payoutCycleWeekly: 'Weekly',
  payoutCycleBiweekly: 'Bi-weekly',
  payoutCycleMonthly: 'Monthly',
  payoutCycleWeeklyLegacy: 'Weekly (legacy)',
  supportEmail: 'Support email',
  supportHours: 'Support hours',
  saveSettings: 'Save settings',
  settingsSaved: 'Settings saved.',
  couldNotSaveSettings: 'Could not save settings.',
  couldNotLoadSettings: 'Could not load platform settings from the server.',
  settingsUnavailable: 'Settings unavailable.',
  loadingPlatformSettings: 'Loading platform settings…',
  addTaxRule: 'Add tax rule',
  enterGstPercentage: 'Enter a GST percentage to continue.',
  gstPercentage: 'GST %',
  hsnOptional: 'HSN (optional)',
  addShippingZone: 'Add shipping zone',
  enterZoneName: 'Enter a zone name to continue.',
  zoneName: 'Zone name',
  decreaseValue: 'Decrease value',
  increaseValue: 'Increase value',
  pickDateTime: 'Pick date & time',
  previousMonth: 'Previous month',
  nextMonth: 'Next month',
  hour: 'Hour',
  minute: 'Minute',
  done: 'Done',
  createCoupon: 'Create coupon',
  couponValue: 'Value',
  maxDiscountCap: 'Max discount cap',
  minOrderValue: 'Min order value',
  startDate: 'Start date',
  endDate: 'End date',
  couponTypePercentage: 'Percentage',
  couponTypeFlat: 'Flat amount',
  couponTypeFreeShipping: 'Free shipping',
  couponTypeBogo: 'Buy one get one',
  couponTypeTiered: 'Tiered',
  couponTypeCashback: 'Cashback',
  couponTypeBundle: 'Bundle',
  selectCategory: 'Select category',
  daysShort: 'days',
  completeCouponFields: 'Add a code, type, start date, and end date to create a coupon.',
  fieldRequired: 'Required',
  enterCouponCode: 'Enter a coupon code.',
  enterCouponValue: 'Enter a value for this coupon type.',
  enterCouponStartDate: 'Choose a start date and time.',
  enterCouponEndDate: 'Choose an end date and time after the start.',
  couponCreateHint: 'Complete all required fields to create this coupon.',
  adminPanel: 'Admin Panel',
  brandName: 'Marketplace',
  menu: 'Menu',
  closeMenu: 'Close menu',
  search: 'Search',
  cart: 'Cart',
  wishlist: 'Wishlist',
  profile: 'Profile',
  account: 'Account',
  themeLight: 'Light',
  themeDark: 'Dark',
  openAccountMenu: 'Open account menu',
  browseCategories: 'Browse categories',
  privacyPreferences: 'Preferences',
  privacyAndData: 'Privacy & data',
  appearance: 'Appearance',
  appearanceHintCustomer: 'Light or dark for the storefront. Saved on this device.',
  appearanceHintWorkspace: 'Light or dark for the admin and vendor consoles. Saved on this device.',
  downloadMyData: 'Download my data',
  downloadMyDataHintCustomer:
    'Export a JSON copy of your profile, addresses, orders, reviews, returns, and wishlist.',
  download: 'Download',
  signOut: 'Sign out',
  signOutHint: 'End this session on this device.',
  signOutConfirmTitle: 'Sign out?',
  signOutConfirmBody: "You'll need to sign in again to access your account on this device.",
  dangerZone: 'Danger zone',
  deleteAccount: 'Delete account',
  deleteAccountHintCustomer:
    'Permanently deactivate your account. This cannot be undone from the storefront.',
  deleteAccountHintWorkspace: 'Permanently deactivate your account. This cannot be undone.',
  deleteAccountBody: "Your profile will be deactivated and you'll be signed out immediately.",
  deleteAccountConfirmTitle: 'Delete your account?',
  deleteAccountConfirmBody: 'Type DELETE to confirm. Your profile will be deactivated and you’ll be signed out.',
  confirmation: 'Confirmation',
  couldNotExportAccount: 'Could not export account data.',
  couldNotDeleteAccount: 'Could not delete account.',
  phoneOptionalDelivery: 'Optional — used for delivery updates.',
  phoneOptionalContact: 'Optional — used for account recovery contact.',
  personalInfoFooterCustomer:
    'Keep your name, phone, and email current for orders and account recovery.',
  personalInfoFooterWorkspace:
    'Keep your name, phone, and email current for account recovery.',
  emailFixedStorefront: 'Email addresses are fixed on this account and cannot be changed from the storefront.',
  emailFixedWorkspace: 'Email addresses are fixed on this account and cannot be changed here.',
  accountSettingsHintCustomer:
    'Manage your profile, security, addresses, and preferences — quietly, clearly.',
  accountSettingsHintWorkspace:
    'Manage your profile, security, and preferences — quietly, clearly.',
  privacyAndDataHintCustomer:
    'Control appearance on this device, export your data, or end your session.',
  privacyAndDataHintWorkspace: 'Control appearance on this device or end your session.',
  privacySectionDescCustomer: 'Data and account deletion',
  privacySectionDescWorkspace: 'Appearance, sign out, and account deletion',
} as const

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_ORDER_MANAGER: 'ADMIN_ORDER_MANAGER',
  ADMIN_CATALOG_MANAGER: 'ADMIN_CATALOG_MANAGER',
  VENDOR_OWNER: 'VENDOR_OWNER',
  VENDOR_STAFF: 'VENDOR_STAFF',
  CUSTOMER: 'CUSTOMER',
} as const

export type RoleName = (typeof ROLES)[keyof typeof ROLES]
export const ROLE_VALUES = Object.values(ROLES) as [RoleName, ...RoleName[]]

export const ROLE_LABELS: Record<RoleName, string> = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.ADMIN_ORDER_MANAGER]: 'Order Manager',
  [ROLES.ADMIN_CATALOG_MANAGER]: 'Catalog Manager',
  [ROLES.VENDOR_OWNER]: 'Vendor Owner',
  [ROLES.VENDOR_STAFF]: 'Vendor Staff',
  [ROLES.CUSTOMER]: 'Customer',
}

export const ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN_ORDER_MANAGER,
  ROLES.ADMIN_CATALOG_MANAGER,
] as const

export const VENDOR_ROLES = [ROLES.VENDOR_OWNER, ROLES.VENDOR_STAFF] as const
