/** Shared UI labels — single source for nav, footer, and repeated CTAs. */
export const LABELS = {
  // CTAs / commerce
  continueShopping: 'Continue shopping',
  outOfStock: 'Out of stock',
  addToWishlist: 'Add to wishlist',
  removeFromWishlist: 'Remove from wishlist',
  addToCart: 'Add to cart',
  approvalQueue: 'Approval queue',
  newArrivals: 'New Arrivals',
  topRated: 'Top Rated',
  allProducts: 'All Products',
  shop: 'Shop',
  goToMyOrders: 'Go to my orders',
  allOrders: 'All orders',

  // Auth
  logIn: 'Log in',
  backToLogin: 'Back to login',
  alreadyHaveAccount: 'Already have an account?',
  welcomeBack: 'Welcome back',
  logInToAccount: 'Log in to your account',
  dontHaveAccount: "Don't have an account?",
  register: 'Register',
  loginFailed: 'Login failed',
  createAccount: 'Create an account',
  createAccountHint: 'Join the marketplace in a few steps.',
  phoneOptional: 'Phone (optional)',
  forgotPassword: 'Forgot password?',
  forgotPasswordTitle: 'Forgot password',
  forgotPasswordHint: 'Enter your email and we’ll send you a reset link.',
  sendResetLink: 'Send reset link',
  resetLinkSent: 'If that email exists, a reset link has been sent.',
  resetPasswordTitle: 'Reset password',
  resetPasswordHint: 'Choose a new password for your account.',
  newPassword: 'New password',
  resetPassword: 'Reset password',
  resetPasswordFailed: 'Reset failed or link expired.',
  password: 'Password',
  verifyOtpTitle: 'Verify OTP',
  verifyOtpHint: 'Enter the 6-digit code sent to your email.',
  resendCode: 'Resend code',
  resendCodeWait: 'You can resend a new code after the timer ends.',
  verifyCode: 'Verify code',
  enterCompleteOtp: 'Enter the complete 6-digit code to verify.',
  orContinueWith: 'Or continue with',
  continueWithGoogle: 'Continue with Google',
  authBrandHeadline: 'Shop with clarity.',
  authBrandBody: 'Curated finds, trusted sellers, and a checkout experience that stays out of your way.',
  authBrandFooter: 'Secure sign-in · Encrypted sessions',
  changePasswordTitle: 'Change password',
  changePasswordHint: 'Use a strong password you don’t reuse elsewhere.',
  changePasswordSuccess: 'Password changed successfully.',
  changePasswordAgain: 'Change again',
  currentPassword: 'Current password',
  changePassword: 'Change password',
  couldNotChangePassword: 'Could not change password.',

  // Footer sections
  company: 'Company',
  customerService: 'Customer Service',
  sellOnMarketplace: 'Sell on Marketplace',
  connect: 'Connect',

  // Footer / nav link labels
  about: 'About',
  contact: 'Contact',
  blog: 'Blog',
  faq: 'FAQ',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  trackOrder: 'Track Order',
  helpCenter: 'Help Center',
  becomeSeller: 'Become a Seller',
  vendorDashboard: 'Vendor Dashboard',

  // Admin nav
  vendors: 'Vendors',
  products: 'Products',
  categories: 'Categories',
  orders: 'Orders',
  returnsRefunds: 'Returns / Refunds',
  coupons: 'Coupons',
  reviews: 'Reviews',
  tax: 'Tax',
  shipping: 'Shipping',
  financePayouts: 'Finance / Payouts',
  users: 'Users',
  analytics: 'Analytics',
  analyticsHint:
    'Commerce health, growth trends, and queues that need attention — tuned for the marketplace.',
  analyticsGmv: 'Gross merchandise volume',
  analyticsPaidGmv: 'Paid GMV',
  analyticsAov: 'Average order value',
  analyticsTotalOrders: 'Orders',
  analyticsCustomers: 'Customers',
  analyticsVendors: 'Vendors',
  analyticsCancellationRate: 'Cancellation rate',
  analyticsReturnRate: 'Return rate',
  analyticsOrderTrend: 'Order & revenue trend',
  analyticsOrderTrendHint: 'Non-cancelled orders over the last 30 days',
  analyticsOrdersByStatus: 'Orders by status',
  analyticsPaymentsByStatus: 'Payments by status',
  analyticsPaymentsTotal: 'Payments',
  analyticsTopVendors: 'Top vendors',
  analyticsTopCategories: 'Top categories',
  analyticsRatingDistribution: 'Approved review ratings',
  analyticsOpsQueues: 'Needs attention',
  analyticsPendingProducts: 'Pending products',
  analyticsPendingVendors: 'Pending vendors',
  analyticsPendingReviews: 'Pending reviews',
  analyticsGrowthOrders: 'Orders (14d)',
  analyticsGrowthRevenue: 'Revenue (14d)',
  analyticsNoData: 'No analytics data available',
  analyticsOrdersSeries: 'Orders',
  analyticsRevenueSeries: 'Revenue',
  analyticsRankShare: '{value}% of top total',
  analyticsEmptyChart: 'Not enough data to chart yet.',
  analyticsStarRating: '{rating}★',
  analyticsVsPriorPeriod: 'vs prior 14 days',
  percentValue: '{value}%',
  audit: 'Audit',
  settings: 'Settings',

  // Vendor / account nav
  overview: 'Overview',
  payouts: 'Payouts',
  personalInfo: 'Personal info',
  security: 'Security',
  addresses: 'Addresses',
  privacy: 'Privacy',

  // Return reasons
  returnReasonDamaged: 'Damaged',
  returnReasonWrongItem: 'Wrong item',
  returnReasonNotAsDescribed: 'Not as described',
  returnReasonNoLongerNeeded: 'No longer needed',
  returnReasonOther: 'Other',

  // Unavailable item badges
  unavailableReasonOutOfStock: 'Out of stock',
  unavailableReasonProductUnpublished: 'No longer available',
  unavailableReasonVendorUnavailable: 'Shop unavailable',
  unavailableGeneric: 'Unavailable',

  // Cart / checkout unavailability
  removeUnavailableToCheckout: 'Remove unavailable items to continue',

  // Vendor storefront unavailable
  shopUnavailableHeading: 'This shop is unavailable',
  shopUnavailableBody: 'The shop you are looking for is no longer active or has been removed.',
  browseOtherShops: 'Browse other shops',
  vendorsIndexEyebrow: 'Makers',
  vendorsIndexHint: 'Explore approved shops on {site}.',
  noVendorsYet: 'No shops to show yet',
  noVendorsYetHint: 'Approved vendors will appear here once they publish their storefront.',
  visitShop: 'Visit shop',

  // Coupon messages
  couponRemovedUnavailable: 'Coupon was removed because some items are no longer available.',
  couponRemovedCartChange: 'Your coupon was removed due to cart changes.',
  applyCoupon: 'Apply',
  removeCoupon: 'Remove',
  couponCodePlaceholder: 'Enter coupon code',
  couponApplied: 'Coupon applied — ₹{amount} off',
  couponAppliedCheckout: 'Coupon applied — discount will be calculated at checkout',
  couponInvalid: 'Invalid or expired coupon code',
  couponAppliedLabel: 'Applied: {code}',
  couponDiscount: 'Discount',
  availableOffers: 'Available offers',
  availableOffersCount: '{count} available offers',
  noAvailableOffers: 'No offers available for this cart.',
  applyOffer: 'Apply offer',
  offersAtCheckout: 'Offers available at checkout',
  autoAppliedOffer: 'Best available offer applied automatically.',
  signInToApplyCoupon: 'Sign in to apply coupon codes to your order.',
  enterCouponCodeToApply: 'Enter a coupon code to apply it.',
  couponSectionBasics: 'Basics',
  couponSectionValue: 'Value',
  couponSectionScope: 'Scope',
  couponSectionConstraints: 'Constraints',
  couponSectionRestrictions: 'Restrictions',
  discountBearer: 'Discount bearer',
  discountBearerPlatform: 'Platform',
  discountBearerVendor: 'Vendor',
  applicableScope: 'Applicable scope',
  scopeTypeAll: 'All products',
  scopeTypeVendor: 'Vendor',
  scopeTypeProduct: 'Products',
  scopeTypeCategory: 'Categories',
  scopeIds: 'Applicable items',
  selectScopeCategories: 'Select categories',
  selectScopeProducts: 'Select products',
  selectScopeVendors: 'Select vendors',
  searchCategories: 'Search categories',
  searchProducts: 'Search products',
  searchProductsVendors: 'Search products, vendors, categories...',
  searchVendors: 'Search vendors',
  searchSuggestions: 'Search suggestions',
  searchAutocompleteEmpty: 'No matching results',
  searchAutocompleteEmptyHint: 'Try another spelling, or browse products and shops.',
  searchSuggestionTypeProduct: 'Product',
  searchSuggestionTypeVendor: 'Vendor',
  searchSuggestionTypeCategory: 'Category',
  searchSuggestionSku: 'SKU {sku}',
  searchSuggestionProducts: 'Products',
  searchSuggestionVendors: 'Shops',
  searchSuggestionCategories: 'Categories',
  searchOpenResult: 'Open',
  noCategoriesFound: 'No categories found',
  noProductsFound: 'No products found',
  noVendorsFound: 'No vendors found',
  couponScopeNoneSelected: 'None selected',
  couponScopeSelectedCount: '{count} selected',
  couponScopeIdsRequired: 'Select at least one item for this scope',
  couponBundleProductsRequired: 'Select at least one bundle product',
  couponSegmentRequired: 'Select a customer segment',
  enterCouponScopeIds: 'Select at least one category, product, or vendor.',
  couponTierHint: 'Tier 1 uses min order value + value %. Optional tier 2 below.',
  couponTier2Min: 'Tier 2 min subtotal',
  couponTier2Percent: 'Tier 2 percent',
  selectBundleProducts: 'Bundle products',
  userRestrictionSegmentNew: 'New customers',
  userRestrictionSegmentReturning: 'Returning customers',
  userRestrictionSegmentLoyal: 'Loyal customers (3+ orders)',
  batchRedemptions: 'Redemptions',
  batchDiscountImpact: 'Discount impact',
  batchRevenueImpact: 'Revenue impact',
  batchCodes: 'Codes',
  batchExpires: 'Expires',
  viewBatchCodes: 'View codes',
  vendorDiscountBreakdown: 'Discount by seller',
  conversionRate: 'Conversion rate',
  revenueImpact: 'Revenue impact',
  discountCostImpact: 'Discount cost',
  rejectCoupon: 'Reject',
  confirmRejectCouponTitle: 'Reject this vendor coupon?',
  confirmRejectCouponBody: '"{code}" will be rejected and cannot be redeemed.',
  searchUsers: 'Search users by name or email',
  noUsersFound: 'No users found',
  couponSpecificUsersRequired: 'Select at least one user for this restriction',
  selectSpecificUsers: 'Eligible users',
  noPdpOffers: 'No offers available for this product.',
  absorbedThisPeriod: 'This calendar month',
  noneSelected: 'None selected',
  selectedCount: '{count} selected',
  loadingMore: 'Loading more…',
  noResults: 'No results found',
  couldNotLoadOptions: 'Could not load options',
  minQuantity: 'Min quantity',
  usageLimitTotal: 'Total usage limit',
  usageLimitPerUser: 'Per-user usage limit',
  stackable: 'Stackable',
  stackableHint: 'When enabled, this coupon can combine with other stackable coupons on the same order.',
  priority: 'Priority',
  userRestriction: 'User restriction',
  userRestrictionSegment: 'Customer segment',
  userRestrictionAll: 'All users',
  userRestrictionFirstOrder: 'First order only',
  userRestrictionSpecific: 'Specific users',
  pauseCoupon: 'Pause',
  activateCoupon: 'Activate',
  archiveCoupon: 'Archive',
  viewAnalytics: 'Analytics',
  couponAnalytics: 'Coupon analytics',
  redemptionCount: 'Redemptions',
  discountTotal: 'Discount cost',
  absorbedDiscounts: 'Absorbed discounts',
  absorbedDiscountsSummary: 'You absorbed ₹{amount} in discounts',
  bulkGenerate: 'Bulk generate',
  bulkGenerateTitle: 'Generate coupon batch',
  bulkBatchName: 'Batch name',
  bulkCount: 'Number of codes',
  bulkPrefix: 'Code prefix',
  couponBatches: 'Coupon batches',
  noCouponBatches: 'No coupon batches yet',
  batchGeneratedCount: 'Generated',
  vendorCoupons: 'Vendor coupons',
  platformCoupons: 'Platform coupons',
  allCoupons: 'All coupons',
  vendorId: 'Vendor',
  confirmPauseCouponTitle: 'Pause this coupon?',
  confirmPauseCouponBody: '"{code}" will stop accepting new redemptions until reactivated.',
  confirmActivateCouponTitle: 'Activate this coupon?',
  confirmActivateCouponBody: '"{code}" will become available for eligible carts.',
  confirmArchiveCouponTitle: 'Archive this coupon?',
  confirmArchiveCouponBody: '"{code}" will be archived and no longer usable.',
  couponCodeRequired: 'Code is required',
  couponCodeTooLong: 'Code must be 64 characters or fewer',
  couponTypeRequired: 'Type is required',
  couponValueNegative: 'Value cannot be negative',
  couponMaxDiscountNegative: 'Max discount cannot be negative',
  couponMinOrderNegative: 'Min order value cannot be negative',
  couponStartDateRequired: 'Start date is required',
  couponStartDateInvalid: 'Start date is invalid',
  couponEndDateRequired: 'End date is required',
  couponEndDateInvalid: 'End date is invalid',
  couponValueRequired: 'Value is required for this coupon type',
  couponPercentageMax: 'Percentage value cannot exceed 100',
  couponEndAfterStart: 'End date must be after start date',
  couponScopeTypeRequired: 'Scope type is required',
  couponBearerRequired: 'Discount bearer is required',
  couponBatchNameRequired: 'Batch name is required',
  couponBulkCountInvalid: 'Enter a count between 1 and 500',
  couponAppliedReview: 'Coupon {code} applied (−{amount})',
  vendorTotal: 'Vendor total',
  subtotal: 'Subtotal',
  freeShipping: 'Free',
  payableNow: 'Payable now',
  includingShippingTaxes: 'Including shipping and taxes',
  placeOrder: 'Place order',
  paymentUnavailableTitle: 'Payment unavailable',
  paymentUnavailableLoadScript: 'Unable to load payment checkout. Please try again.',
  paymentUnavailableMissingDetails: 'Payment could not be started. Missing order details from server.',
  paymentConfirmationPendingTitle: 'Confirmation pending',
  paymentConfirmationPendingBody:
    'Payment was received, but confirmation is still settling. Check Orders shortly.',
  paymentCancelledTitle: 'Payment cancelled',
  paymentCancelledBody:
    'No charge was made. Your cart has been restored and is ready whenever you want to try again.',
  paymentFailedTitle: 'Payment failed',
  paymentFailedBody:
    'Payment could not be completed. Your cart has been restored so you can try again.',
  placeOrderFailedTitle: 'Could not place order',
  placeOrderFailedBody: 'Could not place order. Please try again.',
  itemsUnavailableTitle: 'Items unavailable',
  backToPayment: 'Back to payment',
  preparingSummary: 'Preparing your summary',
  calculatingShippingTaxes: 'Calculating shipping and taxes for your order…',
  couponCodeLabel: 'Coupon code',
  yourCart: 'Your Cart',
  closeCart: 'Close cart',
  cartEmptyHeading: 'Your cart is empty',
  cartEmptyMessage: 'Add some items to get started.',
  checkout: 'Checkout',
  viewFullCart: 'View full cart',
  total: 'Total',
  qtyLabel: 'Qty {count}',
  taxIgst: 'IGST',
  taxCgstSgst: 'CGST + SGST',
  enterBatchName: 'Enter a batch name.',
  enterBulkCount: 'Enter how many codes to generate.',
  bulkGenerateHint: 'Complete the batch fields to generate codes.',
  createVendorCoupon: 'Create vendor coupon',
  noVendorCoupons: 'No vendor coupons',
  couponVendorScopeLocked: 'Scope is locked to your vendor catalog.',
  usageUnlimited: '∞',

  // Tables / pagination
  refresh: 'Refresh',
  loading: 'Loading…',
  noRecordsFound: 'No records found.',
  recordDetails: 'Record details',
  recordDetailsHint: 'Full fields for this row, including values not shown in the table.',
  noDetailFields: 'No fields to display.',
  viewRecordDetails: 'View record details',
  close: 'Close',
  noCoupons: 'No coupons',
  actions: 'Actions',
  moreActions: 'More actions',
  pageOf: 'Page {current} of {total}',
  showingResults: 'Showing {from}–{to} of {total}',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  firstPageHint: "You're on the first page.",
  lastPageHint: "You're on the last page.",
  couldNotLoadData: 'Could not load data',
  approve: 'Approve',
  reject: 'Reject',
  cancel: 'Cancel',
  suspend: 'Suspend',
  archive: 'Archive',
  activate: 'Activate',
  block: 'Block',
  delete: 'Delete',
  edit: 'Edit',
  confirm: 'Confirm',
  orderActionShip: 'Ship',
  orderActionDeliver: 'Deliver',
  updateStatus: 'Update',
  selectStatus: 'Select status',
  processPayouts: 'Process payouts',
  commissions: 'Commissions',
  couponCode: 'Code',
  couponType: 'Type',
  couponUsage: 'Usage',
  status: 'Status',
  expires: 'Expires',
  businessName: 'Business name',
  vendorName: 'Vendor',
  productName: 'Product',
  customerName: 'Customer',
  actorName: 'Actor',
  category: 'Category',
  email: 'Email',
  newsletterEmailPlaceholder: 'Your email',
  subscribe: 'Subscribe',
  newsletterInvalidEmail: 'Enter a valid email address',
  enterNewsletterEmail: 'Enter a valid email address to subscribe.',
  newsletterSuccess: "Thanks — you're on the list. We'll be in touch.",
  newsletterAlreadySubscribed: "You're already on the list. We'll be in touch.",
  newsletterCouldNotSubscribe: 'Could not subscribe right now. Try again or contact support.',
  trackingNumber: 'Tracking number',
  track: 'Track',
  role: 'Role',
  createdAt: 'Created',
  basePrice: 'Price',
  totalAmount: 'Total',
  rating: 'Rating',
  title: 'Title',
  body: 'Review',
  reason: 'Reason',
  reasonCode: 'Reason code',
  refundAmount: 'Refund',
  saleAmount: 'Sale amount',
  commissionRate: 'Commission rate',
  commissionAmount: 'Commission',
  amount: 'Amount',
  periodStart: 'Period start',
  periodEnd: 'Period end',
  action: 'Action',
  entityType: 'Business entity type',
  hsnCode: 'HSN',
  states: 'States',
  pincodePrefixes: 'Pincode prefixes',
  yes: 'Yes',
  no: 'No',
  slug: 'Slug',
  rejectionReason: 'Rejection reason',
  suspensionReason: 'Suspension reason',
  product: 'Product',
  price: 'Price',
  rejectionNote: 'Rejection note',
  reasonRequired: 'Reason required',
  enterRejectionNote: 'Enter a rejection note before rejecting.',
  enterRejectionReason: 'Enter a rejection reason before rejecting.',
  vendorApprovalQueue: 'Vendor Approval Queue',
  productModerationQueue: 'Product Moderation Queue',
  noPendingVendorApprovals: 'No pending vendor approvals',
  noPendingProductApprovals: 'No pending product approvals',
  pendingReview: 'Pending review',
  allVendors: 'All vendors',
  countOverflow: '99+',
  confirmApproveVendorTitle: 'Approve this vendor?',
  confirmApproveVendorBody: '"{name}" will be approved and can sell on the marketplace.',
  confirmRejectVendorTitle: 'Reject this vendor?',
  confirmRejectVendorBody: '"{name}" will be rejected. Share a clear reason for the seller.',
  confirmApproveProductTitle: 'Approve this product?',
  confirmApproveProductBody: '"{name}" will go live for customers once approved.',
  confirmRejectProductTitle: 'Reject this product?',
  confirmRejectProductBody: '"{name}" will be sent back to the vendor. Include a rejection note.',
  thisItem: 'this item',
  confirmSuspendVendorTitle: 'Suspend this vendor?',
  confirmSuspendVendorBody: '"{name}" will be suspended and hidden from customers. Provide a reason.',
  confirmArchiveProductTitle: 'Archive this product?',
  confirmArchiveProductBody: '"{name}" will be archived and removed from the live catalog.',
  confirmOrderTitle: 'Confirm this order?',
  confirmOrderBody: 'Mark order "{name}" as confirmed?',
  kycDocuments: 'KYC documents',
  viewKycDocuments: 'Documents',
  noKycDocuments: 'No KYC documents uploaded yet.',
  documentTypeGst: 'GST certificate',
  documentTypePan: 'PAN',
  documentTypeAadhaar: 'Aadhaar',
  documentTypeBank: 'Bank proof',
  documentTypeAddressProof: 'Address proof',
  documentTypeIncorporationCert: 'Incorporation certificate',
  documentTypePartnershipDeed: 'Partnership deed',
  documentTypeAuthorizedSignatoryId: 'Authorized signatory ID',
  documentTypeFssaiLicense: 'FSSAI license',
  documentTypeCategoryTradeLicense: 'Category / trade license',
  documentVerified: 'Verified',
  documentPending: 'Pending verification',
  documentNotUploaded: 'Not uploaded',
  documentRejected: 'Rejected',
  documentRejectionReason: 'Rejection reason',
  verifyDocument: 'Verify',
  rejectDocument: 'Reject',
  uploadKycDocument: 'Upload KYC document',
  uploadKycDocumentHint: 'Upload each required document. Rejected documents can be replaced.',
  kycDocumentUploaded: 'Document uploaded.',
  couldNotUploadKycDocument: 'Could not upload document.',
  kycChecklist: 'KYC checklist',
  kycChecklistHint: 'Required documents for your business type and categories.',
  kycChecklistIncomplete: 'Complete and verify all required documents before approval.',
  kycChecklistComplete: 'All required documents are verified.',
  couldNotLoadKycChecklist: 'Could not load KYC checklist.',
  kycApproveBlocked: 'Cannot approve until all required KYC documents are verified.',
  kycNameMismatchWarningAcknowledged: 'Name mismatch noted — review carefully when uploading documents.',
  submitForApproval: 'Submit for approval',
  couldNotSubmitProduct: 'Could not submit product for approval.',
  productSubmittedForApproval: 'Product submitted for approval.',
  couldNotOpenDocument: 'Could not open document.',
  saveCategories: 'Save categories',
  categoriesSaved: 'Categories updated. Check the KYC checklist for any new requirements.',
  couldNotSaveCategories: 'Could not save categories.',
  entityTypeSole: 'Sole proprietorship',
  entityTypePartnership: 'Partnership',
  entityTypeLlp: 'LLP',
  entityTypePrivateLimited: 'Private limited',
  vendorCategories: 'Selling categories',
  vendorCategoriesHint: 'Select the categories you plan to sell in. Extra regulated categories may require more documents.',
  panHolderName: 'Name on PAN',
  bankAccountHolderName: 'Bank account holder name',
  kycNameMismatchWarning:
    'Bank account holder name does not match the name on PAN. This is a common rejection reason — double-check before submitting.',
  requiredDocuments: 'Required documents',
  registerAsVendor: 'Register as a vendor',
  registerAsVendorHint: 'Tell us your entity type and categories first so we can list the documents you need.',
  registrationFailed: 'Registration failed. Try again.',
  businessDescriptionOptional: 'Description (optional)',
  gstNumberOptional: 'GST number (optional)',
  startSelling: 'Start selling on the marketplace',
  promoBanners: 'Promo banners',
  promoBannersHint: 'Homepage hero banners. Upload the image first, then save the banner.',
  promoBannerTitle: 'Title',
  promoBannerImage: 'Banner image',
  promoBannerLinkType: 'Link type',
  promoBannerLinkTargetId: 'Link target ID',
  promoBannerLinkUrl: 'Link URL',
  promoBannerPriority: 'Priority',
  promoBannerStatus: 'Status',
  promoBannerStartDate: 'Start date',
  promoBannerEndDate: 'End date',
  createPromoBanner: 'Create banner',
  noPromoBanners: 'No promo banners yet.',
  couldNotLoadPromoBanners: 'Could not load promo banners.',
  couldNotSavePromoBanner: 'Could not save promo banner.',
  promoBannerSaved: 'Promo banner saved.',
  promoBannerDeleted: 'Promo banner deleted.',
  enterPromoBannerTitle: 'Enter a banner title to continue.',
  uploadPromoBannerImage: 'Upload a banner image to continue.',
  enterPromoBannerLinkUrl: 'Enter a link URL to continue.',
  enterPromoBannerLinkTarget: 'Enter a link target ID to continue.',
  confirmDeletePromoBannerTitle: 'Delete this banner?',
  confirmDeletePromoBannerBody: 'Delete "{name}"? The image will be removed from storage.',
  shopNow: 'Shop now',
  promoBannerEyebrow: 'Featured',
  confirmVerifyDocumentTitle: 'Verify this document?',
  confirmVerifyDocumentBody: 'Mark "{type}" as verified for {name}.',
  confirmRejectDocumentTitle: 'Reject this document?',
  confirmRejectDocumentBody:
    '"{type}" for {name} will be rejected and removed. The seller will be notified by email.',
  openDocument: 'Open document',
  documentType: 'Document type',
  couldNotLoadDocuments: 'Could not load documents.',
  confirmApproveReturnTitle: 'Approve this return?',
  confirmApproveReturnBody: 'Approve return request "{name}" and continue the refund flow?',
  confirmApproveReviewTitle: 'Approve this review?',
  confirmApproveReviewBody: 'Publish review "{name}" for shoppers to see?',
  confirmRejectReviewTitle: 'Reject this review?',
  confirmRejectReviewBody: 'Reject review "{name}"? It will not appear publicly.',
  confirmDeleteCategoryTitle: 'Delete this category?',
  confirmDeleteCategoryBody:
    'Delete "{name}"? Categories with products or subcategories cannot be deleted.',
  confirmDeleteTaxTitle: 'Delete this tax rule?',
  confirmDeleteTaxBody: 'Delete tax rule "{name}"? This cannot be undone.',
  confirmDeleteShippingTitle: 'Delete this shipping zone?',
  confirmDeleteShippingBody: 'Delete shipping zone "{name}"? Rates in this zone will be affected.',
  confirmBlockUserTitle: 'Block this user?',
  confirmBlockUserBody: 'Block "{name}"? They will no longer be able to sign in.',
  confirmActivateUserTitle: 'Activate this user?',
  confirmActivateUserBody: 'Activate "{name}" and restore account access?',
  confirmDeleteUserTitle: 'Delete this user?',
  confirmDeleteUserBody: 'Delete "{name}"? This cannot be undone.',
  confirmProcessPayoutsTitle: 'Process payouts?',
  confirmProcessPayoutsBody: 'Process pending payouts for eligible vendors now?',
  enterSuspendReason: 'Enter a suspension reason before continuing.',
  create: 'Create',
  save: 'Save',
  newCategory: 'New category',
  createCategory: 'Create category',
  createCategoryHint: 'Add a catalog category with optional parent, image, and status.',
  enterCategoryName: 'Enter a category name to create.',
  editCategoryTitle: 'Edit category',
  editCategoryBody: 'Update name, parent, image, and status for this category.',
  categoryName: 'Category name',
  categoryNameRequired: 'Category name is required',
  enterCategoryNameToSave: 'Enter a category name to save.',
  imageNotAvailable: 'Image not available',
  parentCategory: 'Parent category',
  parentCategoryNone: 'None (top-level)',
  selectParentCategory: 'Select a parent category',
  categoryImageUrl: 'Image URL',
  categoryImageUrlPlaceholder: 'https://…',
  categoryImageUrlInvalid: 'Enter a valid image URL',
  categoryImageUpload: 'Category image',
  uploadFile: 'Upload file',
  uploadFiles: 'Upload files',
  uploading: 'Uploading…',
  uploadFailed: 'Could not upload file.',
  uploadStorageUnavailable:
    'File upload is temporarily unavailable. Please try again later.',
  uploadForbidden: 'You do not have permission to upload this file.',
  uploadTooLargeGeneric: 'File is too large.',
  unexpectedError: 'Something went wrong. Please try again.',
  unexpectedErrorHeading: 'Something went wrong',
  unexpectedErrorBody: 'Please try again. If the problem continues, contact support.',
  validationFailedGeneric: 'Please check the form and try again.',
  uploadTooLargeMb: 'File must be under {mb}MB.',
  uploadFileFailedAt: 'File {index}: {message}',
  uploadProfilePhoto: 'Upload profile photo',
  uploadProfilePhotoHint:
    'Recommended 512×512 (1:1). PNG, JPEG, or WebP up to 1.5MB. Edit after selecting.',
  uploadInvalidImageType: 'Please choose a PNG, JPEG, or WebP image.',
  imageCropTitle: 'Edit image',
  imageCropHint: 'Drag to reposition. Adjust zoom and rotation, then apply.',
  imageCropZoom: 'Zoom',
  imageCropRotation: 'Rotation',
  imageCropRotateLeft: 'Rotate left',
  imageCropRotateRight: 'Rotate right',
  imageCropReset: 'Reset',
  imageCropConfirm: 'Apply',
  imageCropProcessing: 'Processing…',
  categoryFormSectionBasics: 'Basics',
  categoryFormSectionImage: 'Image',
  categoryFormSectionSeo: 'SEO & commission',
  categoryFormSectionBasicsHint: 'Name, parent, and visibility.',
  categoryFormSectionImageHint: 'Upload and crop the category image.',
  categoryFormSectionSeoHint: 'Optional search metadata and commission override.',
  productFormSectionDetails: 'Product details',
  productFormSectionDetailsHint: 'Name, price, category, and short description.',
  productFormSectionImages: 'Images',
  productFormSectionImagesHint: 'Add one or more product photos.',
  promoBannerFormSection: 'Banner details',
  promoBannerFormSectionHint: 'Title, image, link, status, and priority.',
  promoBannerEditSection: 'Edit banner',
  promoBannerEditSectionHint: 'Update banner content and link settings.',
  vendorRegisterSectionBasics: 'Business details',
  vendorRegisterSectionBasicsHint: 'How your shop appears on the marketplace.',
  vendorRegisterSectionCategories: 'Categories',
  vendorRegisterSectionCategoriesHint: 'Select the categories you sell in.',
  vendorRegisterSectionIdentity: 'Identity & bank',
  vendorRegisterSectionIdentityHint: 'Used for KYC and payouts.',
  imageUploadHintPromoBanner:
    'Recommended 1920×1080 (16:9). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.',
  imageUploadHintCategory:
    'Recommended 1200×900 (4:3). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.',
  imageUploadHintProduct:
    'Recommended 1200×1200 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.',
  imageUploadHintVendorLogo:
    'Recommended 512×512 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.',
  imageUploadHintVendorBanner:
    'Recommended 1680×525 (16:5). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.',
  imageUploadHintAvatar:
    'Recommended 512×512 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.',
  imageUploadHintReturnPhoto:
    'Recommended 1600×1200 (4:3). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.',
  imageUploadHintKyc: 'PNG, JPEG, WebP, or PDF up to {mb}MB.',
  imageUploadHintTicketAttachment:
    'Up to 5 images (5MB each) and 1 video (60s / 50MB). PNG, JPEG, WebP, MP4, or WebM.',
  imageUploadHintBugAttachment:
    'Up to 5 screenshots (5MB each) and 1 screen recording (120s / 50MB). PNG, JPEG, WebP, MP4, or WebM.',
  imageUploadInvalidDocumentType: 'Please choose a PNG, JPEG, WebP, or PDF file.',
  returnPhotosLabel: 'Photos (optional)',
  productImagesLabel: 'Product images',
  manageProductImages: 'Manage product images',
  addProductImage: 'Add image',
  replaceImage: 'Replace image',
  deleteImage: 'Delete image',
  setPrimaryImage: 'Set as primary',
  primaryImage: 'Primary image',
  couldNotLoadProduct: 'Could not load product.',
  couldNotSaveProductImages: 'Could not save product images.',
  editPromoBanner: 'Edit banner',
  savePromoBanner: 'Save banner',
  confirmDeleteVendorTitle: 'Delete vendor?',
  confirmDeleteVendorBody: 'Delete "{name}" and all associated media? This cannot be undone.',
  confirmDeleteReturnTitle: 'Delete return?',
  confirmDeleteReturnBody: 'Delete return for "{name}" and its photos? This cannot be undone.',
  categoryStatus: 'Status',
  categoryStatusActive: 'Active',
  categoryStatusArchived: 'Archived',
  categorySeoTitle: 'SEO title',
  categorySeoDescription: 'SEO description',
  categoryCommissionRate: 'Category commission %',
  categoryCommissionRateHint: 'Optional override; leaves inherit from parents, then vendor default.',
  categoryCommissionPlaceholder: '0–100',
  categoryAttributes: 'Filter attributes',
  categoryAttributesHint: 'Define category-specific filters (Material, Size, etc.).',
  addCategoryAttribute: 'Add attribute',
  attributeName: 'Attribute name',
  attributeType: 'Attribute type',
  attributeOptions: 'Options (comma-separated)',
  attributeTypeEnum: 'Enum',
  attributeTypeRange: 'Range',
  attributeTypeBoolean: 'Boolean',
  manageAttributes: 'Attributes',
  editCategoryAttribute: 'Edit attribute',
  saveCategoryAttribute: 'Save attribute',
  cancelEditAttribute: 'Cancel',
  couldNotReorderAttributes: 'Could not save attribute order.',
  couldNotSaveAttribute: 'Could not save attribute.',
  couldNotDeleteAttribute: 'Could not delete attribute.',
  deleteCategoryAttribute: 'Delete attribute',
  reassignProducts: 'Reassign products',
  reassignProductsTitle: 'Bulk reassign products',
  reassignProductsBody: 'Move all products from one category to another.',
  reassignFrom: 'From category',
  reassignTo: 'To category',
  reassignConfirm: 'Reassign',
  selectCategory: 'Select category',
  archiveCategory: 'Archive',
  reactivateCategory: 'Reactivate',
  confirmArchiveCategoryTitle: 'Archive this category?',
  confirmArchiveCategoryBody:
    'Archive "{name}"? It will leave navigation and filters. {count} product(s) stay visible via direct links.',
  confirmReactivateCategoryTitle: 'Reactivate this category?',
  confirmReactivateCategoryBody: 'Restore "{name}" to active navigation and filters?',
  categoryReorderHint: 'Drag rows to change display order.',
  couldNotReorderCategories: 'Could not save category order.',
  couldNotReassignProducts: 'Could not reassign products.',
  productsReassigned: 'Reassigned {count} product(s).',
  name: 'Name',
  imageUrl: 'Image',
  parentId: 'Parent',
  parentName: 'Parent',
  displayOrder: 'Order',
  seoTitle: 'SEO title',
  seoDescription: 'SEO description',
  shopCategory: 'Shop {name}',
  shopCategoryDescription: 'Browse {name} on {site}.',
  filteredCategoryNoindex: 'Filtered category results',
  categoryBreadcrumbHome: 'Home',
  breadcrumb: 'Breadcrumb',
  clearFacetFilters: 'Clear filters',
  facetResults: '{count} results',
  facetDisabledHint: 'No products match with current filters',
  allCategories: 'All categories',
  categoryPlpEmpty: 'No products in this category yet.',
  categoryPlpEmptyEyebrow: 'Empty category',
  categoryPlpEmptyHeading: 'No products in "{name}"',
  categoryPlpEmptyBody:
    'This category has no items listed right now. Try a parent category, or browse the full catalog.',
  categoryPlpNoFilterMatchesEyebrow: 'No matches',
  categoryPlpNoFilterMatchesHeading: 'Nothing matches in "{name}"',
  categoryPlpNoFilterMatchesBody:
    'No products in this category match your current filters. Clear filters to see everything available here.',
  browseParentCategory: 'Back to {name}',
  categoryNotFound: 'Category not found.',
  pageNotFound: 'Page not found',
  pageNotFoundBody: "The page you're looking for doesn't exist or has been moved.",
  goToHomepage: 'Go to homepage',
  dragToReorder: 'Drag to reorder',
  featured: 'Featured',
  shopNewArrivals: 'Shop new arrivals',
  filters: 'Filters',
  refine: 'Refine',
  clearRating: 'Clear rating',
  showResults: 'Show results',
  resetFilters: 'Reset filters',
  nothingInThisRange: 'Nothing in this range',
  nothingInThisRangeHint: 'No pieces match these filters. Reset them to browse the full collection.',
  noSearchResultsHeading: 'No results',
  noSearchResultsHint: 'Nothing matched “{search}”. Try another term or browse the full collection.',
  noCategoryProductsHeading: 'No products here yet',
  noCategoryProductsHintNamed:
    '“{name}” doesn’t have any products right now. Browse the full collection instead.',
  noCategoryProductsHint:
    'This category doesn’t have any products right now. Browse the full collection instead.',
  noVendorProductsHeading: 'No products from this vendor',
  noVendorProductsHint: 'This vendor has nothing listed right now. Browse the full collection instead.',
  noProductsYetHeading: 'No products yet',
  noProductsYetHint: 'The collection is empty for now. Check back soon for new pieces.',
  browseAllProducts: 'Browse all products',
  sort: 'Sort',
  compare: 'Compare',
  sortTrending: 'Trending',
  sortNewest: 'Newest',
  sortPriceLowHigh: 'Price: Low to High',
  sortPriceHighLow: 'Price: High to Low',
  sortTopRated: 'Top Rated',
  productCountSingular: '{count} product',
  productCountPlural: '{count} products',
  updatingEllipsis: 'Updating…',
  browseCollection: 'Browse collection',
  starsAndUp: '{count}+ stars',
  // Platform settings
  platformSettings: 'Platform Settings',
  platformSettingsHint:
    'Manage commission, returns, shipping thresholds, support contact, and moderation defaults.',
  settingsCommerce: 'Commerce',
  settingsCommerceHint: 'Commission and product moderation defaults.',
  settingsFulfillment: 'Fulfillment',
  settingsFulfillmentHint: 'Returns, free shipping, and payout timing.',
  settingsSupport: 'Support',
  settingsSupportHint: 'Customer-facing contact details and helpdesk windows.',
  ticketReopenWindowDays: 'Ticket reopen window',
  ticketReopenWindowDaysHint:
    'Days after resolve during which a customer may reopen a support ticket.',
  bugVerifyWindowDays: 'Bug auto-verify window',
  bugVerifyWindowDaysHint:
    'Days after a bug is marked fixed before it auto-transitions to verified.',
  bugCloseWindowDays: 'Bug auto-close window',
  bugCloseWindowDaysHint:
    'Days after a bug is verified before it auto-transitions to closed.',
  defaultCommissionRate: 'Default commission rate',
  tcsRatePercent: 'Marketplace TCS rate (%)',
  tcsRateHint: 'Tax collected at source on taxable marketplace sales. Set 0 to disable.',
  tdsRatePercent: 'TDS rate at payout (%)',
  tdsRateHint: 'TDS under section 194-O deducted when settling vendor payouts. Set 0 to disable.',
  reports: 'Reports',
  reportsHubHint: 'Filtered, paginated tabular reports with Excel export from frozen ledger data.',
  reportFilters: 'Filters',
  reportFiltersHint: 'Choose a report and date range, then load or export results.',
  reportSelect: 'Report',
  reportCategory: 'Category',
  reportStatus: 'Status',
  reportVendor: 'Vendor',
  exportExcel: 'Export Excel',
  reportAsyncQueued: 'Large export queued — waiting for file…',
  reportAsyncReady: 'Export ready — downloading…',
  reportAsyncFailed: 'Export failed. Try again with a narrower date range.',
  reportLoadError: 'Could not load report.',
  reportCatalogError: 'Could not load report catalog.',
  uuidPlaceholder: 'UUID',
  refundsToCustomer: 'Refunds to customer',
  emptyCell: '—',
  approvedCount: 'Approved',
  pendingCount: 'Pending',
  rejectedCount: 'Rejected',
  // Report column headers not already covered above (must match BE REPORT_COLUMN_LABELS keys)
  groupType: 'Group',
  state: 'State',
  period: 'Period',
  taxableValue: 'Taxable Value',
  tcsCgst: 'TCS CGST',
  tcsSgst: 'TCS SGST',
  tcsIgst: 'TCS IGST',
  tcsTotal: 'TCS Total',
  section: 'Section',
  grossTaxable: 'Gross Taxable',
  tdsAmount: 'TDS Amount',
  qty: 'Quantity',
  taxable: 'Taxable',
  cgst: 'CGST',
  sgst: 'SGST',
  igst: 'IGST',
  taxTotal: 'Tax Total',
  platformCommission: 'Platform Commission',
  accountedTotal: 'Accounted Total',
  difference: 'Difference',
  type: 'Type',
  noteNumber: 'Note Number',
  orderId: 'Order ID',
  taxAmount: 'Tax Amount',
  issuedAt: 'Issued At',
  payoutAmount: 'Payout Amount',
  payoutPending: 'Payout Pending',
  payoutPaid: 'Payout Paid',
  payoutStatus: 'Payout Status',
  categoryId: 'Category ID',
  commission: 'Commission',
  discountAmount: 'Discount Amount',
  gmv: 'GMV',
  actorId: 'Actor ID',
  entityId: 'Entity ID',
  metadata: 'Metadata',
  subOrderId: 'Sub-order ID',
  deliveredAt: 'Delivered At',
  hoursToDeliver: 'Hours to Deliver',
  level: 'Level',
  cancelledAt: 'Cancelled At',
  orderItemId: 'Order Item ID',
  refundStatus: 'Refund Status',
  turnaroundHours: 'Turnaround Hours',
  resolvedAt: 'Resolved At',
  productId: 'Product ID',
  revenue: 'Revenue',
  submittedAt: 'Submitted At',
  decidedAt: 'Decided At',
  approvedById: 'Approved By',
  reviewCount: 'Reviews',
  avgRating: 'Avg Rating',
  netPayout: 'Net Payout',
  invoiceId: 'Invoice',
  payoutId: 'Payout ID',
  paidAt: 'Paid At',
  razorpayPayoutId: 'Razorpay Payout ID',
  tcsAmount: 'TCS Amount',
  sku: 'SKU',
  stock: 'Stock',
  lowStockAt: 'Low Stock At',
  isLowStock: 'Low Stock',
  valuation: 'Valuation',
  updatedAt: 'Updated At',
  orderStatus: 'Order Status',
  subOrderStatus: 'Sub-order Status',
  quantity: 'Qty',
  paymentStatus: 'Payment Status',
  subOrderCount: 'Sub-orders',
  variantId: 'Variant ID',
  downloadTaxInvoice: 'Download tax invoice',
  exportOrderHistory: 'Export order history',
  reportGstTcsSummary: 'GST TCS summary (GSTR-8)',
  reportTds194oSummary: 'Income tax TDS (194-O) summary',
  reportHsnSalesSummary: 'HSN-wise sales summary',
  reportStateTaxCollection: 'State-wise tax collection',
  reportReconciliation: 'Reconciliation report',
  reportCreditDebitNoteRegister: 'Credit / debit note register',
  reportVendorSettlement: 'Vendor settlement report',
  reportCommissionRevenue: 'Commission revenue report',
  reportCouponDiscountCost: 'Coupon & discount cost',
  reportGmvSales: 'GMV & sales report',
  reportAuditLog: 'Audit log report',
  reportOrderSla: 'Order status / SLA',
  reportCancellations: 'Cancellation report',
  reportRefundReturn: 'Refund / return report',
  reportProductPerformance: 'Product performance',
  reportCategoryPerformance: 'Category performance',
  reportProductApprovalTat: 'Product approval turnaround',
  reportReviewRatingSummary: 'Review / rating summary',
  reportVendorSales: 'Sales report',
  reportVendorGstSales: 'GST-ready sales summary',
  reportVendorTcsCredit: 'TCS credit statement',
  reportVendorTdsCertificate: 'TDS certificate report',
  reportVendorPayoutStatement: 'Settlement / payout statement',
  reportVendorCommissionDeducted: 'Commission deducted',
  reportVendorDiscountCost: 'Discount cost',
  reportVendorReturnRefund: 'Return / refund report',
  reportVendorInventory: 'Inventory / stock report',
  reportVendorFulfillmentSla: 'Order fulfillment (SLA)',
  reportStaffOrders: 'Order / sub-order report',
  reportStaffInventory: 'Inventory report',
  reportCustomerOrderHistory: 'Order history export',
  settlementReports: 'Settlement reports',
  reportDateFrom: 'From',
  reportDateTo: 'To',
  reportLoad: 'Load report',
  exportCsv: 'Export CSV',
  exportPdf: 'Export PDF',
  platformGmv: 'GMV',
  customerPayments: 'Customer payments',
  commissionEarned: 'Commission earned',
  taxCollected: 'Tax collected',
  tcsCollected: 'TCS collected',
  shippingCollected: 'Shipping collected',
  discountAbsorbedPlatform: 'Discount absorbed (platform)',
  discountAbsorbedVendor: 'Discount absorbed (vendor)',
  vendorNetPayouts: 'Vendor net payouts',
  reconciliation: 'Reconciliation',
  reconciliationBalanced: 'Balanced',
  reconciliationMismatch: 'Mismatch — totals do not reconcile',
  reconciliationDifference: 'Difference',
  vendorSettlements: 'Vendor settlements',
  grossSales: 'Gross sales',
  discountsAbsorbed: 'Discounts absorbed',
  commissionCharged: 'Commission charged',
  pendingNet: 'Pending net',
  settledNet: 'Settled net',
  ownCouponDiscounts: 'Own coupon discounts',
  platformCouponDiscounts: 'Platform coupon discounts on my items',
  upcomingPayout: 'Upcoming payout',
  historicalPayout: 'Historical payout',
  noReportData: 'No report data for this range.',
  couldNotLoadReport: 'Could not load report.',
  autoApproveProducts: 'Auto-approve products',
  autoApproveEnabled: 'Enabled (auto-approve)',
  autoApproveDisabled: 'Disabled (moderated)',
  defaultReturnWindow: 'Default return window',
  freeShippingThreshold: 'Free shipping threshold',
  returnShippingFee: 'Return shipping fee',
  returnShippingFeeHint:
    'Deducted from customer refunds when the return reason does not refund original shipping (for example no longer needed).',
  vendorShopSettings: 'Shop settings',
  vendorShopSettingsHint:
    'Configure how your shop appears and how returns affect your storefront. Leave return shipping fee blank to use the platform default.',
  vendorLogoUpload: 'Shop logo',
  vendorBannerUpload: 'Shop banner',
  vendorReturnShippingFeeClear: 'Use platform default',
  couldNotLoadVendorShopSettings: 'Could not load shop settings.',
  couldNotSaveVendorShopSettings: 'Could not save shop settings.',
  vendorShopSettingsSaved: 'Shop settings saved.',
  payoutCycle: 'Payout cycle',
  payoutCycleWeekly: 'Weekly',
  payoutCycleBiweekly: 'Bi-weekly',
  payoutCycleMonthly: 'Monthly',
  payoutCycleWeeklyLegacy: 'Weekly (legacy)',
  supportEmail: 'Support email',
  supportHours: 'Support hours',
  saveSettings: 'Save settings',
  settingsSaved: 'Settings saved.',
  couldNotSaveSettings: 'Could not save settings.',
  couldNotLoadSettings: 'Could not load platform settings from the server.',
  settingsUnavailable: 'Settings unavailable.',
  loadingPlatformSettings: 'Loading platform settings…',
  addTaxRule: 'Add tax rule',
  enterGstPercentage: 'Enter a GST percentage to continue.',
  gstPercentage: 'GST %',
  hsnOptional: 'HSN (optional)',
  addShippingZone: 'Add shipping zone',
  enterZoneName: 'Enter a zone name to continue.',
  zoneName: 'Zone name',
  decreaseValue: 'Decrease value',
  increaseValue: 'Increase value',
  pickDateTime: 'Pick date & time',
  pickDate: 'Pick date',
  previousMonth: 'Previous month',
  nextMonth: 'Next month',
  hour: 'Hour',
  minute: 'Minute',
  done: 'Done',
  createCoupon: 'Create coupon',
  couponValue: 'Value',
  maxDiscountCap: 'Max discount cap',
  minOrderValue: 'Min order value',
  startDate: 'Start date',
  endDate: 'End date',
  couponTypePercentage: 'Percentage',
  couponTypeFlat: 'Flat amount',
  couponTypeFreeShipping: 'Free shipping',
  couponTypeBogo: 'Buy one get one',
  couponTypeTiered: 'Tiered',
  couponTypeCashback: 'Cashback',
  couponTypeBundle: 'Bundle',
  daysShort: 'days',
  completeCouponFields: 'Add a code, type, start date, and end date to create a coupon.',
  fieldRequired: 'Required',
  enterCouponCode: 'Enter a coupon code.',
  enterCouponValue: 'Enter a value for this coupon type.',
  enterCouponStartDate: 'Choose a start date and time.',
  enterCouponEndDate: 'Choose an end date and time after the start.',
  couponCreateHint: 'Complete all required fields to create this coupon.',
  adminPanel: 'Admin Panel',
  brandName: 'Marketplace',
  menu: 'Menu',
  closeMenu: 'Close menu',
  home: 'Home',
  search: 'Search',
  cart: 'Cart',
  wishlist: 'Wishlist',
  myWishlist: 'My Wishlist',
  moveToCart: 'Move to cart',
  profile: 'Profile',
  account: 'Account',
  themeLight: 'Light',
  themeDark: 'Dark',
  openAccountMenu: 'Open account menu',
  browseCategories: 'Browse categories',
  remove: 'Remove',
  removeNamed: 'Remove {name}',
  removeNamedFromWishlist: 'Remove {name} from wishlist',
  addAddress: 'Add address',
  addressDefault: 'Default',
  setDefaultShort: 'Set default',
  details: 'Details',
  view: 'View',
  clear: 'Clear',
  compareNow: 'Compare now',
  backToTop: 'Back to top',
  openChatSupport: 'Open chat support',
  chatNeedHelpTitle: 'Need help?',
  chatSupportMessage: 'Chat support is available for orders, returns, and account questions.',
  cookieBannerMessage:
    'This site uses cookies to improve your experience. By continuing, you agree to our use of cookies.',
  manageCookiePreferences: 'Manage preferences',
  acceptCookies: 'Accept',
  dismiss: 'Dismiss',
  shareThisProduct: 'Share this product',
  share: 'Share',
  copyLink: 'Copy link',
  linkCopied: 'Link copied',
  previousSlide: 'Previous slide',
  nextSlide: 'Next slide',
  productImageView: '{name} - view {index}',
  decreaseQuantity: 'Decrease quantity',
  increaseQuantity: 'Increase quantity',
  editQuantity: 'Quantity {value}. Click to edit.',
  quantityField: 'Quantity',
  minimumQuantityHint: 'Minimum quantity is {min}.',
  maximumQuantityHint: 'Maximum quantity is {max}.',
  onlyOneInStock: 'Only 1 available in stock.',
  browse: 'Browse',
  viewAll: 'View all',
  shopByCategory: 'Shop by category',
  noCategoriesYet: 'No categories yet',
  browseProducts: 'Browse products',
  quickAdd: 'Quick add',
  homeYourBrowsing: 'Your browsing',
  homeRecentlyViewed: 'Recently viewed',
  homeCuratedMakers: 'Curated makers',
  homeVendorSpotlight: 'Vendor spotlight',
  homeKnownFor: 'Known for {product}',
  homeBrowseAll: 'Browse all',
  categoryDepartmentCount: '{count} departments',
  categoryExploreCollection: 'Explore the full collection',
  categoryChildCountSingular: '{count} subcategory',
  categoryChildCountPlural: '{count} subcategories',
  digDeeper: 'Dig deeper',
  subcategories: 'Subcategories',
  shopInCategory: 'Browse',
  shopAll: 'Shop all',
  categoriesIndexHint:
    'Explore every collection on {site} — from makers and studios across the country.',
  categoryImageUnavailable: '{name} image not available',
  minPricePlaceholder: 'Min',
  maxPricePlaceholder: 'Max',
  minimumPrice: 'Minimum price',
  maximumPrice: 'Maximum price',
  help: 'Help',
  productNamePlaceholder: 'Product name',
  pricePlaceholder: 'Price',
  shortDescription: 'Short description',
  creatingEllipsis: 'Creating…',
  createProduct: 'Create product',
  moreCategoriesCount: '+{count} more',
  privacyPreferences: 'Preferences',
  privacyAndData: 'Privacy & data',
  appearance: 'Appearance',
  appearanceHintCustomer: 'Light or dark for the storefront. Saved on this device.',
  appearanceHintWorkspace: 'Light or dark for the admin and vendor consoles. Saved on this device.',
  downloadMyData: 'Download my data',
  downloadMyDataHintCustomer:
    'Export a JSON copy of your profile, addresses, orders, reviews, returns, and wishlist.',
  download: 'Download',
  signOut: 'Sign out',
  signOutHint: 'End this session on this device.',
  signOutConfirmTitle: 'Sign out?',
  signOutConfirmBody: "You'll need to sign in again to access your account on this device.",
  dangerZone: 'Danger zone',
  deleteAccount: 'Delete account',
  deleteAccountHintCustomer:
    'Permanently deactivate your account. This cannot be undone from the storefront.',
  deleteAccountHintWorkspace: 'Permanently deactivate your account. This cannot be undone.',
  deleteAccountBody: "Your profile will be deactivated and you'll be signed out immediately.",
  deleteAccountConfirmTitle: 'Delete your account?',
  deleteAccountConfirmBody: 'Type DELETE to confirm. Your profile will be deactivated and you’ll be signed out.',
  confirmation: 'Confirmation',
  couldNotExportAccount: 'Could not export account data.',
  couldNotDeleteAccount: 'Could not delete account.',
  phoneOptionalDelivery: 'Optional — used for delivery updates.',
  phoneOptionalContact: 'Optional — used for account recovery contact.',
  personalInfoFooterCustomer:
    'Keep your name, phone, and email current for orders and account recovery.',
  personalInfoFooterWorkspace:
    'Keep your name, phone, and email current for account recovery.',
  personalInfoSectionTitle: 'Personal information',
  personalInfoSectionHint: 'Update how we address you and how we can reach you.',
  personalInfoEyebrow: 'Identity',
  personalInfoProfileEyebrow: 'Profile',
  personalInfoProfileHint: 'A quick view of the details currently tied to your account.',
  personalInfoAccountHolder: 'Account holder',
  personalInfoEmailStatus: 'Email status',
  personalInfoNoPhone: 'No phone saved yet',
  personalInfoVerified: 'Verified',
  personalInfoUnverified: 'Unverified',
  personalInfoSaved: 'Profile saved.',
  fullName: 'Full name',
  phone: 'Phone',
  phonePlaceholder: '+91…',
  nameRequired: 'Name is required',
  saveChanges: 'Save changes',
  couldNotSaveProfile: 'Could not save profile.',
  couldNotLoadProfile: 'Could not load your profile. Please try again.',
  newAddress: 'New address',
  editAddress: 'Edit address',
  addressFormHint: 'All fields marked required must be filled.',
  addressLine1: 'Address line 1',
  addressLine2Optional: 'Address line 2 (optional)',
  addressLine1Placeholder: 'House no., street, landmark',
  addressLine2Placeholder: 'Apartment, suite, floor',
  addressCity: 'City',
  addressState: 'State',
  addressPincode: 'Pincode',
  addressCountry: 'Country',
  addressSetDefault: 'Set as default address',
  addressRequiredFields: 'Please fill all required fields.',
  enterAddressLine1: 'Enter address line 1 to continue.',
  enterAddressCity: 'Enter a city to continue.',
  enterAddressState: 'Enter a state to continue.',
  enterAddressPincode: 'Enter a pincode to continue.',
  saveAddress: 'Save address',
  couldNotSaveAddress: 'Could not save address.',
  addressFormSection: 'Address details',
  addressFormSectionHint: 'Delivery location used at checkout.',
  defaultCountry: 'India',
  helpContactSection: 'Contact details',
  helpContactSectionHint: 'Tell us how to reach you and what you need help with.',
  helpContactMessageSection: 'Message',
  helpContactMessageSectionHint: 'Include enough detail for us to investigate.',
  reviewFormSection: 'Your review',
  reviewFormSectionHint: 'Rating and comments for this product.',
  reviewingProduct: 'Reviewing: {name}',
  reviewTitleOptional: 'Title (optional)',
  reviewTitlePlaceholder: 'Summarize your experience',
  reviewBody: 'Review',
  reviewBodyPlaceholder: 'What did you think?',
  selectReviewRating: 'Select a star rating to continue.',
  enterReviewBody: 'Enter a review of at least 10 characters.',
  enterFullName: 'Enter your full name to continue.',
  enterProductName: 'Enter a product name to continue.',
  enterProductPrice: 'Enter a price to continue.',
  selectProductCategory: 'Select a category to continue.',
  enterBusinessName: 'Enter a business name to continue.',
  selectVendorEntityType: 'Select an entity type to continue.',
  selectVendorCategories: 'Select at least one category to continue.',
  submitReview: 'Submit review',
  returnRequestFormSection: 'Return details',
  returnRequestFormSectionHint: 'Reason, notes, and optional photos.',
  attributeFormSection: 'Attribute',
  attributeFormSectionHint: 'Name, type, and options for category filters.',
  bulkCouponMetaSection: 'Batch settings',
  bulkCouponMetaSectionHint: 'Name, count, and code prefix for generated coupons.',
  emailFixedStorefront: 'Email addresses are fixed on this account and cannot be changed from the storefront.',
  emailFixedWorkspace: 'Email addresses are fixed on this account and cannot be changed here.',
  accountSettingsHintCustomer:
    'Manage your profile, security, addresses, and preferences — quietly, clearly.',
  accountSettingsHintWorkspace:
    'Manage your profile, security, and preferences — quietly, clearly.',
  privacyAndDataHintCustomer:
    'Control appearance on this device, export your data, or end your session.',
  privacyAndDataHintWorkspace: 'Control appearance on this device or end your session.',
  privacySectionDescCustomer: 'Data and account deletion',
  privacySectionDescWorkspace: 'Appearance, sign out, and account deletion',

  // Wallet
  wallet: 'Wallet',
  walletBalance: 'Wallet balance',
  walletAmountToApply: 'Amount to apply from wallet',
  walletUseAll: 'Use full balance',
  walletRemainderDue: 'Amount due today: {amount}',
  walletFullyCoversOrder: 'Your wallet covers this order — no online payment needed.',
  walletNotAvailableWithCod: 'Wallet balance cannot be used with cash on delivery.',
  walletPageDescription: 'Credits from returns and cashback, and debits from checkout.',
  walletTransactionHistory: 'Transaction history',
  walletNoTransactions: 'No wallet activity yet.',
  walletCredit: 'Credit',
  walletDebit: 'Debit',
  walletTransactionSourceCodRefund: 'COD return refund',
  walletTransactionSourceWalletRefund: 'Wallet refund',
  walletTransactionSourceCashback: 'Cashback',
  walletTransactionSourceCheckout: 'Checkout payment',
  walletTransactionSourceClawback: 'Cashback recovery',
  walletTransactionSourceOther: 'Adjustment',
  walletBalanceAfter: 'Balance after {amount}',

  // Payment split & cashback
  paymentSplitHeading: 'Payment',
  paymentSplitWallet: '{amount} from wallet',
  paymentSplitRazorpay: '{amount} via Razorpay',
  paymentSplitCod: 'Cash on delivery',
  cashbackPendingAfterDelivery: 'Cashback pending — credited to wallet after delivery',
  cashbackCreditedToWallet: '{amount} cashback credited to your wallet',
  cashbackPayNowMessage: 'Pay {payNow} now, {cashback} cashback after delivery',
  couponCashbackApplied: 'Cashback offer: {code}',

  // Checkout payment methods
  paymentMethodRazorpay: 'Card / UPI / Netbanking',
  paymentMethodRazorpayDesc: 'Pay securely via Razorpay',
  paymentMethodCod: 'Cash on Delivery',
  paymentMethodCodDesc: 'Pay when your order arrives',
  selectPaymentMethodToContinue: 'Select a payment method to continue.',
  backToShipping: 'Back to shipping',
  continueToReview: 'Continue to review',
  walletAppliedAtCheckout: 'Wallet applied',
  amountDueToday: 'Due today',

  // Return timelines
  returnTimelineRefundTrack: 'Refund',
  returnTimelineLogisticsTrack: 'Return pickup',
  returnRefundStatusNone: 'Not started',
  returnRefundStatusPending: 'Processing',
  returnRefundStatusInitiated: 'Refund initiated',
  returnRefundStatusCompleted: 'Refunded',
  returnRefundStatusFailed: 'Refund failed',
  returnLogisticsRequested: 'Return requested',
  returnLogisticsApproved: 'Approved',
  returnLogisticsPickupScheduled: 'Pickup scheduled',
  returnLogisticsReceived: 'Item received',
  returnLogisticsClosed: 'Closed',
  returnLogisticsRejected: 'Rejected',
  returnSchedulePickup: 'Schedule pickup',
  returnMarkReceived: 'Mark received',
  returnClose: 'Close return',
  confirmSchedulePickupTitle: 'Schedule reverse pickup?',
  confirmSchedulePickupBody: 'Schedule pickup for return "{name}"?',
  confirmMarkReceivedTitle: 'Mark return as received?',
  confirmMarkReceivedBody: 'Confirm warehouse receipt for return "{name}"?',
  confirmCloseReturnTitle: 'Close this return?',
  confirmCloseReturnBody: 'Close return "{name}" after receipt?',
  returnsPageTitle: 'Returns',
  returnsPageDescription:
    'Track return requests for delivered items. Start a return from an order detail page when an item qualifies.',
  noReturnsYet: 'No returns yet',
  noReturnsYetMessage: 'When you request a return on a delivered order, it will show up here.',
  viewOrders: 'View orders',
  couldNotLoadReturns: 'Could not load returns.',
  orderItemFallback: 'Order item',
  requestReturn: 'Request return',
  submitReturn: 'Submit return',
  cancelReturn: 'Cancel',
  returnRequestedSuccess: 'Return requested.',
  couldNotSubmitReturn: 'Could not submit return request.',
  requestReturnTitle: 'Request a return',
  requestReturnDescription: 'Tell us why you want to return this item.',
  requestReturnDescriptionItem: 'Return "{product}". We\'ll review and update you by email.',
  returnReasonLabel: 'Reason',
  returnDetailsLabel: 'Details',
  returnDetailsPlaceholder: 'Briefly describe the issue',

  // Admin wallet reports
  reportWalletLiability: 'Wallet liability',
  reportCashbackWriteOff: 'Cashback write-offs',
  reportTotalLiability: 'Total outstanding balance',
  reportWalletCustomerCount: 'Customers with balance',
  reportRecoveredTotal: 'Recovered',
  reportWrittenOffTotal: 'Written off',
  reportBornBy: 'Born by',
  reportBornByAll: 'All',
  reportBornByPlatform: 'Platform',
  reportBornByVendor: 'Vendor',
  reportUserId: 'User ID',
  reportBalance: 'Balance',
  reportAsOf: 'As of',
  reportOriginalClawback: 'Original clawback',
  reportRecoveredAmount: 'Recovered amount',
  reportWrittenOffAmount: 'Written off amount',

  // Support tickets
  supportTickets: 'Support tickets',
  supportTicket: 'Support ticket',
  mySupportTickets: 'My support tickets',
  supportTicketsPageDescription:
    'Open and track helpdesk conversations about orders, payments, and sellers.',
  supportTicketsEmpty: 'No support tickets yet',
  supportTicketsEmptyMessage: 'Create a ticket when you need help with an order or account issue.',
  createSupportTicket: 'Create ticket',
  newSupportTicket: 'New support ticket',
  newSupportTicketDescription: 'Describe the issue. Attach screenshots or a short video if helpful.',
  ticketSubject: 'Subject',
  ticketSubjectPlaceholder: 'Short summary of the issue',
  ticketDescription: 'Description',
  ticketDescriptionPlaceholder: 'What happened, what you expected, and any error messages.',
  ticketCategory: 'Category',
  ticketRelatedOrderId: 'Related order ID (optional)',
  ticketRelatedVendorId: 'Related vendor ID (optional)',
  ticketRelatedVendor: 'Related vendor',
  ticketRelatedVendorHint:
    'Required when the issue is about a specific seller, or when your order has multiple sellers.',
  ticketSelectVendor: 'Select a vendor',
  ticketVendorRequired: 'Select the related vendor',
  ticketSearchVendors: 'Search vendors…',
  ticketPriority: 'Priority',
  ticketAttachments: 'Attachments',
  ticketSubmit: 'Submit ticket',
  ticketCreatedSuccess: 'Ticket created.',
  ticketCouldNotCreate: 'Could not create ticket.',
  ticketCouldNotLoad: 'Could not load tickets.',
  ticketCouldNotLoadDetail: 'Could not load this ticket.',
  ticketReplyPlaceholder: 'Write a reply…',
  ticketSendReply: 'Send reply',
  ticketCouldNotReply: 'Could not send reply.',
  ticketCouldNotResolve: 'Could not resolve ticket.',
  ticketCouldNotReopen: 'Could not reopen ticket.',
  ticketCouldNotClose: 'Could not close ticket.',
  ticketCouldNotReassign: 'Could not reassign ticket.',
  ticketCouldNotUpdatePriority: 'Could not update priority.',
  ticketCouldNotEscalate: 'Could not escalate ticket.',
  ticketCouldNotRate: 'Could not submit rating.',
  ticketReopenWindowExpired: 'The reopen window for this ticket has ended.',
  ticketResolve: 'Mark resolved',
  ticketReopen: 'Reopen',
  ticketClose: 'Close ticket',
  ticketReassign: 'Reassign',
  ticketAssignee: 'Assignee',
  ticketAssigneePlaceholder: 'Select an assignee',
  ticketAssigneeNone: 'Unassigned',
  ticketAssigneesEmpty: 'No eligible assignees found.',
  ticketAssignedToId: 'Assignee',
  ticketRate: 'Rate this resolution',
  ticketRateSubmit: 'Submit rating',
  ticketRatedThanks: 'Thanks for your feedback.',
  ticketLoadEarlier: 'Load earlier messages',
  ticketNoMessages: 'No messages yet.',
  ticketLatestPreview: 'Latest',
  ticketNumberLabel: 'Ticket {number}',
  ticketNumber: 'Ticket #',
  ticketCustomer: 'Customer',
  ticketVendor: 'Vendor',
  ticketView: 'View',
  ticketConversation: 'Conversation',
  ticketOriginalRequest: 'Original request',
  ticketAboutTicket: 'About this ticket',
  ticketBackToList: 'Back to tickets',
  ticketShowDetails: 'Ticket details',
  ticketHideDetails: 'Hide details',
  ticketClosedNotice: 'This ticket is closed. You can no longer send replies.',
  ticketMustReopenToReplyCustomer: 'This ticket is resolved. Reopen it to send another reply.',
  ticketMustReopenToReplyStaff: 'This ticket is resolved. The customer must reopen it before further replies.',
  ticketUnread: 'Unread',
  ticketHasUnread: 'New activity',
  ticketRateHint: 'How was the resolution? Your rating helps us improve support.',
  ticketUpdatePriority: 'Update priority',
  ticketPrioritySaved: 'Priority updated.',
  ticketEscalate: 'Escalate to urgent',
  ticketMessageYou: 'You',
  ticketMessageSupport: 'Support',
  ticketMessageCustomer: 'Customer',
  ticketAvatarInitialsFallback: '?',
  ticketComposerHint: 'Replies are visible to everyone on this ticket.',
  ticketBasicsSection: 'Ticket details',
  ticketBasicsSectionHint: 'Subject and category for routing.',
  ticketDescriptionSection: 'Description',
  ticketDescriptionSectionHint: 'Include enough detail for support to investigate.',
  ticketAttachmentsSection: 'Attachments',
  ticketAttachmentsSectionHint: 'Up to 5 images and 1 short video.',
  ticketOrderSection: 'Related order',
  ticketOrderSectionHint: 'Optionally link one of your orders (any status).',
  ticketSelectOrder: 'Select an order',
  ticketNoOrder: 'No related order',
  ticketNoOrdersYet: 'You have no orders to link yet.',
  ticketSubjectTooLong: 'Subject must be {max} characters or fewer.',
  ticketDescriptionTooLong: 'Description must be {max} characters or fewer.',
  ticketReplyTooLong: 'Reply must be {max} characters or fewer.',
  ticketSubjectRequired: 'Subject is required',
  ticketDescriptionRequired: 'Description is required',
  enterTicketSubject: 'Enter a subject to continue.',
  enterTicketDescription: 'Enter a description to continue.',
  selectTicketVendor: 'Select the related vendor to continue.',
  ticketCategoryRequired: 'Category is required',
  ticketCharCounter: '{count} / {max}',
  attachmentCounter: '{count} / {max} images · {videoCount} / {videoMax} video',
  ticketStatusOpen: 'Open',
  ticketStatusInProgress: 'In progress',
  ticketStatusResolved: 'Resolved',
  ticketStatusClosed: 'Closed',
  ticketStatusReopened: 'Reopened',
  ticketCategoryOrder: 'Order',
  ticketCategoryProduct: 'Product',
  ticketCategoryPayment: 'Payment',
  ticketCategoryVendor: 'Vendor',
  ticketCategoryOther: 'Other',
  ticketPriorityLow: 'Low',
  ticketPriorityMedium: 'Medium',
  ticketPriorityHigh: 'High',
  ticketPriorityUrgent: 'Urgent',
  ticketFilterAllStatuses: 'All statuses',
  ticketFilterAllPriorities: 'All priorities',
  ticketFilterAllCategories: 'All categories',
  ticketFilterVendorId: 'Vendor',
  ticketFilterAllVendors: 'All vendors',
  ticketAdminQueueDescription: 'Platform helpdesk queue with filters and assignment.',
  ticketVendorQueueDescription: 'Customer tickets related to your shop.',
  ticketSignInRequired: 'Sign in to view and manage support tickets.',
  ticketAttachmentLimit: 'You can attach up to 5 images and 1 video.',
  ticketVideoTooLong: 'Video must be {seconds} seconds or less.',
  ticketVideoTooLarge: 'Video must be under {mb}MB.',
  ticketCompressFailed: 'Could not compress video. Try a shorter or smaller file.',
  ticketCompressingVideo: 'Compressing video…',
  bugVideoTooLong: 'Screen recording must be {seconds} seconds or less.',
  bugVideoTooLarge: 'Screen recording must be under {mb}MB.',
  bugCompressFailed: 'Could not compress the recording. Try a shorter or smaller file.',
  bugCompressingVideo: 'Compressing recording…',
  ticketRemoveAttachment: 'Remove',
  ticketAttachmentImage: 'Image',
  ticketAttachmentVideo: 'Video',
  loadMore: 'Load more',

  // Bug reports
  bugReports: 'Bug reports',
  bugReport: 'Bug report',
  myBugReports: 'My bug reports',
  reportABug: 'Report a bug',
  bugReportsPageDescription: 'Report product issues so we can investigate and fix them.',
  bugReportsEmpty: 'No bug reports yet',
  bugReportsEmptyMessage: 'Report a bug when something on the site does not work as expected.',
  newBugReport: 'Report a bug',
  newBugReportDescription:
    'Tell us what went wrong. We capture the page and device context automatically. Severity is optional.',
  bugBasicsSection: 'Bug details',
  bugBasicsSectionHint: 'A clear title helps triage.',
  bugSeverityOptional: 'Severity (optional)',
  bugSeverityHint: 'Leave blank if you are unsure — admins will triage.',
  bugSeverityNone: 'Not sure',
  bugDescriptionSection: 'What happened',
  bugDescriptionSectionHint: 'Describe the issue and optional steps to reproduce.',
  bugAttachmentsSection: 'Screenshots & recording',
  bugAttachmentsSectionHint: 'Up to 5 screenshots and 1 recording (max 2 minutes).',
  bugReportNumber: 'Report #',
  bugReporter: 'Reporter',
  bugView: 'View',
  bugNoCommentsYet: 'No internal notes yet. Add the first triage note below.',
  bugInternalCommentsHint: 'Visible to admins only — never shown to the reporter.',
  bugBackToList: 'Back to bug reports',
  bugProgress: 'Progress',
  bugProgressHint: 'We update this as your report moves through triage and fixes.',
  bugVerifyHint: 'Please confirm the issue is fixed on your side.',
  bugDetailsEyebrow: 'Bug report',
  bugAttachmentsHeading: 'Attachments',
  bugCurrentStatus: 'Current status',
  bugFiledOn: 'Filed on',
  bugTitle: 'Title',
  bugTitlePlaceholder: 'Short summary of the bug',
  bugDescription: 'Description',
  bugDescriptionPlaceholder: 'What you saw versus what you expected.',
  bugStepsToReproduce: 'Steps to reproduce (optional)',
  bugStepsPlaceholder: '1. Go to…\n2. Click…\n3. See error…',
  bugAttachments: 'Screenshots & recording',
  bugSubmit: 'Submit bug report',
  bugCreatedSuccess: 'Bug report submitted.',
  bugCouldNotCreate: 'Could not submit bug report.',
  bugCouldNotLoad: 'Could not load bug reports.',
  bugCouldNotLoadDetail: 'Could not load this bug report.',
  bugVerifyFixed: 'Confirm fixed',
  bugVerifiedThanks: 'Thanks — marked as verified.',
  bugAdminQueueDescription: 'Triage queue with severity, module, and reporter filters.',
  bugContextPanel: 'Reporter context',
  bugPageUrl: 'Page URL',
  bugBrowser: 'Browser',
  bugOs: 'OS',
  bugDevice: 'Device',
  bugAppVersion: 'App version',
  bugUserAgent: 'User agent',
  bugOccurredAt: 'Occurred at',
  bugReporterUserId: 'Reporter ID',
  bugReporterUserRole: 'Reporter role',
  bugReporterRoleLabel: 'Reporter type',
  bugInternalComments: 'Internal comments',
  bugCommentPlaceholder: 'Add an internal note…',
  bugAddComment: 'Add comment',
  bugCouldNotComment: 'Could not add comment.',
  bugCouldNotUpdate: 'Could not update bug report.',
  bugTriage: 'Triage',
  bugSeverity: 'Severity',
  bugAffectedModule: 'Affected module',
  bugAssignToId: 'Assignee',
  bugAssigneePlaceholder: 'Select an assignee',
  bugAssigneeNone: 'Unassigned',
  bugTriageSubmit: 'Save triage',
  bugSaveAssignment: 'Save assignment',
  bugAssignmentSaved: 'Assignment updated.',
  bugCouldNotSaveAssignment: 'Could not save assignment.',
  bugUpdateStatus: 'Update status',
  bugMarkDuplicate: 'Mark duplicate',
  bugDuplicateOfId: 'Duplicate of report # or ID',
  bugDuplicateOfHint: 'Paste a report number like BUG-000123, or the report UUID.',
  bugDuplicateOfPlaceholder: 'BUG-000123',
  bugDuplicateOf: 'This report is a duplicate of',
  bugTimeline: 'Status timeline',
  bugTimelineFiled: 'Filed',
  bugTimelineTriaged: 'Triaged',
  bugTimelineInProgress: 'In progress',
  bugTimelineResolved: 'Marked fixed',
  bugTimelineCurrent: 'Current status',
  bugTimelineAssignmentUpdated: 'Assignment updated',
  bugTimelineDuplicate: 'Marked duplicate',
  bugTimelineWontFix: 'Won’t fix',
  bugTimelineVerified: 'Verified',
  bugTimelineAutoVerified: 'Auto-verified',
  bugTimelineAutoClosed: 'Auto-closed',
  bugTimelineStatusChanged: 'Status updated',
  vendorBugReportsUtility: 'My bug reports',
  bugWontFix: 'Won’t fix',
  bugWontFixReason: 'Reason',
  bugWontFixSubmit: 'Confirm won’t fix',
  bugSignInRequired: 'Sign in to view and submit bug reports.',
  bugTitleRequired: 'Title is required',
  bugDescriptionRequired: 'Description is required',
  enterBugTitle: 'Enter a bug title to continue.',
  enterBugDescription: 'Enter a description of what went wrong.',
  bugTitleTooLong: 'Title must be {max} characters or fewer.',
  bugDescriptionTooLong: 'Description must be {max} characters or fewer.',
  bugStepsTooLong: 'Steps must be {max} characters or fewer.',
  bugCommentTooLong: 'Comment must be {max} characters or fewer.',
  bugWontFixReasonTooLong: 'Reason must be {max} characters or fewer.',
  bugAttachmentLimit: 'You can attach up to 5 screenshots and 1 screen recording.',
  bugAttachmentTypeMissing: 'One or more attachments are missing a type. Remove and re-upload them.',
  bugStatusNew: 'New',
  bugStatusTriaged: 'Triaged',
  bugStatusInProgress: 'In progress',
  bugStatusFixed: 'Fixed',
  bugStatusVerified: 'Verified',
  bugStatusClosed: 'Closed',
  bugStatusWontFix: 'Won’t fix',
  bugStatusDuplicate: 'Duplicate',
  bugSeverityLow: 'Low',
  bugSeverityMedium: 'Medium',
  bugSeverityHigh: 'High',
  bugSeverityCritical: 'Critical',
  bugModuleCatalog: 'Catalog',
  bugModuleCart: 'Cart',
  bugModuleCheckout: 'Checkout',
  bugModulePayments: 'Payments',
  bugModuleOrders: 'Orders',
  bugModuleVendorDashboard: 'Vendor dashboard',
  bugModuleAdminDashboard: 'Admin dashboard',
  bugModuleOther: 'Other',
  bugReporterRoleCustomer: 'Customer',
  bugReporterRoleVendor: 'Vendor',
  bugReporterRoleVendorStaff: 'Vendor staff',
  bugFilterAllSeverities: 'All severities',
  bugFilterAllModules: 'All modules',
  bugFilterAllReporterRoles: 'All reporter roles',
  bugFilterReporterRole: 'Reporter role',
  bugReportNumberLabel: 'Report {number}',
  helpQuickLinkTickets: 'My support tickets',
  helpQuickLinkTicketsDesc: 'Open and track authenticated helpdesk conversations.',
  helpQuickLinkBugs: 'Report a bug',
  helpQuickLinkBugsDesc: 'Tell us when something on the site breaks.',
  helpQuickLinkOrders: 'My orders',
  helpQuickLinkOrdersDesc: 'View order history, status, and tracking for each shipment.',
  helpQuickLinkProfile: 'Profile',
  helpQuickLinkProfileDesc: 'Update personal details, addresses, and account preferences.',
  helpQuickLinkReturnsPolicy: 'Returns policy',
  helpQuickLinkReturnsPolicyDesc: 'Read eligibility windows, conditions, and item-level return rules.',
  helpQuickLinkMyReturns: 'My returns',
  helpQuickLinkMyReturnsDesc: 'Track return requests, pickups, and refund progress.',
  helpQuickLinkContact: 'Contact support',
  helpQuickLinkContactDesc: 'Reach support for order and account questions.',
  overviewSupportTickets: 'Support tickets',
  overviewBugReports: 'Bug reports',
  helpContactDeskHint:
    'Send a message with as much detail as you can. Include your order ID when the issue is about a purchase. Prefer the helpdesk for ongoing conversations, or report a product bug separately.',
  helpContactUseSupport: 'For order and account help, open a support ticket.',
  helpContactSignIn: 'Sign in to open a support ticket.',
  helpOpenSupportTicket: 'Open a support ticket',
  helpSupportEyebrow: 'Support',
  helpCenterIntro:
    'Guides for orders, shipping, returns, payments, and your account — written for real shopping on this marketplace.',
  helpSearchPlaceholder: 'Search help articles…',
  helpSearchAriaLabel: 'Search help',
  helpSearchResultSingular: '{count} result for “{query}”',
  helpSearchResultPlural: '{count} results for “{query}”',
  helpSearchEmpty: 'No articles matched. Try different words, or contact support below.',
  helpQuickLinksEyebrow: 'Quick links',
  helpBrowseTopicsEyebrow: 'Browse topics',
  helpStillStuckEyebrow: 'Still stuck?',
  helpContactSupportHeading: 'Contact support',
  helpArticleNotFound: 'Article not found',
  helpArticleNotFoundMessage: 'That help article doesn’t exist or may have moved.',
  helpBackToCenter: 'Back to Help Center',
  helpRelatedEyebrow: 'Related',
  helpStillNeedHelp: 'Still need help?',
  helpContactSupportLink: 'Contact support',
  contactUsHeading: 'Contact Us',
  contactUsIntro:
    'Have a question about orders, shipping, or returns? Send us a message and our support team will follow up.',
  contactSupportDetails: 'Support Details',
  contactLoadingDetails: 'Loading support details…',
  contactEmailLabel: 'Email: {email}',
  contactHoursLabel: 'Working hours: {hours}',
  contactNotConfigured: 'Not configured',
  contactPreferSelfServe: 'Prefer self-serve? Visit the',
} as const

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_ORDER_MANAGER: 'ADMIN_ORDER_MANAGER',
  ADMIN_CATALOG_MANAGER: 'ADMIN_CATALOG_MANAGER',
  VENDOR_OWNER: 'VENDOR_OWNER',
  VENDOR_STAFF: 'VENDOR_STAFF',
  CUSTOMER: 'CUSTOMER',
} as const

export type RoleName = (typeof ROLES)[keyof typeof ROLES]
export const ROLE_VALUES = Object.values(ROLES) as [RoleName, ...RoleName[]]

export const ROLE_LABELS: Record<RoleName, string> = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.ADMIN_ORDER_MANAGER]: 'Order Manager',
  [ROLES.ADMIN_CATALOG_MANAGER]: 'Catalog Manager',
  [ROLES.VENDOR_OWNER]: 'Vendor Owner',
  [ROLES.VENDOR_STAFF]: 'Vendor Staff',
  [ROLES.CUSTOMER]: 'Customer',
}

export const ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN_ORDER_MANAGER,
  ROLES.ADMIN_CATALOG_MANAGER,
] as const

export const VENDOR_ROLES = [ROLES.VENDOR_OWNER, ROLES.VENDOR_STAFF] as const
