/** App Router path constants — single source for Link / router.push / redirects. */
export const PATHS = {
  home: '/',
  products: '/products',
  product: (slug: string) => `/products/${slug}`,
  productsNewest: '/products?sort=newest',
  productsTopRated: '/products?sort=rating',
  productsTrending: '/products?sort=trending',
  categories: '/categories',
  /** Hierarchical category path: `/category/home-kitchen/cookware` (prompt). */
  category: (...slugs: string[]) =>
    `/category/${slugs.map((slug) => encodeURIComponent(slug)).join('/')}`,
  vendors: '/vendors',
  vendorPage: (slug: string) => `/vendors/${slug}`,
  cart: '/cart',
  checkout: '/checkout',
  orders: '/orders',
  order: (id: string) => `/orders/${id}`,
  orderConfirmation: (id: string) => `/orders/${id}/confirmation`,
  wishlist: '/wishlist',
  reviews: '/reviews',
  returns: '/returns',
  myReturns: '/my-returns',
  myReturn: (id: string) => `/my-returns/${id}`,
  wallet: '/wallet',
  profile: '/profile',
  profileTab: (tab: string) => `/profile?tab=${tab}`,
  login: '/login',
  loginWithRedirect: (next: string) => `/login?redirect=${encodeURIComponent(next)}`,
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  authCallback: '/auth/callback',
  about: '/about',
  contact: '/contact',
  blog: '/blog',
  blogPost: (slug: string) => `/blog/${slug}`,
  help: '/help',
  faq: '/faq',
  privacy: '/privacy',
  terms: '/terms',
  supportTickets: '/support/tickets',
  supportTicket: (id: string) => `/support/tickets/${id}`,
  supportTicketNew: '/support/tickets/new',
  bugReports: '/support/bug-reports',
  bugReport: (id: string) => `/support/bug-reports/${id}`,
  bugReportNew: '/support/bug-reports/new',
  admin: {
    root: '/admin',
    vendors: '/admin/vendors',
    products: '/admin/products',
    categories: '/admin/categories',
    banners: '/admin/banners',
    orders: '/admin/orders',
    returns: '/admin/returns',
    coupons: '/admin/coupons',
    reviews: '/admin/reviews',
    tax: '/admin/tax',
    shipping: '/admin/shipping',
    finance: '/admin/finance',
    reports: '/admin/reports',
    users: '/admin/users',
    analytics: '/admin/analytics',
    audit: '/admin/audit',
    settings: '/admin/settings',
    profile: '/admin/profile',
    supportTickets: '/admin/support-tickets',
    supportTicket: (id: string) => `/admin/support-tickets/${id}`,
    bugReports: '/admin/bug-reports',
    bugReport: (id: string) => `/admin/bug-reports/${id}`,
  },
  vendor: {
    register: '/vendor/register',
    root: '/vendor',
    overview: '/vendor/dashboard/overview',
    products: '/vendor/dashboard/products',
    productCreateQuery: '/vendor/dashboard/products?create=1',
    productEditQuery: (id: string) =>
      `/vendor/dashboard/products?edit=${encodeURIComponent(id)}`,
    productImagesQuery: (id: string) =>
      `/vendor/dashboard/products?images=${encodeURIComponent(id)}`,
    orders: '/vendor/dashboard/orders',
    payouts: '/vendor/dashboard/payouts',
    coupons: '/vendor/dashboard/coupons',
    couponCreateQuery: '/vendor/dashboard/coupons?create=1',
    reviews: '/vendor/dashboard/reviews',
    profile: '/vendor/dashboard/profile',
    shopSettings: '/vendor/dashboard/shop-settings',
    reports: '/vendor/dashboard/reports',
    supportTickets: '/vendor/dashboard/support-tickets',
    supportTicket: (id: string) => `/vendor/dashboard/support-tickets/${id}`,
    bugReports: '/vendor/dashboard/bug-reports',
    bugReport: (id: string) => `/vendor/dashboard/bug-reports/${id}`,
    bugReportNew: '/vendor/dashboard/bug-reports/new',
  },
} as const
