/** App Router path constants — single source for Link / router.push / redirects. */
export const PATHS = {
  home: '/',
  products: '/products',
  product: (slug: string) => `/products/${slug}`,
  productsNewest: '/products?sort=newest',
  productsTopRated: '/products?sort=rating',
  productsTrending: '/products?sort=trending',
  categories: '/categories',
  /** Hierarchical category path: `/category/home-kitchen/cookware` (prompt). */
  category: (...slugs: string[]) =>
    `/category/${slugs.map((slug) => encodeURIComponent(slug)).join('/')}`,
  vendors: '/vendors',
  vendorPage: (slug: string) => `/vendors/${slug}`,
  cart: '/cart',
  checkout: '/checkout',
  orders: '/orders',
  order: (id: string) => `/orders/${id}`,
  orderConfirmation: (id: string) => `/orders/${id}/confirmation`,
  wishlist: '/wishlist',
  reviews: '/reviews',
  returns: '/returns',
  myReturns: '/my-returns',
  profile: '/profile',
  profileTab: (tab: string) => `/profile?tab=${tab}`,
  login: '/login',
  loginWithRedirect: (next: string) => `/login?redirect=${encodeURIComponent(next)}`,
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  about: '/about',
  contact: '/contact',
  blog: '/blog',
  blogPost: (slug: string) => `/blog/${slug}`,
  help: '/help',
  faq: '/faq',
  privacy: '/privacy',
  terms: '/terms',
  admin: {
    root: '/admin',
    vendors: '/admin/vendors',
    products: '/admin/products',
    categories: '/admin/categories',
    orders: '/admin/orders',
    returns: '/admin/returns',
    coupons: '/admin/coupons',
    reviews: '/admin/reviews',
    tax: '/admin/tax',
    shipping: '/admin/shipping',
    finance: '/admin/finance',
    users: '/admin/users',
    analytics: '/admin/analytics',
    audit: '/admin/audit',
    settings: '/admin/settings',
    profile: '/admin/profile',
  },
  vendor: {
    register: '/vendor/register',
    root: '/vendor',
    overview: '/vendor/dashboard/overview',
    products: '/vendor/dashboard/products',
    orders: '/vendor/dashboard/orders',
    payouts: '/vendor/dashboard/payouts',
    coupons: '/vendor/dashboard/coupons',
    reviews: '/vendor/dashboard/reviews',
    profile: '/vendor/dashboard/profile',
  },
} as const
