export const deliveryAgentDocumentsCardStyles = {
  section: "border border-line bg-surface shadow-elevation-1",
  header: "border-b border-line bg-paper/55 px-5 py-4 md:px-6",
  headerEyebrowRow: "flex items-center gap-2",
  icon: "size-4 text-brand",
  eyebrow: "!mb-0",
  title: "mt-1 font-display text-[1.125rem] font-medium text-ink",
  subtitle: "mt-1 text-[0.875rem] text-ink-muted",
  list: "divide-y divide-line/60",
  row: "flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between md:px-6",
  docInfo: "space-y-0.5",
  docTitle: "font-medium text-ink",
  actionsRow: "flex flex-wrap items-center gap-2",
  dateInput: "w-40",
  uploadButton:
    "inline-flex cursor-pointer items-center gap-2 rounded-md border border-line px-3 py-1.5 text-body-sm font-medium text-brand hover:bg-paper/60",
  fileInput: "sr-only",
  errorText: "px-5 pb-4 text-body-sm text-danger md:px-6",
  badgeNotSubmitted: "text-body-sm text-ink-muted",
  badgeApproved: "flex items-center gap-1 text-body-sm text-success",
  badgeRejected: "flex items-center gap-1 text-body-sm text-danger",
  badgePending: "flex items-center gap-1 text-body-sm text-warning",
  badgeIcon: "size-3.5",
  badgeExpired: "text-body-sm text-danger",
  badgeExpiringSoon: "text-body-sm text-warning",
  badgeExpiresNormal: "text-body-sm text-ink-muted",
} as const;
