import type { MetadataRoute } from "next";
import { SITE } from "@/shared/seo/constants";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE.name,
    short_name: SITE.shortName,
    description: SITE.description,
    start_url: "/",
    display: "standalone",
    // Manifest JSON cannot read CSS custom properties, so these mirror the
    // light-palette token values in shared/styles/globals.css (--paper, --brand).
    background_color: "#f6f3ec",
    theme_color: "#8a6a2e",
    icons: [
      // Raster icons are generated by scripts/generate-app-icons.mjs from the
      // same mark as app/icon.svg. Android installs and splash screens read
      // these from the manifest, and Chrome deprioritises SVG for them.
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
