export const adminPagesStyles = {
  pageRoot: "w-full min-w-0 space-y-5",
  stack6: "space-y-6",
  stack5: "space-y-5",
  stack4: "space-y-4",
  stack1: "space-y-1",
  headerRow: "flex flex-wrap items-center justify-between gap-3",
  headerInfo: "min-w-0 space-y-1",
  pageHeadingLg: "font-display text-[1.5rem] tracking-tight text-ink",
  pageHeadingLgNormal: "font-display text-[1.5rem] text-ink",
  pageHeadingXl:
    "font-display text-xl font-semibold tracking-tight text-ink sm:text-2xl",
  pageHeading: "font-display text-xl font-semibold text-ink",
  hint: "text-body-sm text-ink-muted",
  hintMuted: "mt-1 text-body-sm text-ink-muted",
  hintMax2xl: "max-w-2xl text-body-sm text-ink-muted",
  emptyCenteredNotice: "py-8 text-center text-body text-ink-muted",
  emptyText: "text-ink-muted",
  emptyBodyText: "text-body text-ink-muted",
  errorText: "text-danger",
  errorSmText: "text-body-sm text-danger",
  successSmText: "text-body-sm text-success",
  minW0: "min-w-0",
  tabContent: "mt-6 min-w-0 focus-visible:outline-none",
  tabsListStrong:
    "flex h-auto w-full flex-wrap justify-start gap-1 rounded-md border border-line-strong bg-paper p-1",
  tabTriggerBrand:
    "rounded-sm px-4 py-2.5 text-body-sm text-ink-muted hover:text-ink data-[state=active]:bg-brand data-[state=active]:text-paper data-[state=active]:shadow-none",
  formStack: "space-y-8",
  colSpan2: "sm:col-span-2",
  backLink:
    "inline-flex items-center gap-1.5 text-body-sm font-medium text-ink-muted hover:text-ink",
  borderBottomRow:
    "flex flex-wrap items-center justify-between gap-3 border-b border-line pb-4",
  borderBoxEmpty: "border border-line bg-surface-raised px-5 py-10 text-center",
  skeletonPy4: "space-y-3 py-4",
  skeletonH32: "h-32 w-full rounded-md",
  skeletonH28: "h-28 w-full rounded-md",
  skeletonH72: "h-72 w-full rounded-md",
  gridCols4: "grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4",
  iconSm: "size-4",
  subheadingMedium: "mb-2 text-body-sm font-medium text-ink",
  flexGap2: "flex items-center gap-2",
  fontMono: "font-mono",
  flexWrapGap2: "flex flex-wrap gap-2",
  inputMaxXs: "max-w-xs",
  cardSurface: "rounded-md border border-line bg-surface p-4 sm:p-5",
  stockEditorRow: "flex min-w-56 items-center justify-end gap-2",
  stockEditorInput: "w-24",
  stockEditorError: "max-w-40 text-body-sm text-danger",
  flexGap2_5: "flex items-center gap-2.5",
  buttonGap1_5: "gap-1.5",
  captionMediumMuted: "text-caption font-medium text-ink-muted",
  iconBrandMd: "size-5 text-brand",
  filterRow: "flex flex-wrap items-end gap-4",
  dateRangeInput: "w-full sm:w-44 lg:w-48",
  fieldFlex1MinW: "flex-1 min-w-[16rem]",
  wFullSmAuto: "w-full sm:w-auto",
  actionButtonH11: "w-full sm:w-auto h-11 px-6 font-medium",
  colMetric: "font-mono font-medium text-ink",
  colMuted: "text-ink-muted",
  colInkMedium: "font-medium text-ink",
} as const;
