import type { Metadata, Viewport } from "next";
import { SITE } from "./constants";

/**
 * Root viewport configuration (theme colors mirror the theme baseline).
 * `viewportFit: "cover"` is what makes the `env(safe-area-inset-*)` offsets in
 * the bottom tab bar, sheets, sticky bars and toasts resolve to real values on
 * iOS — without it they are all 0 and content sits under the home indicator.
 */
export const ROOT_VIEWPORT: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#F6F3EC" },
    { media: "(prefers-color-scheme: dark)", color: "#121113" },
  ],
};

/**
 * Root application metadata (Rule 27): title template, Open Graph/Twitter,
 * robots and icons — all copy pulled from the centralized `SITE` constants.
 */
export function generateRootMetadata(): Metadata {
  return {
    metadataBase: new URL(SITE.url),
    title: {
      template: `%s | ${SITE.name}`,
      default: SITE.name,
    },
    description: SITE.description,
    keywords: [
      "t-shirts",
      "online shopping",
      "premium clothing",
      "e-commerce",
      "multi-vendor",
    ],
    authors: [{ name: SITE.author }],
    creator: SITE.author,
    publisher: SITE.author,
    generator: "Next.js",
    applicationName: SITE.name,
    category: "e-commerce",
    openGraph: {
      type: "website",
      siteName: SITE.name,
      locale: SITE.locale,
      url: SITE.url,
      title: SITE.name,
      description: SITE.description,
      images: [{ url: SITE.ogImage, width: 1200, height: 630 }],
    },
    twitter: {
      card: "summary_large_image",
      site: SITE.twitter,
      creator: SITE.twitter,
      title: SITE.name,
      description: SITE.description,
      images: [SITE.ogImage],
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    icons: {
      icon: [
        { url: "/favicon.ico" },
        { url: "/icon.svg", type: "image/svg+xml" },
      ],
      // 180x180, opaque and full-bleed: iOS masks the corners itself and
      // ignores SVG. Generated by scripts/generate-app-icons.mjs.
      apple: [{ url: "/apple-icon.png", sizes: "180x180" }],
      other: [{ url: "/icon-512.png", sizes: "512x512" }],
    },
    verification: {
      google: process.env.GOOGLE_SITE_VERIFICATION,
    },
  };
}
