/** Admin sidebar navigation labels. Subset of LABELS; merged in labels/index.ts. */
export const adminNavigationLabels = {
  vendors: "Vendors",
  products: "Products",
  inventory: "Inventory",
  categories: "Categories",
  orders: "Orders",
  returnsRefunds: "Returns / Refunds",
  coupons: "Coupons",
  reviews: "Reviews",
  vendorReviewsHint:
    "Customer reviews on your products. Respond from this page when a reply is needed.",
  reviewUntitled: "Review",
  reviewRatingOutOf: "{rating}/5",
  respondToReview: "Respond",
  reviewResponseTitle: "Respond to review",
  reviewResponseBody: "Your reply is posted publicly on the product page.",
  reviewResponseLabel: "Response",
  reviewResponseEmptyHint: "Enter a response to send.",
  noReviewsFound: "No reviews found.",
  couldNotLoadReviews: "Could not load reviews.",
  tax: "Tax",
  shipping: "Shipping",
  financePayouts: "Finance / Payouts",
  users: "Users",
  analytics: "Analytics",
  analyticsHint:
    "Commerce health, growth trends, and queues that need attention — tuned for the marketplace.",
  analyticsGmv: "Gross merchandise volume",
  analyticsPaidGmv: "Paid GMV",
  analyticsAov: "Average order value",
  analyticsTotalOrders: "Orders",
  analyticsCustomers: "Customers",
  analyticsVendors: "Vendors",
  analyticsCancellationRate: "Cancellation rate",
  analyticsReturnRate: "Return rate",
  analyticsOrderTrend: "Order & revenue trend",
  analyticsOrderTrendHint: "Non-cancelled orders over the last 30 days",
  analyticsOrdersByStatus: "Orders by status",
  analyticsPaymentsByStatus: "Payments by status",
  analyticsPaymentsTotal: "Payments",
  analyticsTopVendors: "Top vendors",
  analyticsTopCategories: "Top categories",
  analyticsRatingDistribution: "Approved review ratings",
  analyticsOpsQueues: "Needs attention",
  analyticsPendingProducts: "Pending products",
  analyticsPendingVendors: "Pending vendors",
  analyticsPendingReviews: "Pending reviews",
  analyticsGrowthOrders: "Orders (14d)",
  analyticsGrowthRevenue: "Revenue (14d)",
  analyticsNoData: "No analytics data available",
  analyticsOrdersSeries: "Orders",
  analyticsRevenueSeries: "Revenue",
  analyticsRankShare: "{value}% of total",
  analyticsEmptyChart: "Not enough data to chart yet.",
  analyticsStarRating: "{rating}★",
  analyticsVsPriorPeriod: "vs prior 14 days",
  percentValue: "{value}%",
  audit: "Audit",
  settings: "Settings",
  notifications: "Notifications",
  deliveryAgents: "Delivery agents",

  // Vendor / account nav
} as const;
