/** Authentication copy. Subset of LABELS; merged in labels/index.ts. */
export const authLabels = {
  logIn: "Log in",
  backToLogin: "Back to login",
  alreadyHaveAccount: "Already have an account?",
  welcomeBack: "Welcome back",
  logInToAccount: "Log in to your account",
  dontHaveAccount: "Don't have an account?",
  register: "Register",
  loginFailed: "Login failed",
  createAccount: "Create an account",
  createAccountHint: "Join the marketplace in a few steps.",
  phoneOptional: "Phone (optional)",
  forgotPassword: "Forgot password?",
  forgotPasswordTitle: "Forgot password",
  forgotPasswordHint: "Enter your email and we’ll send you a reset link.",
  sendResetLink: "Send reset link",
  resetLinkSent: "If that email exists, a reset link has been sent.",
  resetPasswordTitle: "Reset password",
  resetPasswordHint: "Choose a new password for your account.",
  newPassword: "New password",
  resetPassword: "Reset password",
  resetPasswordFailed: "Reset failed or link expired.",
  password: "Password",
  verifyOtpTitle: "Verify OTP",
  verifyOtpHint: "Enter the 6-digit code sent to your email.",
  resendCode: "Resend code",
  resendCodeWait: "You can resend a new code after the timer ends.",
  verifyCode: "Verify code",
  enterCompleteOtp: "Enter the complete 6-digit code to verify.",
  orContinueWith: "Or continue with",
  continueWithGoogle: "Continue with Google",
  oauthNotConfigured:
    "Google sign-in is not set up yet. Add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET on the server.",
  oauthSignInFailed: "Google sign-in failed. Please try again.",
  oauthCompletingSignIn: "Completing sign-in…",
  authBrandHeadline: "Shop with clarity.",
  authBrandBody:
    "Curated finds, trusted sellers, and a checkout experience that stays out of your way.",
  authBrandEyebrow: "Independent marketplace",
  authBrandFooter: "Secure sign-in · Encrypted sessions",
  authFeatureCurated: "Curated sellers",
  authFeatureCuratedHint: "Hand-picked shops you can trust",
  authFeatureSecure: "Secure checkout",
  authFeatureSecureHint: "Encrypted sign-in and payments",
  authFeatureDelivery: "Reliable delivery",
  authFeatureDeliveryHint: "Track orders from cart to door",
  changePasswordTitle: "Change password",
  changePasswordHint: "Use a strong password you don’t reuse elsewhere.",
  changePasswordSuccess: "Password changed successfully.",
  couldNotLoadSessions: "Could not load sessions.",
  changePasswordAgain: "Change again",
  currentPassword: "Current password",
  changePassword: "Change password",
  couldNotChangePassword: "Could not change password.",
  verifyEmailTitle: "Verify your email",
  verifyEmailHint:
    "Confirm the address we sent this link to so you can keep using your account.",
  verifyEmailSuccess: "Your email is verified. You can continue shopping.",
  verifyEmailFailed: "This verification link is invalid or has expired.",
  verifyEmailMissingToken:
    "This link is missing a verification token. Use the latest email we sent.",
  verifyingEmail: "Verifying your email…",
  continueToAccount: "Continue to account",
  resendVerificationEmail: "Resend verification email",
  verificationEmailSent: "A new verification email is on its way.",
  emailAlreadyVerified: "This email is already verified.",
  couldNotSendVerificationEmail:
    "Could not send a verification email. Try again shortly.",

  // Footer sections
} as const;
