/** Bug report copy (part 2); merged via labels.ts. */
export const bugs2Labels = {
  bugTimelineStatusChanged: "Status updated",
  vendorBugReportsUtility: "My bug reports",
  bugWontFix: "Won’t fix",
  bugWontFixReason: "Reason",
  bugWontFixSubmit: "Confirm won’t fix",
  bugSignInRequired: "Sign in to view and submit bug reports.",
  bugTitleRequired: "Title is required",
  bugDescriptionRequired: "Description is required",
  enterBugTitle: "Enter a bug title to continue.",
  enterBugDescription: "Enter a description of what went wrong.",
  bugTitleTooLong: "Title must be {max} characters or fewer.",
  bugDescriptionTooLong: "Description must be {max} characters or fewer.",
  bugStepsTooLong: "Steps must be {max} characters or fewer.",
  bugCommentTooLong: "Comment must be {max} characters or fewer.",
  bugWontFixReasonTooLong: "Reason must be {max} characters or fewer.",
  bugAttachmentLimit:
    "You can attach up to 5 screenshots and 1 screen recording.",
  bugAttachmentTypeMissing:
    "One or more attachments are missing a type. Remove and re-upload them.",
  bugStatusNew: "New",
  bugStatusTriaged: "Triaged",
  bugStatusInProgress: "In progress",
  bugStatusFixed: "Fixed",
  bugStatusVerified: "Verified",
  bugStatusClosed: "Closed",
  bugStatusWontFix: "Won’t fix",
  bugStatusDuplicate: "Duplicate",
  bugSeverityLow: "Low",
  bugSeverityMedium: "Medium",
  bugSeverityHigh: "High",
  bugSeverityCritical: "Critical",
  bugModuleCatalog: "Catalog",
  bugModuleCart: "Cart",
  bugModuleCheckout: "Checkout",
  bugModulePayments: "Payments",
  bugModuleOrders: "Orders",
  bugModuleVendorDashboard: "Vendor dashboard",
  bugModuleAdminDashboard: "Admin dashboard",
  bugModuleOther: "Other",
  bugReporterRoleCustomer: "Customer",
  bugReporterRoleVendor: "Vendor",
  bugReporterRoleVendorStaff: "Vendor staff",
  bugFilterAllSeverities: "All severities",
  bugFilterAllModules: "All modules",
  bugFilterAllReporterRoles: "All reporter roles",
  bugFilterReporterRole: "Reporter role",
  bugReportNumberLabel: "Report {number}",
  helpQuickLinkTickets: "My support tickets",
  helpQuickLinkTicketsDesc:
    "Open and track authenticated helpdesk conversations.",
  helpQuickLinkBugs: "Report a bug",
  helpQuickLinkBugsDesc: "Tell us when something on the site breaks.",
  helpQuickLinkOrders: "My orders",
  helpQuickLinkOrdersDesc:
    "View order history, status, and tracking for each shipment.",
  helpQuickLinkProfile: "Profile",
  helpQuickLinkProfileDesc:
    "Update personal details, addresses, and account preferences.",
  helpQuickLinkReturnsPolicy: "Returns policy",
  helpQuickLinkReturnsPolicyDesc:
    "Read eligibility windows, conditions, and item-level return rules.",
  helpQuickLinkMyReturns: "My returns",
  helpQuickLinkMyReturnsDesc:
    "Track return requests, pickups, and refund progress.",
  helpQuickLinkContact: "Contact support",
  helpQuickLinkContactDesc: "Reach support for order and account questions.",
  overviewSupportTickets: "Support tickets",
  overviewBugReports: "Bug reports",
  helpContactDeskHint:
    "Send a message with as much detail as you can. Include your order ID when the issue is about a purchase. Prefer the helpdesk for ongoing conversations, or report a product bug separately.",
  helpContactUseSupport: "For order and account help, open a support ticket.",
  helpContactSignIn: "Sign in to open a support ticket.",
  helpOpenSupportTicket: "Open a support ticket",
  helpSupportEyebrow: "Support",
  helpCenterIntro:
    "Guides for orders, shipping, returns, payments, and your account — written for real shopping on this marketplace.",
  helpSearchPlaceholder: "Search help articles…",
  helpSearchAriaLabel: "Search help",
  helpSearchResultSingular: "{count} result for “{query}”",
  helpSearchResultPlural: "{count} results for “{query}”",
  helpSearchEmpty:
    "No articles matched. Try different words, or contact support below.",
  helpQuickLinksEyebrow: "Quick links",
  helpBrowseTopicsEyebrow: "Browse topics",
  helpStillStuckEyebrow: "Still stuck?",
  helpContactSupportHeading: "Contact support",
  helpArticleNotFound: "Article not found",
  helpArticleNotFoundMessage:
    "That help article doesn’t exist or may have moved.",
  helpBackToCenter: "Back to Help Center",
  helpRelatedEyebrow: "Related",
  helpStillNeedHelp: "Still need help?",
  helpContactSupportLink: "Contact support",
  contactUsHeading: "Contact Us",
  contactUsIntro:
    "Have a question about orders, shipping, or returns? Send us a message and our support team will follow up.",
  contactSupportDetails: "Support Details",
  contactLoadingDetails: "Loading support details…",
  contactEmailLabel: "Email: {email}",
  contactHoursLabel: "Working hours: {hours}",
  contactNotConfigured: "Not configured",
  contactPreferSelfServe: "Prefer self-serve? Visit the",
} as const;
