/** Bug report copy (part 1); merged via labels.ts. */
export const bugsLabels = {
  bugReports: "Bug reports",
  bugReport: "Bug report",
  myBugReports: "My bug reports",
  reportABug: "Report a bug",
  bugReportsPageDescription:
    "Report product issues so we can investigate and fix them.",
  bugReportsEmpty: "No bug reports yet",
  bugReportsEmptyMessage:
    "Report a bug when something on the site does not work as expected.",
  newBugReport: "Report a bug",
  newBugReportDescription:
    "Tell us what went wrong. We capture the page and device context automatically. Severity is optional.",
  bugBasicsSection: "Bug details",
  bugBasicsSectionHint: "A clear title helps triage.",
  bugSeverityOptional: "Severity (optional)",
  bugSeverityHint: "Leave blank if you are unsure — admins will triage.",
  bugSeverityNone: "Not sure",
  bugDescriptionSection: "What happened",
  bugDescriptionSectionHint:
    "Describe the issue and optional steps to reproduce.",
  bugAttachmentsSection: "Screenshots & recording",
  bugAttachmentsSectionHint:
    "Up to 5 screenshots and 1 recording (max 2 minutes).",
  bugReportNumber: "Report #",
  bugReporter: "Reporter",
  bugView: "View",
  bugNoCommentsYet: "No internal notes yet. Add the first triage note below.",
  bugInternalCommentsHint:
    "Visible to admins only — never shown to the reporter.",
  bugBackToList: "Back to bug reports",
  bugProgress: "Progress",
  bugProgressHint:
    "We update this as your report moves through triage and fixes.",
  bugVerifyHint: "Please confirm the issue is fixed on your side.",
  bugDetailsEyebrow: "Bug report",
  bugAttachmentsHeading: "Attachments",
  bugCurrentStatus: "Current status",
  bugFiledOn: "Filed on",
  bugTitle: "Title",
  bugTitlePlaceholder: "Short summary of the bug",
  bugDescription: "Description",
  bugDescriptionPlaceholder: "What you saw versus what you expected.",
  bugStepsToReproduce: "Steps to reproduce (optional)",
  bugStepsPlaceholder: "1. Go to…\n2. Click…\n3. See error…",
  bugAttachments: "Screenshots & recording",
  bugSubmit: "Submit bug report",
  bugCreatedSuccess: "Bug report submitted.",
  bugCouldNotCreate: "Could not submit bug report.",
  bugCouldNotLoad: "Could not load bug reports.",
  bugCouldNotLoadDetail: "Could not load this bug report.",
  bugVerifyFixed: "Confirm fixed",
  bugVerifiedThanks: "Thanks — marked as verified.",
  bugAdminQueueDescription:
    "Triage queue with severity, module, and reporter filters.",
  bugContextPanel: "Reporter context",
  bugPageUrl: "Page URL",
  bugBrowser: "Browser",
  bugOs: "OS",
  bugDevice: "Device",
  bugAppVersion: "App version",
  bugUserAgent: "User agent",
  bugOccurredAt: "Occurred at",
  bugReporterUserId: "Reporter ID",
  bugReporterUserRole: "Reporter role",
  bugReporterRoleLabel: "Reporter type",
  bugInternalComments: "Internal comments",
  bugCommentPlaceholder: "Add an internal note…",
  bugAddComment: "Add comment",
  bugCouldNotComment: "Could not add comment.",
  bugCouldNotUpdate: "Could not update bug report.",
  bugTriage: "Triage",
  bugSeverity: "Severity",
  bugAffectedModule: "Affected module",
  bugAssignToId: "Assignee",
  bugAssigneePlaceholder: "Select an assignee",
  bugAssigneeNone: "Unassigned",
  bugTriageSubmit: "Save triage",
  bugSaveAssignment: "Save assignment",
  bugAssignmentSaved: "Assignment updated.",
  bugCouldNotSaveAssignment: "Could not save assignment.",
  bugUpdateStatus: "Update status",
  bugMarkDuplicate: "Mark duplicate",
  bugDuplicateOfId: "Duplicate of report # or ID",
  bugDuplicateOfHint:
    "Paste a report number like BUG-000123, or the report UUID.",
  bugDuplicateOfPlaceholder: "BUG-000123",
  bugDuplicateOf: "This report is a duplicate of",
  bugTimeline: "Status timeline",
  bugTimelineFiled: "Filed",
  bugTimelineTriaged: "Triaged",
  bugTimelineInProgress: "In progress",
  bugTimelineResolved: "Marked fixed",
  bugTimelineCurrent: "Current status",
  bugTimelineAssignmentUpdated: "Assignment updated",
  bugTimelineDuplicate: "Marked duplicate",
  bugTimelineWontFix: "Won’t fix",
  bugTimelineVerified: "Verified",
  bugTimelineAutoVerified: "Auto-verified",
  bugTimelineAutoClosed: "Auto-closed",
} as const;
