/** Bug report flows. Subset of LABELS; merged in labels/index.ts. */
export const bugsLabels = {
  bugReports: "Bug reports",
  bugReport: "Bug report",
  myBugReports: "My bug reports",
  reportABug: "Report a bug",
  bugReportsPageDescription:
    "Report product issues so we can investigate and fix them.",
  bugReportsEmpty: "No bug reports yet",
  bugReportsEmptyMessage:
    "Report a bug when something on the site does not work as expected.",
  newBugReport: "Report a bug",
  newBugReportDescription:
    "Tell us what went wrong. We capture the page and device context automatically. Severity is optional.",
  bugBasicsSection: "Bug details",
  bugBasicsSectionHint: "A clear title helps triage.",
  bugSeverityOptional: "Severity (optional)",
  bugSeverityHint: "Leave blank if you are unsure — admins will triage.",
  bugSeverityNone: "Not sure",
  bugDescriptionSection: "What happened",
  bugDescriptionSectionHint:
    "Describe the issue and optional steps to reproduce.",
  bugAttachmentsSection: "Screenshots & recording",
  bugAttachmentsSectionHint:
    "Up to 5 screenshots and 1 recording (max 2 minutes).",
  bugReportNumber: "Report #",
  bugReporter: "Reporter",
  bugView: "View",
  bugNoCommentsYet: "No internal notes yet. Add the first triage note below.",
  bugInternalCommentsHint:
    "Visible to admins only — never shown to the reporter.",
  bugBackToList: "Back to bug reports",
  bugProgress: "Progress",
  bugProgressHint:
    "We update this as your report moves through triage and fixes.",
  bugVerifyHint: "Please confirm the issue is fixed on your side.",
  bugDetailsEyebrow: "Bug report",
  bugAttachmentsHeading: "Attachments",
  bugCurrentStatus: "Current status",
  bugFiledOn: "Filed on",
  bugTitle: "Title",
  bugTitlePlaceholder: "Short summary of the bug",
  bugDescription: "Description",
  bugDescriptionPlaceholder: "What you saw versus what you expected.",
  bugStepsToReproduce: "Steps to reproduce (optional)",
  bugStepsPlaceholder: "1. Go to…\n2. Click…\n3. See error…",
  bugAttachments: "Screenshots & recording",
  bugSubmit: "Submit bug report",
  bugCreatedSuccess: "Bug report submitted.",
  bugCouldNotCreate: "Could not submit bug report.",
  bugCouldNotLoad: "Could not load bug reports.",
  bugCouldNotLoadDetail: "Could not load this bug report.",
  bugVerifyFixed: "Confirm fixed",
  bugVerifiedThanks: "Thanks — marked as verified.",
  bugAdminQueueDescription:
    "Triage queue with severity, module, and reporter filters.",
  bugContextPanel: "Reporter context",
  bugPageUrl: "Page URL",
  bugBrowser: "Browser",
  bugOs: "OS",
  bugDevice: "Device",
  bugAppVersion: "App version",
  bugUserAgent: "User agent",
  bugOccurredAt: "Occurred at",
  bugReporterUserId: "Reporter ID",
  bugReporterUserRole: "Reporter role",
  bugReporterRoleLabel: "Reporter type",
  bugInternalComments: "Internal comments",
  bugCommentPlaceholder: "Add an internal note…",
  bugAddComment: "Add comment",
  bugCouldNotComment: "Could not add comment.",
  bugCouldNotUpdate: "Could not update bug report.",
  bugTriage: "Triage",
  bugSeverity: "Severity",
  bugAffectedModule: "Affected module",
  bugAssignToId: "Assignee",
  bugAssigneePlaceholder: "Select an assignee",
  bugAssigneeNone: "Unassigned",
  bugTriageSubmit: "Save triage",
  bugSaveAssignment: "Save assignment",
  bugAssignmentSaved: "Assignment updated.",
  bugCouldNotSaveAssignment: "Could not save assignment.",
  bugUpdateStatus: "Update status",
  bugMarkDuplicate: "Mark duplicate",
  bugDuplicateOfId: "Duplicate of report # or ID",
  bugDuplicateOfHint:
    "Paste a report number like BUG-000123, or the report UUID.",
  bugDuplicateOfPlaceholder: "BUG-000123",
  bugDuplicateOf: "This report is a duplicate of",
  bugTimeline: "Status timeline",
  bugTimelineFiled: "Filed",
  bugTimelineTriaged: "Triaged",
  bugTimelineInProgress: "In progress",
  bugTimelineResolved: "Marked fixed",
  bugTimelineCurrent: "Current status",
  bugTimelineAssignmentUpdated: "Assignment updated",
  bugTimelineDuplicate: "Marked duplicate",
  bugTimelineWontFix: "Won’t fix",
  bugTimelineVerified: "Verified",
  bugTimelineAutoVerified: "Auto-verified",
  bugTimelineAutoClosed: "Auto-closed",
  bugTimelineStatusChanged: "Status updated",
  vendorBugReportsUtility: "My bug reports",
  bugWontFix: "Won’t fix",
  bugWontFixReason: "Reason",
  bugWontFixSubmit: "Confirm won’t fix",
  bugSignInRequired: "Sign in to view and submit bug reports.",
  bugTitleRequired: "Title is required",
  bugDescriptionRequired: "Description is required",
  enterBugTitle: "Enter a bug title to continue.",
  enterBugDescription: "Enter a description of what went wrong.",
  bugTitleTooLong: "Title must be {max} characters or fewer.",
  bugDescriptionTooLong: "Description must be {max} characters or fewer.",
  bugStepsTooLong: "Steps must be {max} characters or fewer.",
  bugCommentTooLong: "Comment must be {max} characters or fewer.",
  bugWontFixReasonTooLong: "Reason must be {max} characters or fewer.",
  bugAttachmentLimit:
    "You can attach up to 5 screenshots and 1 screen recording.",
  bugAttachmentTypeMissing:
    "One or more attachments are missing a type. Remove and re-upload them.",
  bugStatusNew: "New",
  bugStatusTriaged: "Triaged",
  bugStatusInProgress: "In progress",
  bugStatusFixed: "Fixed",
  bugStatusVerified: "Verified",
  bugStatusClosed: "Closed",
  bugStatusWontFix: "Won’t fix",
  bugStatusDuplicate: "Duplicate",
  bugSeverityLow: "Low",
  bugSeverityMedium: "Medium",
  bugSeverityHigh: "High",
  bugSeverityCritical: "Critical",
  bugModuleCatalog: "Catalog",
  bugModuleCart: "Cart",
  bugModuleCheckout: "Checkout",
  bugModulePayments: "Payments",
  bugModuleOrders: "Orders",
  bugModuleVendorDashboard: "Vendor dashboard",
  bugModuleAdminDashboard: "Admin dashboard",
  bugModuleOther: "Other",
  bugReporterRoleCustomer: "Customer",
  bugReporterRoleVendor: "Vendor",
  bugReporterRoleVendorStaff: "Vendor staff",
  bugFilterAllSeverities: "All severities",
  bugFilterAllModules: "All modules",
  bugFilterAllReporterRoles: "All reporter roles",
  bugFilterReporterRole: "Reporter role",
  bugReportNumberLabel: "Report {number}",
  helpQuickLinkTickets: "My support tickets",
  helpQuickLinkTicketsDesc:
    "Open and track authenticated helpdesk conversations.",
  helpQuickLinkBugs: "Report a bug",
  helpQuickLinkBugsDesc: "Tell us when something on the site breaks.",
  helpQuickLinkOrders: "My orders",
  helpQuickLinkOrdersDesc:
    "View order history, status, and tracking for each shipment.",
  helpQuickLinkProfile: "Profile",
  helpQuickLinkProfileDesc:
    "Update personal details, addresses, and account preferences.",
  helpQuickLinkReturnsPolicy: "Returns policy",
  helpQuickLinkReturnsPolicyDesc:
    "Read eligibility windows, conditions, and item-level return rules.",
  helpQuickLinkMyReturns: "My returns",
  helpQuickLinkMyReturnsDesc:
    "Track return requests, pickups, and refund progress.",
  helpQuickLinkContact: "Contact support",
  helpQuickLinkContactDesc: "Reach support for order and account questions.",
  overviewSupportTickets: "Support tickets",
  overviewBugReports: "Bug reports",
  helpContactDeskHint:
    "Send a message with as much detail as you can. Include your order ID when the issue is about a purchase. Prefer the helpdesk for ongoing conversations, or report a product bug separately.",
  helpContactUseSupport: "For order and account help, open a support ticket.",
  helpContactSignIn: "Sign in to open a support ticket.",
  helpOpenSupportTicket: "Open a support ticket",
  helpSupportEyebrow: "Support",
  helpCenterIntro:
    "Guides for orders, shipping, returns, payments, and your account — written for real shopping on this marketplace.",
  helpSearchPlaceholder: "Search help articles…",
  helpSearchAriaLabel: "Search help",
  helpSearchResultSingular: "{count} result for “{query}”",
  helpSearchResultPlural: "{count} results for “{query}”",
  helpSearchEmpty:
    "No articles matched. Try different words, or contact support below.",
  helpQuickLinksEyebrow: "Quick links",
  helpBrowseTopicsEyebrow: "Browse topics",
  helpStillStuckEyebrow: "Still stuck?",
  helpContactSupportHeading: "Contact support",
  helpArticleNotFound: "Article not found",
  helpArticleNotFoundMessage:
    "That help article doesn’t exist or may have moved.",
  helpBackToCenter: "Back to Help Center",
  helpRelatedEyebrow: "Related",
  helpStillNeedHelp: "Still need help?",
  helpContactSupportLink: "Contact support",
  contactUsHeading: "Contact Us",
  contactUsIntro:
    "Have a question about orders, shipping, or returns? Send us a message and our support team will follow up.",
  contactSupportDetails: "Support Details",
  contactLoadingDetails: "Loading support details…",
  contactEmailLabel: "Email: {email}",
  contactHoursLabel: "Working hours: {hours}",
  contactNotConfigured: "Not configured",
  contactPreferSelfServe: "Prefer self-serve? Visit the",
} as const;
