/** CTAs and commerce copy. Subset of LABELS; merged in labels/index.ts. */
export const commerceLabels = {
  continueShopping: "Continue shopping",
  outOfStock: "Out of stock",
  addToWishlist: "Add to wishlist",
  removeFromWishlist: "Remove from wishlist",
  addToCart: "Add to cart",
  selectOptions: "Select options",
  selectAllOptionsHint: "Select all options to add this item to your cart.",
  selectOptionsHint: "Select product options to add this item to your cart.",
  outOfStockHint: "This item is currently out of stock.",
  addingToCart: "Adding to your cart…",
  addToCartWithPrice: "Add to cart — ₹{price}",
  inStock: "In stock",
  onlyLeft: "Only {count} left",
  freeDeliveryAbove: "Free delivery on orders above ₹{amount}",
  deliveryAtCheckout: "Delivery options shown at checkout",
  easyReturnsDays: "{days}-day easy returns",
  returnsEligible: "Returns available on eligible items",
  notReturnable: "This item is not returnable",
  returnShippingFeeAmount: "Return shipping ₹{amount}",
  returnShippingFree: "Free return pickup",
  checkPincode: "Check",
  enterDeliveryPincode: "Enter pincode",
  deliveryPincodeHint:
    "Check delivery time and cash-on-delivery for your area.",
  invalidPincode: "Enter a valid 6-digit pincode",
  deliveryEtaDays: "Arrives in {days} day(s)",
  deliveryEtaWithCost: "Arrives in {days} day(s) · ₹{amount}",
  deliveryEtaFree: "Arrives in {days} day(s) · free delivery",
  deliveryNotServiceable: "Not deliverable to this pincode",
  deliveryCheckFailed: "Could not check delivery for this pincode.",
  cashOnDelivery: "Cash on delivery",
  codAvailable: "Cash on delivery available",
  codUnavailable: "Cash on delivery not available",
  codConfirmPincode: "Confirm cash on delivery with your pincode",
  codMinOrder: "COD on orders of ₹{amount} or more",
  codMaxOrder: "COD on orders up to ₹{amount}",
  taxExclusiveGst: "Exclusive of GST ({percent}%)",
  taxInclusiveEstimate: "Approx. ₹{amount} including GST",
  hsnCodeLabel: "HSN {code}",
  warrantyManufacturer: "manufacturer warranty",
  warrantySeller: "seller warranty",
  warrantyMonthsLabel: "{months}-month {type}",
  sizeChart: "Size chart",
  sizeChartForProduct: "Size chart for {name}",
  productVideo: "Product video",
  relatedProducts: "Related products",
  moreFromSeller: "More from this seller",
  pdfPreview: "PDF",
  videoPreview: "Video",
  description: "Description",
  specifications: "Specifications",
  reviewsWithCount: "Reviews ({count})",
  stockAvailable: "{count} available",
  categoryLabel: "Category",
  generalCategory: "General",
  notAvailable: "Not available",
  variantUnavailableHint: "Not available with your current selection.",
  previousImage: "Previous image",
  nextImage: "Next image",
  hoverToZoom: "Hover to zoom",
  longTouchToZoom: "Long-press to zoom",
  imageZoomPreview: "Zoomed product image",
  imagePosition: "{current} / {total}",
  viewLargerImage: "View larger image",
  imageGalleryThumbnails: "Image thumbnails",
  productBrand: "Brand",
  productHighlights: "Highlights",
  productWeight: "Weight",
  productWeightGrams: "{grams} g",
  discountPercentOff: "{percent}% off",
  alsoInCategories: "Also in",
  selectedOptions: "Selected options",
  listPrice: "MRP",
  variantPrice: "Price",
  soldBy: "Sold by",
  visitStore: "Visit store",
  productTags: "Tags",
  approvalQueue: "Approval queue",
  newArrivals: "New Arrivals",
  topRated: "Top Rated",
  allProducts: "All Products",
  shop: "Shop",
  goToMyOrders: "Go to my orders",
  allOrders: "All orders",

  // Content
  readArticle: "Read article",

  // Auth
  maintenanceHeading: "Scheduled maintenance",
  maintenanceBody:
    "We're making improvements to the marketplace. Please check back shortly.",
} as const;
