/** Copy subset (part 1); merged via labels.ts. */
export const couponsLabels = {
  couponRemovedUnavailable:
    "Coupon was removed because some items are no longer available.",
  couponRemovedCartChange: "Your coupon was removed due to cart changes.",
  applyCoupon: "Apply",
  removeCoupon: "Remove",
  couponCodePlaceholder: "Enter coupon code",
  couponApplied: "Coupon applied — ₹{amount} off",
  couponAppliedCheckout:
    "Coupon applied — discount will be calculated at checkout",
  couponInvalid: "Invalid or expired coupon code",
  couponAppliedLabel: "Applied: {code}",
  couponDiscount: "Discount",
  availableOffers: "Available offers",
  availableOffersCount: "{count} available offers",
  availableOffersList: "Scroll to view more offers",
  showMoreOffers: "Show {count} more offers",
  showLessOffers: "Show less",
  noAvailableOffers: "No offers available for this cart.",
  applyOffer: "Apply offer",
  offersAtCheckout: "Offers available at checkout",
  autoAppliedOffer: "Best available offer applied automatically.",
  signInToApplyCoupon: "Sign in to apply coupon codes to your order.",
  enterCouponCodeToApply: "Enter a coupon code to apply it.",
  couponSectionBasics: "Basics",
  couponSectionValue: "Value",
  couponSectionScope: "Scope",
  couponSectionConstraints: "Constraints",
  couponSectionRestrictions: "Restrictions",
  discountBearer: "Discount bearer",
  discountBearerPlatform: "Platform",
  discountBearerVendor: "Vendor",
  applicableScope: "Applicable scope",
  scopeTypeAll: "All products",
  scopeTypeVendor: "Vendor",
  scopeTypeProduct: "Products",
  scopeTypeCategory: "Categories",
  scopeIds: "Applicable items",
  selectScopeCategories: "Select categories",
  selectScopeProducts: "Select products",
  selectScopeVendors: "Select vendors",
  searchCategories: "Search categories",
  searchProducts: "Search products",
  searchProductsVendors: "Search products, vendors, categories...",
  searchVendors: "Search vendors",
  searchSuggestions: "Search suggestions",
  searchAutocompleteEmpty: "No matching results",
  searchAutocompleteEmptyHint:
    "Try another spelling, or browse products and shops.",
  searchSuggestionTypeProduct: "Product",
  searchSuggestionTypeVendor: "Vendor",
  searchSuggestionTypeCategory: "Category",
  searchSuggestionSku: "SKU {sku}",
  searchSuggestionProducts: "Products",
  searchSuggestionVendors: "Shops",
  searchSuggestionCategories: "Categories",
  searchOpenResult: "Open",
  noCategoriesFound: "No categories found",
  noProductsFound: "No products found",
  noVendorsFound: "No vendors found",
  couponScopeNoneSelected: "None selected",
  couponScopeSelectedCount: "{count} selected",
  couponScopeIdsRequired: "Select at least one item for this scope",
  couponBundleProductsRequired: "Select at least one bundle product",
  couponSegmentRequired: "Select a customer segment",
  enterCouponScopeIds: "Select at least one category, product, or vendor.",
  couponTierHint:
    "Tier 1 uses min order value + value %. Optional tier 2 below.",
  couponTier2Min: "Tier 2 min subtotal",
  couponTier2Percent: "Tier 2 percent",
  selectBundleProducts: "Bundle products",
  userRestrictionSegmentNew: "New customers",
  userRestrictionSegmentReturning: "Returning customers",
  userRestrictionSegmentLoyal: "Loyal customers (3+ orders)",
  batchRedemptions: "Redemptions",
  batchDiscountImpact: "Discount impact",
  batchRevenueImpact: "Revenue impact",
  batchCodes: "Codes",
  batchExpires: "Expires",
  viewBatchCodes: "View codes",
  vendorDiscountBreakdown: "Discount by seller",
  conversionRate: "Conversion rate",
  revenueImpact: "Revenue impact",
  discountCostImpact: "Discount cost",
  rejectCoupon: "Reject",
  confirmRejectCouponTitle: "Reject this vendor coupon?",
  confirmRejectCouponBody: '"{code}" will be rejected and cannot be redeemed.',
  searchUsers: "Search users by name or email",
  noUsersFound: "No users found",
  couponSpecificUsersRequired: "Select at least one user for this restriction",
  selectSpecificUsers: "Eligible users",
  noPdpOffers: "No offers available for this product.",
  absorbedThisPeriod: "This calendar month",
  noneSelected: "None selected",
  selectedCount: "{count} selected",
  loadingMore: "Loading more…",
  noResults: "No results found",
  couldNotLoadOptions: "Could not load options",
  minQuantity: "Min quantity",
  usageLimitTotal: "Total usage limit",
  usageLimitPerUser: "Per-user usage limit",
  stackable: "Stackable",
  stackableHint:
    "When enabled, this coupon can combine with other stackable coupons on the same order.",
  priority: "Priority",
  userRestriction: "User restriction",
  userRestrictionSegment: "Customer segment",
  userRestrictionAll: "All users",
  userRestrictionFirstOrder: "First order only",
  userRestrictionSpecific: "Specific users",
  pauseCoupon: "Pause",
  activateCoupon: "Activate",
  archiveCoupon: "Archive",
  viewAnalytics: "Analytics",
  couponAnalytics: "Coupon analytics",
  redemptionCount: "Redemptions",
  discountTotal: "Discount cost",
  absorbedDiscounts: "Absorbed discounts",
  absorbedDiscountsSummary: "You absorbed ₹{amount} in discounts",
  bulkGenerate: "Bulk generate",
  bulkGenerateTitle: "Generate coupon batch",
  bulkBatchName: "Batch name",
  bulkCount: "Number of codes",
  bulkPrefix: "Code prefix",
  couponBatches: "Coupon batches",
  noCouponBatches: "No coupon batches yet",
  batchGeneratedCount: "Generated",
  vendorCoupons: "Vendor coupons",
  platformCoupons: "Platform coupons",
  allCoupons: "All coupons",
  vendorId: "Vendor",
  confirmPauseCouponTitle: "Pause this coupon?",
  confirmPauseCouponBody:
    '"{code}" will stop accepting new redemptions until reactivated.',
  confirmActivateCouponTitle: "Activate this coupon?",
  confirmActivateCouponBody:
    '"{code}" will become available for eligible carts.',
  confirmArchiveCouponTitle: "Archive this coupon?",
  confirmArchiveCouponBody: '"{code}" will be archived and no longer usable.',
  couponCodeRequired: "Code is required",
  couponCodeTooLong: "Code must be 64 characters or fewer",
  couponTypeRequired: "Type is required",
  couponValueNegative: "Value cannot be negative",
  couponMaxDiscountNegative: "Max discount cannot be negative",
  couponMinOrderNegative: "Min order value cannot be negative",
  couponStartDateRequired: "Start date is required",
  couponStartDateInvalid: "Start date is invalid",
  couponEndDateRequired: "End date is required",
  couponEndDateInvalid: "End date is invalid",
  couponValueRequired: "Value is required for this coupon type",
  couponPercentageMax: "Percentage value cannot exceed 100",
  couponEndAfterStart: "End date must be after start date",
  couponScopeTypeRequired: "Scope type is required",
  couponBearerRequired: "Discount bearer is required",
  couponBatchNameRequired: "Batch name is required",
  couponBulkCountInvalid: "Enter a count between 1 and 500",
  couponAppliedReview: "Coupon {code} applied (−{amount})",
  vendorTotal: "Vendor total",
  subtotal: "Subtotal",
  freeShipping: "Free",
  payableNow: "Payable now",
  includingShippingTaxes: "Including shipping and taxes",
  placeOrder: "Place order",
  paymentUnavailableTitle: "Payment unavailable",
  paymentUnavailableLoadScript:
    "Unable to load payment checkout. Please try again.",
  paymentUnavailableMissingDetails:
    "Payment could not be started. Missing order details from server.",
  paymentConfirmationPendingTitle: "Confirmation pending",
  paymentConfirmationPendingBody:
    "Payment was received, but confirmation is still settling. Check Orders shortly.",
  paymentCancelledTitle: "Payment cancelled",
  paymentCancelledBody:
    "No charge was made. Your cart has been restored and is ready whenever you want to try again.",
  paymentFailedTitle: "Payment failed",
  paymentFailedBody:
    "Payment could not be completed. Your cart has been restored so you can try again.",
  placeOrderFailedTitle: "Could not place order",
  placeOrderFailedBody: "Could not place order. Please try again.",
  itemsUnavailableTitle: "Items unavailable",
  backToPayment: "Back to payment",
  preparingSummary: "Preparing your summary",
  calculatingShippingTaxes: "Calculating shipping and taxes for your order…",
  summaryLoadFailed:
    "We couldn't calculate shipping and taxes. Go back to payment and try again.",
  couponCodeLabel: "Coupon code",
  yourCart: "Your Cart",
  closeCart: "Close cart",
  cartEmptyHeading: "Your cart is empty",
  cartEmptyMessage: "Add some items to get started.",
  checkout: "Checkout",
  viewFullCart: "View full cart",
  total: "Total",
} as const;
