/** Admin delivery/shipping panel table copy. Subset of LABELS; merged in labels/index.ts. */
export const deliveryAgentTablesLabels = {
  flagsStuckFor: "Stuck for",
  flagsFailedAttempts: "Failed attempts",
  documentTypeColumn: "Type",
  commissionStatement: "Statement",
  returnIdColumn: "Return ID",
  referenceReasonColumn: "Reference / reason",
  rtoColumn: "RTO",
  rtoRateColumn: "RTO rate",
  periodColumn: "Period",
  noteColumn: "Note",
  lastNoteColumn: "Last note",
  hubZoneColumn: "Hub/zone",
  failureReasonColumn: "Failure reason",
  expiryColumn: "Expiry",
  expectedColumn: "Expected",
  documentColumn: "Document",
  deliveredColumn: "Delivered",
  declaredColumn: "Declared",
  avgRatingColumn: "Avg. rating",
  avgFulfillmentColumn: "Avg. fulfillment",
  performancePanelTitle: "Agent delivery performance & metrics",
  performancePanelSubtitle:
    "Rollup of fulfillment speed, RTO rates, failed attempts, and customer satisfaction.",
  applyFilter: "Apply filter",
  loadingPerformanceReport: "Loading performance report…",
  noDeliveryActivity: "No delivery activity recorded in this date range.",
  flaggedBadge: "Flagged",
} as const;
