/** Copy subset (part 1); merged via labels.ts. */
export const reportsLabels = {
  groupType: "Group",
  state: "State",
  period: "Period",
  taxableValue: "Taxable Value",
  tcsCgst: "TCS CGST",
  tcsSgst: "TCS SGST",
  tcsIgst: "TCS IGST",
  tcsTotal: "TCS Total",
  section: "Section",
  grossTaxable: "Gross Taxable",
  tdsAmount: "TDS Amount",
  qty: "Quantity",
  taxable: "Taxable",
  cgst: "CGST",
  sgst: "SGST",
  igst: "IGST",
  taxTotal: "Tax Total",
  platformCommission: "Platform Commission",
  accountedTotal: "Accounted Total",
  difference: "Difference",
  type: "Type",
  noteNumber: "Note Number",
  orderId: "Order ID",
  taxAmount: "Tax Amount",
  issuedAt: "Issued At",
  payoutAmount: "Payout Amount",
  payoutPending: "Payout Pending",
  payoutPaid: "Payout Paid",
  payoutStatus: "Payout Status",
  categoryId: "Category ID",
  commission: "Commission",
  discountAmount: "Discount Amount",
  gmv: "GMV",
  actorId: "Actor ID",
  entityId: "Entity ID",
  metadata: "Metadata",
  subOrderId: "Sub-order ID",
  deliveredAt: "Delivered At",
  hoursToDeliver: "Hours to Deliver",
  level: "Level",
  cancelledAt: "Cancelled At",
  orderItemId: "Order Item ID",
  refundStatus: "Refund Status",
  turnaroundHours: "Turnaround Hours",
  resolvedAt: "Resolved At",
  productId: "Product ID",
  revenue: "Revenue",
  submittedAt: "Submitted At",
  decidedAt: "Decided At",
  approvedById: "Approved By",
  reviewCount: "Reviews",
  avgRating: "Avg Rating",
  netPayout: "Net Payout",
  invoiceId: "Invoice",
  payoutId: "Payout ID",
  paidAt: "Paid At",
  razorpayPayoutId: "Razorpay Payout ID",
  tcsAmount: "TCS Amount",
  sku: "SKU",
  stock: "Stock",
  lowStockAt: "Low Stock At",
  isLowStock: "Low Stock",
  valuation: "Valuation",
  updatedAt: "Updated At",
  orderStatus: "Order Status",
  subOrderStatus: "Sub-order Status",
  quantity: "Qty",
  paymentStatus: "Payment Status",
  subOrderCount: "Sub-orders",
  variantId: "Variant ID",
  downloadTaxInvoice: "Download tax invoice",
  downloadAllTaxInvoices: "Download all invoices (ZIP)",
  sellerFallback: "Seller",
  downloadCreditNote: "Download credit note",
  downloadDebitNote: "Download debit note",
  commissionInvoices: "Commission invoices",
  downloadCommissionInvoice: "Download invoice",
  noCommissionInvoicesYet: "No commission invoices yet",
  vendorGstin: "Vendor GSTIN",
  entryType: "Entry type",
  placeOfSupplyState: "Place of supply",
  againstInvoiceNumber: "Against invoice",
  exportOrderHistory: "Export order history",
  reportGstTcsSummary: "GST TCS summary (GSTR-8)",
  reportTds194oSummary: "Income tax TDS (194-O) summary",
  reportHsnSalesSummary: "HSN-wise sales summary",
  reportStateTaxCollection: "State-wise tax collection",
  reportReconciliation: "Reconciliation report",
  reportCreditDebitNoteRegister: "Credit / debit note register",
  reportVendorSettlement: "Vendor settlement report",
  reportCommissionRevenue: "Commission revenue report",
  reportCouponDiscountCost: "Coupon & discount cost",
  reportGmvSales: "GMV & sales report",
  reportAuditLog: "Audit log report",
  reportOrderSla: "Order status / SLA",
  reportCancellations: "Cancellation report",
  reportRefundReturn: "Refund / return report",
  reportStuckOrders: "Stuck orders",
  returnId: "Return ID",
  stuckSince: "Stuck since",
  hoursStuck: "Hours stuck",
  reportProductPerformance: "Product performance",
  reportCategoryPerformance: "Category performance",
  reportProductApprovalTat: "Product approval turnaround",
  reportReviewRatingSummary: "Review / rating summary",
  reportVendorSales: "Sales report",
  reportVendorGstSales: "GST-ready sales summary",
  reportVendorTcsCredit: "TCS credit statement",
  reportVendorTdsCertificate: "TDS certificate report",
  reportVendorPayoutStatement: "Settlement / payout statement",
  reportVendorCommissionDeducted: "Commission deducted",
  reportVendorDiscountCost: "Discount cost",
  reportVendorReturnRefund: "Return / refund report",
  reportVendorInventory: "Inventory / stock report",
  reportVendorFulfillmentSla: "Order fulfillment (SLA)",
  reportStaffOrders: "Order / sub-order report",
  reportStaffInventory: "Inventory report",
  reportCustomerOrderHistory: "Order history export",
  reportTaxInvoiceRegister: "Tax invoice register",
  reportB2bGstinSalesRegister: "B2B GSTIN sales register",
  reportGstr1Filing: "GSTR-1 filing export",
  reportGstr3bSummary: "GSTR-3B summary",
  reportPaymentGatewayReconciliation: "Payment gateway reconciliation",
  reportCodRemittance: "COD remittance",
  reportCustomerAnalytics: "Customer analytics",
  reportShippingLogistics: "Shipping & logistics",
  reportAbandonedCart: "Abandoned cart",
  reportSupportTicketSla: "Support ticket SLA",
  reportVendorKycCompliance: "Vendor KYC compliance",
  reportPlatformInventory: "Platform inventory snapshot",
  reportCustomerWalletStatement: "Wallet statement",
  taxInvoiceNumber: "Tax invoice no",
  taxInvoiceIssuedAt: "Tax invoice date",
  buyerGstin: "Buyer GSTIN",
  buyerName: "Buyer name",
  documentNumber: "Document no",
  documentDate: "Document date",
  recipientGstin: "Recipient GSTIN",
  line: "Line",
  paymentMethod: "Payment method",
  razorpayOrderId: "Razorpay order ID",
  razorpayPaymentId: "Razorpay payment ID",
  razorpayAmount: "Razorpay amount",
  pgCaptured: "Captured",
  pgRefunded: "Refunded",
  pgNet: "Net captured",
  walletUsed: "Wallet used",
  reconStatus: "Reconciliation status",
  reconStatusMatched: "Matched",
  reconStatusWalletSettled: "Wallet settled",
  reconStatusMissingPgRef: "Missing PG reference",
  reconStatusPending: "Pending",
  reconStatusFailed: "Failed",
  reconStatusRefunded: "Refunded",
  reconStatusNotApplicable: "Not applicable",
  reconStatusReview: "Review",
  codAmount: "COD amount",
  codCollected: "COD collected",
  codStatus: "COD status",
  userId: "User ID",
  email: "Email",
  name: "Name",
  orderCount: "Order count",
  totalSpent: "Total spent",
  firstOrderAt: "First order",
  lastOrderAt: "Last order",
  segment: "Segment",
  shippingCost: "Shipping cost",
  shippingCharged: "Shipping charged",
  carrier: "Carrier",
  shipmentStatus: "Shipment status",
  shippedAt: "Shipped at",
  cartId: "Cart ID",
  lastActivityAt: "Last activity",
  itemCount: "Item count",
  cartValue: "Cart value",
  ticketNumber: "Ticket no",
  category: "Category",
  priority: "Priority",
  firstResponseAt: "First response",
  firstResponseHours: "First response (hrs)",
  resolutionHours: "Resolution (hrs)",
  verifiedDocs: "Verified docs",
  pendingDocs: "Pending docs",
  rejectedDocs: "Rejected docs",
  complianceStatus: "Compliance status",
  balanceAfter: "Balance after",
  referenceType: "Reference type",
  referenceId: "Reference ID",
  description: "Description",
} as const;
