/** Report column headers (must match backend report keys). Subset of LABELS; merged in labels/index.ts. */
export const reportsLabels = {
  groupType: "Group",
  state: "State",
  period: "Period",
  taxableValue: "Taxable Value",
  tcsCgst: "TCS CGST",
  tcsSgst: "TCS SGST",
  tcsIgst: "TCS IGST",
  tcsTotal: "TCS Total",
  section: "Section",
  grossTaxable: "Gross Taxable",
  tdsAmount: "TDS Amount",
  qty: "Quantity",
  taxable: "Taxable",
  cgst: "CGST",
  sgst: "SGST",
  igst: "IGST",
  taxTotal: "Tax Total",
  platformCommission: "Platform Commission",
  accountedTotal: "Accounted Total",
  difference: "Difference",
  type: "Type",
  noteNumber: "Note Number",
  orderId: "Order ID",
  taxAmount: "Tax Amount",
  issuedAt: "Issued At",
  payoutAmount: "Payout Amount",
  payoutPending: "Payout Pending",
  payoutPaid: "Payout Paid",
  payoutStatus: "Payout Status",
  categoryId: "Category ID",
  commission: "Commission",
  discountAmount: "Discount Amount",
  gmv: "GMV",
  actorId: "Actor ID",
  entityId: "Entity ID",
  metadata: "Metadata",
  subOrderId: "Sub-order ID",
  deliveredAt: "Delivered At",
  hoursToDeliver: "Hours to Deliver",
  level: "Level",
  cancelledAt: "Cancelled At",
  orderItemId: "Order Item ID",
  refundStatus: "Refund Status",
  turnaroundHours: "Turnaround Hours",
  resolvedAt: "Resolved At",
  productId: "Product ID",
  revenue: "Revenue",
  submittedAt: "Submitted At",
  decidedAt: "Decided At",
  approvedById: "Approved By",
  reviewCount: "Reviews",
  avgRating: "Avg Rating",
  netPayout: "Net Payout",
  invoiceId: "Invoice",
  payoutId: "Payout ID",
  paidAt: "Paid At",
  razorpayPayoutId: "Razorpay Payout ID",
  tcsAmount: "TCS Amount",
  sku: "SKU",
  stock: "Stock",
  lowStockAt: "Low Stock At",
  isLowStock: "Low Stock",
  valuation: "Valuation",
  updatedAt: "Updated At",
  orderStatus: "Order Status",
  subOrderStatus: "Sub-order Status",
  quantity: "Qty",
  paymentStatus: "Payment Status",
  subOrderCount: "Sub-orders",
  variantId: "Variant ID",
  downloadTaxInvoice: "Download tax invoice",
  exportOrderHistory: "Export order history",
  reportGstTcsSummary: "GST TCS summary (GSTR-8)",
  reportTds194oSummary: "Income tax TDS (194-O) summary",
  reportHsnSalesSummary: "HSN-wise sales summary",
  reportStateTaxCollection: "State-wise tax collection",
  reportReconciliation: "Reconciliation report",
  reportCreditDebitNoteRegister: "Credit / debit note register",
  reportVendorSettlement: "Vendor settlement report",
  reportCommissionRevenue: "Commission revenue report",
  reportCouponDiscountCost: "Coupon & discount cost",
  reportGmvSales: "GMV & sales report",
  reportAuditLog: "Audit log report",
  reportOrderSla: "Order status / SLA",
  reportCancellations: "Cancellation report",
  reportRefundReturn: "Refund / return report",
  reportProductPerformance: "Product performance",
  reportCategoryPerformance: "Category performance",
  reportProductApprovalTat: "Product approval turnaround",
  reportReviewRatingSummary: "Review / rating summary",
  reportVendorSales: "Sales report",
  reportVendorGstSales: "GST-ready sales summary",
  reportVendorTcsCredit: "TCS credit statement",
  reportVendorTdsCertificate: "TDS certificate report",
  reportVendorPayoutStatement: "Settlement / payout statement",
  reportVendorCommissionDeducted: "Commission deducted",
  reportVendorDiscountCost: "Discount cost",
  reportVendorReturnRefund: "Return / refund report",
  reportVendorInventory: "Inventory / stock report",
  reportVendorFulfillmentSla: "Order fulfillment (SLA)",
  reportStaffOrders: "Order / sub-order report",
  reportStaffInventory: "Inventory report",
  reportCustomerOrderHistory: "Order history export",
  settlementReports: "Settlement reports",
  reportDateFrom: "From",
  reportDateTo: "To",
  reportLoad: "Load report",
  exportCsv: "Export CSV",
  exportPdf: "Export PDF",
  platformGmv: "GMV",
  customerPayments: "Customer payments",
  commissionEarned: "Commission earned",
  taxCollected: "Tax collected",
  tcsCollected: "TCS collected",
  shippingCollected: "Shipping collected",
  discountAbsorbedPlatform: "Discount absorbed (platform)",
  discountAbsorbedVendor: "Discount absorbed (vendor)",
  vendorNetPayouts: "Vendor net payouts",
  reconciliation: "Reconciliation",
  reconciliationBalanced: "Balanced",
  reconciliationMismatch: "Mismatch — totals do not reconcile",
  reconciliationDifference: "Difference",
  vendorSettlements: "Vendor settlements",
  grossSales: "Gross sales",
  discountsAbsorbed: "Discounts absorbed",
  commissionCharged: "Commission charged",
  pendingNet: "Pending net",
  settledNet: "Settled net",
  ownCouponDiscounts: "Own coupon discounts",
  platformCouponDiscounts: "Platform coupon discounts on my items",
  upcomingPayout: "Upcoming payout",
  historicalPayout: "Historical payout",
  noReportData: "No report data for this range.",
  couldNotLoadReport: "Could not load report.",
  autoApproveProducts: "Auto-approve products",
  autoApproveEnabled: "Enabled (auto-approve)",
  autoApproveDisabled: "Disabled (moderated)",
  defaultReturnWindow: "Default return window",
  freeShippingThreshold: "Free shipping threshold",
  returnShippingFee: "Return shipping fee",
  returnShippingFeeHint:
    "Deducted from customer refunds when the return reason does not refund original shipping (for example no longer needed).",
  vendorShopSettings: "Shop settings",
  vendorShopSettingsHint:
    "Configure how your shop appears and how returns affect your storefront. Leave return shipping fee blank to use the platform default.",
  vendorLogoUpload: "Shop logo",
  vendorBannerUpload: "Shop banner",
  vendorReturnShippingFeeClear: "Use platform default",
  couldNotLoadVendorShopSettings: "Could not load shop settings.",
  couldNotSaveVendorShopSettings: "Could not save shop settings.",
  vendorShopSettingsSaved: "Shop settings saved.",
  payoutCycle: "Payout cycle",
  payoutCycleWeekly: "Weekly",
  payoutCycleBiweekly: "Bi-weekly",
  payoutCycleMonthly: "Monthly",
  payoutCycleWeeklyLegacy: "Weekly (legacy)",
  supportEmail: "Support email",
  supportHours: "Support hours",
  saveSettings: "Save settings",
  settingsSaved: "Settings saved.",
  couldNotSaveSettings: "Could not save settings.",
  couldNotLoadSettings: "Could not load platform settings from the server.",
  settingsUnavailable: "Settings unavailable.",
  loadingPlatformSettings: "Loading platform settings…",
  addTaxRule: "Add tax rule",
  enterGstPercentage: "Enter a GST percentage to continue.",
  gstPercentage: "GST %",
  hsnOptional: "HSN (optional)",
  addShippingZone: "Add shipping zone",
  enterZoneName: "Enter a zone name to continue.",
  zoneName: "Zone name",
  decreaseValue: "Decrease value",
  increaseValue: "Increase value",
  pickDateTime: "Pick date & time",
  pickDate: "Pick date",
  previousMonth: "Previous month",
  nextMonth: "Next month",
  hour: "Hour",
  minute: "Minute",
  done: "Done",
  createCoupon: "Create coupon",
  couponValue: "Value",
  maxDiscountCap: "Max discount cap",
  minOrderValue: "Min order value",
  startDate: "Start date",
  endDate: "End date",
  couponTypePercentage: "Percentage",
  couponTypeFlat: "Flat amount",
  couponTypeFreeShipping: "Free shipping",
  couponTypeBogo: "Buy one get one",
  couponTypeTiered: "Tiered",
  couponTypeCashback: "Cashback",
  couponTypeBundle: "Bundle",
  daysShort: "days",
  completeCouponFields:
    "Add a code, type, start date, and end date to create a coupon.",
  fieldRequired: "Required",
  enterCouponCode: "Enter a coupon code.",
  enterCouponValue: "Enter a value for this coupon type.",
  enterCouponStartDate: "Choose a start date and time.",
  enterCouponEndDate: "Choose an end date and time after the start.",
  couponCreateHint: "Complete all required fields to create this coupon.",
  adminPanel: "Admin Panel",
  brandName: "Marketplace",
  menu: "Menu",
  closeMenu: "Close menu",
  home: "Home",
  search: "Search",
  cart: "Cart",
  wishlist: "Wishlist",
  myWishlist: "My Wishlist",
  moveToCart: "Move to cart",
  profile: "Profile",
  account: "Account",
  themeLight: "Light",
  themeDark: "Dark",
  openAccountMenu: "Open account menu",
  browseCategories: "Browse categories",
  remove: "Remove",
  removeNamed: "Remove {name}",
  removeNamedFromWishlist: "Remove {name} from wishlist",
  addAddress: "Add address",
  addressDefault: "Default",
  setDefaultShort: "Set default",
  details: "Details",
  view: "View",
  clear: "Clear",
  compareNow: "Compare now",
  backToTop: "Back to top",
  openChatSupport: "Open chat support",
  chatNeedHelpTitle: "Need help?",
  chatSupportMessage:
    "Chat support is available for orders, returns, and account questions.",
  cookieBannerMessage:
    "This site uses cookies to improve your experience. By continuing, you agree to our use of cookies.",
  manageCookiePreferences: "Manage preferences",
  acceptCookies: "Accept",
  dismiss: "Dismiss",
  shareThisProduct: "Share this product",
  share: "Share",
  copyLink: "Copy link",
  linkCopied: "Link copied",
  previousSlide: "Previous slide",
  nextSlide: "Next slide",
  productImageView: "{name} - view {index}",
  decreaseQuantity: "Decrease quantity",
  increaseQuantity: "Increase quantity",
  editQuantity: "Quantity {value}. Click to edit.",
  quantityField: "Quantity",
  minimumQuantityHint: "Minimum quantity is {min}.",
  maximumQuantityHint: "Maximum quantity is {max}.",
  onlyOneInStock: "Only 1 available in stock.",
  browse: "Browse",
  viewAll: "View all",
  shopByCategory: "Shop by category",
  noCategoriesYet: "No categories yet",
  browseProducts: "Browse products",
  quickAdd: "Quick add",
  homeYourBrowsing: "Your browsing",
  homeRecentlyViewed: "Recently viewed",
  homeCuratedMakers: "Curated makers",
  homeVendorSpotlight: "Vendor spotlight",
  homeKnownFor: "Known for {product}",
  homeBrowseAll: "Browse all",
  categoryDepartmentCount: "{count} departments",
  categoryExploreCollection: "Explore the full collection",
  categoryChildCountSingular: "{count} subcategory",
  categoryChildCountPlural: "{count} subcategories",
  digDeeper: "Dig deeper",
  subcategories: "Subcategories",
  shopInCategory: "Browse",
  shopAll: "Shop all",
  categoriesIndexHint:
    "Explore every collection on {site} — from makers and studios across the country.",
  categoryImageUnavailable: "{name} image not available",
  minPricePlaceholder: "Min",
  maxPricePlaceholder: "Max",
  minimumPrice: "Minimum price",
  maximumPrice: "Maximum price",
  help: "Help",
  productNamePlaceholder: "Product name",
  pricePlaceholder: "Price",
  shortDescription: "Short description",
  creatingEllipsis: "Creating…",
  deletingProductEllipsis: "Deleting this product…",
  createProduct: "Create product",
  moreCategoriesCount: "+{count} more",
  privacyPreferences: "Preferences",
  privacyAndData: "Privacy & data",
  appearance: "Appearance",
  appearanceHintCustomer:
    "Light or dark for the storefront. Saved on this device.",
  appearanceHintWorkspace:
    "Light or dark for the admin and vendor consoles. Saved on this device.",
  downloadMyData: "Download my data",
  downloadMyDataHintCustomer:
    "Export a JSON copy of your profile, addresses, orders, reviews, returns, and wishlist.",
  download: "Download",
  signOut: "Sign out",
  signOutHint: "End this session on this device.",
  signOutConfirmTitle: "Sign out?",
  signOutConfirmBody:
    "You'll need to sign in again to access your account on this device.",
  dangerZone: "Danger zone",
  deleteAccount: "Delete account",
  deleteAccountHintCustomer:
    "Permanently deactivate your account. This cannot be undone from the storefront.",
  deleteAccountHintWorkspace:
    "Permanently deactivate your account. This cannot be undone.",
  deleteAccountBody:
    "Your profile will be deactivated and you'll be signed out immediately.",
  deleteAccountConfirmTitle: "Delete your account?",
  deleteAccountConfirmBody:
    "Type DELETE to confirm. Your profile will be deactivated and you’ll be signed out.",
  confirmation: "Confirmation",
  couldNotExportAccount: "Could not export account data.",
  couldNotDeleteAccount: "Could not delete account.",
  phoneOptionalDelivery: "Optional — used for delivery updates.",
  phoneOptionalContact: "Optional — used for account recovery contact.",
  personalInfoFooterCustomer:
    "Keep your name, phone, and email current for orders and account recovery.",
  personalInfoFooterWorkspace:
    "Keep your name, phone, and email current for account recovery.",
  personalInfoSectionTitle: "Personal information",
  personalInfoSectionHint:
    "Update how we address you and how we can reach you.",
  personalInfoEyebrow: "Identity",
  personalInfoProfileEyebrow: "Profile",
  personalInfoProfileHint:
    "A quick view of the details currently tied to your account.",
  personalInfoAccountHolder: "Account holder",
  personalInfoEmailStatus: "Email status",
  personalInfoNoPhone: "No phone saved yet",
  personalInfoVerified: "Verified",
  personalInfoUnverified: "Unverified",
  personalInfoSaved: "Profile saved.",
  fullName: "Full name",
  phone: "Phone",
  phonePlaceholder: "+91…",
  nameRequired: "Name is required",
  saveChanges: "Save changes",
  couldNotSaveProfile: "Could not save profile.",
  couldNotLoadProfile: "Could not load your profile. Please try again.",
  newAddress: "New address",
  editAddress: "Edit address",
  addressFormHint: "All fields marked required must be filled.",
  addressLine1: "Address line 1",
  addressLine2Optional: "Address line 2 (optional)",
  addressLine1Placeholder: "House no., street, landmark",
  addressLine2Placeholder: "Apartment, suite, floor",
  addressCity: "City",
  addressState: "State",
  addressPincode: "Pincode",
  addressCountry: "Country",
  addressSetDefault: "Set as default address",
  addressRequiredFields: "Please fill all required fields.",
  enterAddressLine1: "Enter address line 1 to continue.",
  enterAddressCity: "Enter a city to continue.",
  enterAddressState: "Enter a state to continue.",
  enterAddressPincode: "Enter a pincode to continue.",
  saveAddress: "Save address",
  couldNotSaveAddress: "Could not save address.",
  addressFormSection: "Address details",
  addressFormSectionHint: "Delivery location used at checkout.",
  defaultCountry: "India",
  helpContactSection: "Contact details",
  helpContactSectionHint:
    "Tell us how to reach you and what you need help with.",
  helpContactMessageSection: "Message",
  helpContactMessageSectionHint: "Include enough detail for us to investigate.",
  reviewFormSection: "Your review",
  reviewFormSectionHint: "Rating and comments for this product.",
  reviewingProduct: "Reviewing: {name}",
  reviewTitleOptional: "Title (optional)",
  reviewTitlePlaceholder: "Summarize your experience",
  reviewBody: "Review",
  reviewBodyPlaceholder: "What did you think?",
  selectReviewRating: "Select a star rating to continue.",
  enterReviewBody: "Enter a review of at least 10 characters.",
  enterFullName: "Enter your full name to continue.",
  enterProductName: "Enter a product name to continue.",
  enterProductPrice: "Enter a price to continue.",
  selectProductCategory: "Select a category to continue.",
  enterBusinessName: "Enter a business name to continue.",
  selectVendorEntityType: "Select an entity type to continue.",
  selectVendorCategories: "Select at least one category to continue.",
  submitReview: "Submit review",
  returnRequestFormSection: "Return details",
  returnRequestFormSectionHint: "Reason, notes, and optional photos.",
  attributeFormSection: "Attribute",
  attributeFormSectionHint: "Name, type, and options for category filters.",
  bulkCouponMetaSection: "Batch settings",
  bulkCouponMetaSectionHint:
    "Name, count, and code prefix for generated coupons.",
  emailFixedStorefront:
    "Email addresses are fixed on this account and cannot be changed from the storefront.",
  emailFixedWorkspace:
    "Email addresses are fixed on this account and cannot be changed here.",
  accountSettingsHintCustomer:
    "Manage your profile, security, addresses, and preferences — quietly, clearly.",
  accountSettingsHintWorkspace:
    "Manage your profile, security, and preferences — quietly, clearly.",
  privacyAndDataHintCustomer:
    "Control appearance on this device, export your data, or end your session.",
  privacyAndDataHintWorkspace:
    "Control appearance on this device or end your session.",
  privacySectionDescCustomer: "Data and account deletion",
  privacySectionDescWorkspace: "Appearance, sign out, and account deletion",

  // Wallet
} as const;
