/** Copy subset (part 2); merged via labels.ts. */
export const reports2Labels = {
  couponTypeTiered: "Tiered",
  couponTypeCashback: "Cashback",
  couponTypeBundle: "Bundle",
  daysShort: "days",
  completeCouponFields:
    "Add a code, type, start date, and end date to create a coupon.",
  fieldRequired: "Required",
  enterCouponCode: "Enter a coupon code.",
  enterCouponValue: "Enter a value for this coupon type.",
  enterCouponStartDate: "Choose a start date and time.",
  enterCouponEndDate: "Choose an end date and time after the start.",
  couponCreateHint: "Complete all required fields to create this coupon.",
  adminPanel: "Admin Panel",
  brandName: "Marketplace",
  menu: "Menu",
  closeMenu: "Close menu",
  home: "Home",
  search: "Search",
  cart: "Cart",
  wishlist: "Wishlist",
  myWishlist: "My Wishlist",
  moveToCart: "Move to cart",
  profile: "Profile",
  account: "Account",
  themeLight: "Light",
  themeDark: "Dark",
  openAccountMenu: "Open account menu",
  browseCategories: "Browse categories",
  remove: "Remove",
  removeNamed: "Remove {name}",
  removeNamedFromWishlist: "Remove {name} from wishlist",
  addAddress: "Add address",
  addressDefault: "Default",
  setDefaultShort: "Set default",
  details: "Details",
  view: "View",
  clear: "Clear",
  compareNow: "Compare now",
  backToTop: "Back to top",
  openChatSupport: "Open chat support",
  chatNeedHelpTitle: "Need help?",
  chatSupportMessage:
    "Chat support is available for orders, returns, and account questions.",
  cookieBannerMessage:
    "This site uses cookies to improve your experience. By continuing, you agree to our use of cookies.",
  manageCookiePreferences: "Manage preferences",
  acceptCookies: "Accept",
  dismiss: "Dismiss",
  shareThisProduct: "Share this product",
  share: "Share",
  copyLink: "Copy link",
  linkCopied: "Link copied",
  previousSlide: "Previous slide",
  nextSlide: "Next slide",
  productImageView: "{name} - view {index}",
  decreaseQuantity: "Decrease quantity",
  increaseQuantity: "Increase quantity",
  editQuantity: "Quantity {value}. Click to edit.",
  quantityField: "Quantity",
  minimumQuantityHint: "Minimum quantity is {min}.",
  maximumQuantityHint: "Maximum quantity is {max}.",
  onlyOneInStock: "Only 1 available in stock.",
  browse: "Browse",
  viewAll: "View all",
  shopByCategory: "Shop by category",
  noCategoriesYet: "No categories yet",
  browseProducts: "Browse products",
  quickAdd: "Quick add",
  homeYourBrowsing: "Your browsing",
  homeRecentlyViewed: "Recently viewed",
  homeCuratedMakers: "Curated makers",
  homeVendorSpotlight: "Vendor spotlight",
  homeKnownFor: "Known for {product}",
  homeBrowseAll: "Browse all",
  categoryDepartmentCount: "{count} departments",
  categoryExploreCollection: "Explore the full collection",
  categoryChildCountSingular: "{count} subcategory",
  categoryChildCountPlural: "{count} subcategories",
  digDeeper: "Dig deeper",
  subcategories: "Subcategories",
  shopInCategory: "Browse",
  shopAll: "Shop all",
  categoriesIndexHint:
    "Explore every collection on {site} — from makers and studios across the country.",
  categoryImageUnavailable: "{name} image not available",
  minPricePlaceholder: "Min",
  maxPricePlaceholder: "Max",
  minimumPrice: "Minimum price",
  maximumPrice: "Maximum price",
  help: "Help",
  productNamePlaceholder: "Product name",
  pricePlaceholder: "Price",
  shortDescription: "Short description",
  creatingEllipsis: "Creating…",
  deletingProductEllipsis: "Deleting this product…",
  createProduct: "Create product",
  moreCategoriesCount: "+{count} more",
  privacyPreferences: "Preferences",
  privacyAndData: "Privacy & data",
  appearance: "Appearance",
  appearanceHintCustomer:
    "Light or dark for the storefront. Saved on this device.",
  appearanceHintWorkspace:
    "Light or dark for the admin and vendor consoles. Saved on this device.",
  downloadMyData: "Download my data",
  downloadMyDataHintCustomer:
    "Export a JSON copy of your profile, addresses, orders, reviews, returns, and wishlist.",
  download: "Download",
  signOut: "Sign out",
  signOutHint: "End this session on this device.",
  signOutConfirmTitle: "Sign out?",
  signOutConfirmBody:
    "You'll need to sign in again to access your account on this device.",
  dangerZone: "Danger zone",
  deleteAccount: "Delete account",
  deleteAccountHintCustomer:
    "Permanently deactivate your account. This cannot be undone from the storefront.",
  deleteAccountHintWorkspace:
    "Permanently deactivate your account. This cannot be undone.",
  deleteAccountBody:
    "Your profile will be deactivated and you'll be signed out immediately.",
  deleteAccountConfirmTitle: "Delete your account?",
  deleteAccountConfirmBody:
    "Type DELETE to confirm. Your profile will be deactivated and you’ll be signed out.",
  confirmation: "Confirmation",
  couldNotExportAccount: "Could not export account data.",
  couldNotDeleteAccount: "Could not delete account.",
  phoneOptionalDelivery: "Optional — used for delivery updates.",
  phoneOptionalContact: "Optional — used for account recovery contact.",
  personalInfoFooterCustomer:
    "Keep your name, phone, and email current for orders and account recovery.",
  personalInfoFooterWorkspace:
    "Keep your name, phone, and email current for account recovery.",
  personalInfoSectionTitle: "Personal information",
  personalInfoSectionHint:
    "Update how we address you and how we can reach you.",
  personalInfoEyebrow: "Identity",
  personalInfoProfileEyebrow: "Profile",
  personalInfoProfileHint:
    "A quick view of the details currently tied to your account.",
  personalInfoAccountHolder: "Account holder",
  personalInfoEmailStatus: "Email status",
  personalInfoNoPhone: "No phone saved yet",
  personalInfoVerified: "Verified",
  personalInfoUnverified: "Unverified",
  memberSince: "Member since {date}",
  personalInfoSaved: "Profile saved.",
  fullName: "Full name",
  phone: "Phone",
  phonePlaceholder: "+91…",
  nameRequired: "Name is required",
  saveChanges: "Save changes",
  couldNotSaveProfile: "Could not save profile.",
  couldNotLoadProfile: "Could not load your profile. Please try again.",
  newAddress: "New address",
  editAddress: "Edit address",
  addressFormHint: "All fields marked required must be filled.",
  addressLine1: "Address line 1",
  addressLine2Optional: "Address line 2 (optional)",
  addressLine1Placeholder: "House no., street, landmark",
  addressLine2Placeholder: "Apartment, suite, floor",
  addressCity: "City",
  addressState: "State",
  addressPincode: "Pincode",
  addressCountry: "Country",
  addressSetDefault: "Set as default address",
  addressRequiredFields: "Please fill all required fields.",
  enterAddressLine1: "Enter address line 1 to continue.",
  enterAddressCity: "Enter a city to continue.",
  enterAddressState: "Enter a state to continue.",
  enterAddressPincode: "Enter a pincode to continue.",
  saveAddress: "Save address",
  couldNotSaveAddress: "Could not save address.",
  deliveryAgentPerTaskEarning: "Delivery agent earning per task",
  deliveryAgentPerTaskEarningHint:
    "Flat estimate shown on the agent's shift summary per completed delivery or pickup.",
  addressFormSection: "Address details",
  addressFormSectionHint: "Delivery location used at checkout.",
  addressLocationRequired: "Location access is required to save an address.",
  addressLocationFetching: "Fetching your location...",
  addressLocationDenied:
    "Location access was denied. Enable it in your browser settings and retry.",
  addressLocationUnsupported: "Your browser doesn't support location access.",
  addressLocationError: "Could not fetch your location. Please retry.",
  addressLocationRetry: "Retry",
  addressDeliveryInstructionsOptional: "Delivery instructions (optional)",
  addressDeliveryInstructionsPlaceholder:
    "E.g. Leave at front desk, gate code, call on arrival",
  defaultCountry: "India",
  helpContactSection: "Contact details",
  helpContactSectionHint:
    "Tell us how to reach you and what you need help with.",
  helpContactMessageSection: "Message",
  helpContactMessageSectionHint: "Include enough detail for us to investigate.",
  enterFullName: "Enter your full name to continue.",
} as const;
