/** Copy subset (part 1); merged via labels.ts. */
export const reportsLabels = {
  groupType: "Group",
  state: "State",
  period: "Period",
  taxableValue: "Taxable Value",
  tcsCgst: "TCS CGST",
  tcsSgst: "TCS SGST",
  tcsIgst: "TCS IGST",
  tcsTotal: "TCS Total",
  section: "Section",
  grossTaxable: "Gross Taxable",
  tdsAmount: "TDS Amount",
  qty: "Quantity",
  taxable: "Taxable",
  cgst: "CGST",
  sgst: "SGST",
  igst: "IGST",
  taxTotal: "Tax Total",
  platformCommission: "Platform Commission",
  accountedTotal: "Accounted Total",
  difference: "Difference",
  type: "Type",
  noteNumber: "Note Number",
  orderId: "Order ID",
  taxAmount: "Tax Amount",
  issuedAt: "Issued At",
  payoutAmount: "Payout Amount",
  payoutPending: "Payout Pending",
  payoutPaid: "Payout Paid",
  payoutStatus: "Payout Status",
  categoryId: "Category ID",
  commission: "Commission",
  discountAmount: "Discount Amount",
  gmv: "GMV",
  actorId: "Actor ID",
  entityId: "Entity ID",
  metadata: "Metadata",
  subOrderId: "Sub-order ID",
  deliveredAt: "Delivered At",
  hoursToDeliver: "Hours to Deliver",
  level: "Level",
  cancelledAt: "Cancelled At",
  orderItemId: "Order Item ID",
  refundStatus: "Refund Status",
  turnaroundHours: "Turnaround Hours",
  resolvedAt: "Resolved At",
  productId: "Product ID",
  revenue: "Revenue",
  submittedAt: "Submitted At",
  decidedAt: "Decided At",
  approvedById: "Approved By",
  reviewCount: "Reviews",
  avgRating: "Avg Rating",
  netPayout: "Net Payout",
  invoiceId: "Invoice",
  payoutId: "Payout ID",
  paidAt: "Paid At",
  razorpayPayoutId: "Razorpay Payout ID",
  tcsAmount: "TCS Amount",
  sku: "SKU",
  stock: "Stock",
  lowStockAt: "Low Stock At",
  isLowStock: "Low Stock",
  valuation: "Valuation",
  updatedAt: "Updated At",
  orderStatus: "Order Status",
  subOrderStatus: "Sub-order Status",
  quantity: "Qty",
  paymentStatus: "Payment Status",
  subOrderCount: "Sub-orders",
  variantId: "Variant ID",
  downloadTaxInvoice: "Download tax invoice",
  downloadAllTaxInvoices: "Download all invoices (ZIP)",
  sellerFallback: "Seller",
  exportOrderHistory: "Export order history",
  reportGstTcsSummary: "GST TCS summary (GSTR-8)",
  reportTds194oSummary: "Income tax TDS (194-O) summary",
  reportHsnSalesSummary: "HSN-wise sales summary",
  reportStateTaxCollection: "State-wise tax collection",
  reportReconciliation: "Reconciliation report",
  reportCreditDebitNoteRegister: "Credit / debit note register",
  reportVendorSettlement: "Vendor settlement report",
  reportCommissionRevenue: "Commission revenue report",
  reportCouponDiscountCost: "Coupon & discount cost",
  reportGmvSales: "GMV & sales report",
  reportAuditLog: "Audit log report",
  reportOrderSla: "Order status / SLA",
  reportCancellations: "Cancellation report",
  reportRefundReturn: "Refund / return report",
  reportProductPerformance: "Product performance",
  reportCategoryPerformance: "Category performance",
  reportProductApprovalTat: "Product approval turnaround",
  reportReviewRatingSummary: "Review / rating summary",
  reportVendorSales: "Sales report",
  reportVendorGstSales: "GST-ready sales summary",
  reportVendorTcsCredit: "TCS credit statement",
  reportVendorTdsCertificate: "TDS certificate report",
  reportVendorPayoutStatement: "Settlement / payout statement",
  reportVendorCommissionDeducted: "Commission deducted",
  reportVendorDiscountCost: "Discount cost",
  reportVendorReturnRefund: "Return / refund report",
  reportVendorInventory: "Inventory / stock report",
  reportVendorFulfillmentSla: "Order fulfillment (SLA)",
  reportStaffOrders: "Order / sub-order report",
  reportStaffInventory: "Inventory report",
  reportCustomerOrderHistory: "Order history export",
  settlementReports: "Settlement reports",
  reportDateFrom: "From",
  reportDateTo: "To",
  reportLoad: "Load report",
  exportCsv: "Export CSV",
  exportPdf: "Export PDF",
  platformGmv: "GMV",
  customerPayments: "Customer payments",
  commissionEarned: "Commission earned",
  taxCollected: "Tax collected",
  tcsCollected: "TCS collected",
  shippingCollected: "Shipping collected",
  discountAbsorbedPlatform: "Discount absorbed (platform)",
  discountAbsorbedVendor: "Discount absorbed (vendor)",
  vendorNetPayouts: "Vendor net payouts",
  reconciliation: "Reconciliation",
  reconciliationBalanced: "Balanced",
  reconciliationMismatch: "Mismatch — totals do not reconcile",
  reconciliationDifference: "Difference",
  vendorSettlements: "Vendor settlements",
  grossSales: "Gross sales",
  discountsAbsorbed: "Discounts absorbed",
  commissionCharged: "Commission charged",
  pendingNet: "Pending net",
  settledNet: "Settled net",
  ownCouponDiscounts: "Own coupon discounts",
  platformCouponDiscounts: "Platform coupon discounts on my items",
  upcomingPayout: "Upcoming payout",
  historicalPayout: "Historical payout",
  noReportData: "No report data for this range.",
  couldNotLoadReport: "Could not load report.",
  autoApproveProducts: "Auto-approve products",
  autoApproveEnabled: "Enabled (auto-approve)",
  autoApproveDisabled: "Disabled (moderated)",
  defaultReturnWindow: "Default return window",
  freeShippingThreshold: "Free shipping threshold",
  returnShippingFee: "Return shipping fee",
  returnShippingFeeHint:
    "Deducted from customer refunds when the return reason does not refund original shipping (for example no longer needed).",
  vendorShopSettings: "Shop settings",
  vendorShopSettingsHint:
    "Configure how your shop appears and how returns affect your storefront. Leave return shipping fee blank to use the platform default.",
  vendorLogoUpload: "Shop logo",
  vendorBannerUpload: "Shop banner",
  vendorReturnShippingFeeClear: "Use platform default",
  couldNotLoadVendorShopSettings: "Could not load shop settings.",
  couldNotSaveVendorShopSettings: "Could not save shop settings.",
  vendorShopSettingsSaved: "Shop settings saved.",
  payoutCycle: "Payout cycle",
  payoutCycleWeekly: "Weekly",
  payoutCycleBiweekly: "Bi-weekly",
  payoutCycleMonthly: "Monthly",
  payoutCycleWeeklyLegacy: "Weekly (legacy)",
  supportEmail: "Support email",
  supportHours: "Support hours",
  saveSettings: "Save settings",
  settingsSaved: "Settings saved.",
  couldNotSaveSettings: "Could not save settings.",
  couldNotLoadSettings: "Could not load platform settings from the server.",
  settingsUnavailable: "Settings unavailable.",
  loadingPlatformSettings: "Loading platform settings…",
  addTaxRule: "Add tax rule",
  enterGstPercentage: "Enter a GST percentage to continue.",
  gstPercentage: "GST %",
  hsnOptional: "HSN (optional)",
  addShippingZone: "Add shipping zone",
  enterZoneName: "Enter a zone name to continue.",
  zoneName: "Zone name",
  decreaseValue: "Decrease value",
  increaseValue: "Increase value",
  pickDateTime: "Pick date & time",
  pickDate: "Pick date",
  previousMonth: "Previous month",
  nextMonth: "Next month",
  hour: "Hour",
  minute: "Minute",
  done: "Done",
  createCoupon: "Create coupon",
  couponValue: "Value",
  maxDiscountCap: "Max discount cap",
  minOrderValue: "Min order value",
  startDate: "Start date",
  endDate: "End date",
  couponTypePercentage: "Percentage",
  couponTypeFlat: "Flat amount",
  couponTypeFreeShipping: "Free shipping",
  couponTypeBogo: "Buy one get one",
} as const;
