/** Copy subset (part 3); merged via labels.ts. */
export const reports3Labels = {
  reviewFormSection: "Your review",
  reviewFormSectionHint: "Rating and comments for this product.",
  reviewingProduct: "Reviewing: {name}",
  reviewTitleOptional: "Title (optional)",
  reviewTitlePlaceholder: "Summarize your experience",
  reviewBody: "Review",
  reviewBodyPlaceholder: "What did you think?",
  selectReviewRating: "Select a star rating to continue.",
  enterReviewBody: "Enter a review of at least 10 characters.",
  enterProductName: "Enter a product name to continue.",
  enterProductPrice: "Enter a price to continue.",
  selectProductCategory: "Select a category to continue.",
  enterBusinessName: "Enter a business name to continue.",
  selectVendorEntityType: "Select an entity type to continue.",
  selectVendorCategories: "Select at least one category to continue.",
  submitReview: "Submit review",
  couldNotSubmitReview: "Could not submit your review. Please try again.",
  returnRequestFormSection: "Return details",
  returnRequestFormSectionHint: "Reason, notes, and optional photos.",
  attributeFormSection: "Attribute",
  attributeFormSectionHint: "Name, type, and options for category filters.",
  bulkCouponMetaSection: "Batch settings",
  bulkCouponMetaSectionHint:
    "Name, count, and code prefix for generated coupons.",
  emailFixedStorefront:
    "Email addresses are fixed on this account and cannot be changed from the storefront.",
  emailFixedWorkspace:
    "Email addresses are fixed on this account and cannot be changed here.",
  accountSettingsHintCustomer:
    "Manage your profile, security, addresses, and preferences — quietly, clearly.",
  accountSettingsHintWorkspace:
    "Manage your profile, security, and preferences — quietly, clearly.",
  privacyAndDataHintCustomer:
    "Control appearance on this device, export your data, or end your session.",
  privacyAndDataHintWorkspace:
    "Control appearance on this device or end your session.",
  privacySectionDescCustomer: "Data and account deletion",
  privacySectionDescWorkspace: "Appearance, sign out, and account deletion",
  noPayoutsYet: "No payouts yet",
  editShippingZoneTitle: "Edit shipping zone",
  editShippingZoneBody: "Update the zone name, states, and pincode prefixes.",
  zoneStatesHint: "Comma-separated state names. Leave blank if unused.",
  zonePincodePrefixesHint:
    "Comma-separated pincode prefixes. Leave blank if unused.",
  runCouponAlerts: "Send coupon alerts",
  couponAlertsSent: "Sent {count} coupon expiry and usage alerts.",
  couponAlertsNoneSent: "No coupon alerts needed right now.",
  couponAlertsFailed: "Could not send coupon alerts.",
  yourOrders: "Your Orders",
  ordersPageHint:
    "Track each seller's package separately — multi-vendor orders ship on their own timelines.",
  ordersColumnOrder: "Order",
  ordersColumnPlaced: "Placed",
  ordersColumnItems: "Items",
  ordersColumnTotal: "Total",
  ordersColumnStatus: "Status",
  ordersColumnOpen: "Open",
  orderHistoryStatement: "Order history statement",
  loadOrderHistory: "Load statement",

  // Wallet / reconciliation
  exportAnalytics: "Export analytics",
  exportWalletStatement: "Export statement",
  walletStatement: "Wallet statement",
  exportAuditLog: "Export audit log",
  auditLogExportHint: "Download audit entries for the selected date range.",
  reportVendorPayoutReconciliation: "Vendor payout reconciliation",
  reportNewsletterSubscribers: "Newsletter subscribers",
  exportVendorSettlements: "Export vendor settlements",
  exportReconciliation: "Export reconciliation",
  subscribedAt: "Subscribed at",
  settlementReports: "Settlement reports",
  reportDateFrom: "From",
  reportDateTo: "To",
  reportLoad: "Load report",
  exportCsv: "Export CSV",
  exportPdf: "Export PDF",
  platformGmv: "GMV",
  customerPayments: "Customer payments",
  commissionEarned: "Commission earned",
  taxCollected: "Tax collected",
  tcsCollected: "TCS collected",
  shippingCollected: "Shipping collected",
  discountAbsorbedPlatform: "Discount absorbed (platform)",
  discountAbsorbedVendor: "Discount absorbed (vendor)",
  vendorNetPayouts: "Vendor net payouts",
  reconciliation: "Reconciliation",
  reconciliationBalanced: "Balanced",
  reconciliationMismatch: "Mismatch — totals do not reconcile",
  reconciliationDifference: "Difference",
  walletRechargeInflow: "Wallet recharge inflow",
  walletPointsRedeemedAtCheckout: "Points redeemed at checkout",
  vendorSettlements: "Vendor settlements",
  grossSales: "Gross sales",
  discountsAbsorbed: "Discounts absorbed",
  commissionCharged: "Commission charged",
  pendingNet: "Pending net",
  settledNet: "Settled net",
  ownCouponDiscounts: "Own coupon discounts",
  platformCouponDiscounts: "Platform coupon discounts on my items",
  upcomingPayout: "Upcoming payout",
  historicalPayout: "Historical payout",
  noReportData: "No report data for this range.",
  couldNotLoadReport: "Could not load report.",

  // Settings (platform / vendor shop / tax / shipping zones)
  autoApproveProducts: "Auto-approve products",
  autoApproveEnabled: "Enabled (auto-approve)",
  autoApproveDisabled: "Disabled (moderated)",
  defaultReturnWindow: "Default return window",
  freeShippingThreshold: "Free shipping threshold",
  returnShippingFee: "Return shipping fee",
  returnShippingFeeHint:
    "Deducted from customer refunds when the return reason does not refund original shipping (for example no longer needed).",
  vendorShopSettings: "Shop settings",
  vendorShopSettingsHint:
    "Configure how your shop appears and how returns affect your storefront. Leave return shipping fee blank to use the platform default.",
  vendorLogoUpload: "Shop logo",
  vendorBannerUpload: "Shop banner",
  vendorReturnShippingFeeClear: "Use platform default",
  couldNotLoadVendorShopSettings: "Could not load shop settings.",
  couldNotSaveVendorShopSettings: "Could not save shop settings.",
  vendorShopSettingsSaved: "Shop settings saved.",
  payoutCycle: "Payout cycle",
  payoutCycleWeekly: "Weekly",
  payoutCycleBiweekly: "Bi-weekly",
  payoutCycleMonthly: "Monthly",
  payoutCycleWeeklyLegacy: "Weekly (legacy)",
  supportEmail: "Support email",
  supportHours: "Support hours",
  saveSettings: "Save settings",
  settingsSaved: "Settings saved.",
  couldNotSaveSettings: "Could not save settings.",
  couldNotLoadSettings: "Could not load platform settings from the server.",
  settingsUnavailable: "Settings unavailable.",
  loadingPlatformSettings: "Loading platform settings…",
  addTaxRule: "Add tax rule",
  enterGstPercentage: "Enter a GST percentage to continue.",
  gstPercentage: "GST %",
  hsnOptional: "HSN (optional)",
  addShippingZone: "Add shipping zone",
  enterZoneName: "Enter a zone name to continue.",
  zoneName: "Zone name",
  decreaseValue: "Decrease value",
  increaseValue: "Increase value",
  pickDateTime: "Pick date & time",
  pickDate: "Pick date",
  previousMonth: "Previous month",
  nextMonth: "Next month",
  hour: "Hour",
  minute: "Minute",
  done: "Done",
  createCoupon: "Create coupon",
  couldNotCreateCoupon: "Could not create coupon. Please try again.",
  couldNotCreateShippingZone: "Could not create shipping zone.",
  couldNotCreateTaxRule: "Could not create tax rule.",
  couponValue: "Value",
  maxDiscountCap: "Max discount cap",
  minOrderValue: "Min order value",
  startDate: "Start date",
  endDate: "End date",
  couponTypePercentage: "Percentage",
  couponTypeFlat: "Flat amount",
  couponTypeFreeShipping: "Free shipping",
  couponTypeBogo: "Buy one get one",
} as const;
