/** Table and pagination copy (part 3); merged via labels.ts. */
export const tables3Labels = {
  addProduct: "Add product",
  createProductBody:
    "Add a new product to your catalog. Upload images during creation or manage them later.",
  editProductTitle: "Edit product",
  editProductBody:
    "Update listing details, policies, and search settings for this product.",
  productBrandPlaceholder: "Brand name",
  productTagsHint: "Separate tags with commas.",
  productTagsPlaceholder: "cookware, steel, induction",
  addProductHighlight: "Add highlight",
  addProductSpecification: "Add specification",
  productSpecKey: "Label",
  productSpecValue: "Value",
  productDeliveryNote: "Delivery note",
  productReturnNote: "Return note",
  productDeliveryNoteHint:
    "Optional. Shown under the free-delivery policy on the product page.",
  productReturnNoteHint:
    "Optional. Shown under the returns policy on the product page.",
  productWarrantyMonths: "Warranty (months)",
  productWarrantyMonthsHint: "Leave blank to inherit the category default.",
  enterWarrantyMonths:
    "Enter warranty months from 0 to {max}, or leave blank to inherit.",
  productMediaUrlInvalid: "Enter a valid media URL or upload a file.",
  productWarrantyType: "Warranty type",
  productHsnCode: "HSN code",
  productHsnCodeHint:
    "Optional display override. Tax still follows category tax rules.",
  productSeoTitle: "SEO title",
  productSeoDescription: "SEO description",
  productVideoUrl: "Product video",
  productSizeChart: "Size chart",
  productCodEnabled: "Cash on delivery",
  productCodInherit: "Inherit from category and seller",
  productCodOn: "Allow COD",
  productCodOff: "Do not allow COD",
  inheritDefault: "Inherit default",
  categoryReturnWindowDays: "Return window (days)",
  categoryReturnWindowHint:
    "Blank inherits the parent, then the platform default. 0 means not returnable.",
  categoryCodEnabled: "Allow cash on delivery",
  categoryDefaultWarrantyMonths: "Default warranty (months)",
  categoryDefaultWarrantyType: "Default warranty type",
  categoryFormSectionPolicies: "Returns, COD & warranty",
  categoryFormSectionPoliciesHint:
    "Category defaults used on product pages when a listing does not override them.",
  settingsCod: "Cash on delivery",
  settingsCodHint:
    "Platform COD switch and order-value limits. Category, seller, and product flags must also allow COD.",
  settingsCodEnabled: "Enable cash on delivery",
  settingsCodMinOrder: "COD minimum order value",
  settingsCodMaxOrder: "COD maximum order value",
  vendorCodEnabled: "Accept cash on delivery",
  vendorCodEnabledHint:
    "Turn off to disable COD for every product from this shop.",
  productMrpHint: "Optional. Must be at least the selling price.",
  productFieldTooLong: "Must be {max} characters or fewer.",
  productListTooLong: "You can add at most {max} items.",
  productSpecPairRequired: "Each specification needs both a label and a value.",
  productSpecDuplicateKey: "Specification labels must be unique.",
  productCompareAtBelowPrice:
    "MRP must be greater than or equal to the selling price.",
  enterProductDescription: "Enter a product description to continue.",
  enterProductCompareAtPrice: "Enter a valid MRP or leave it blank.",
  enterProductHighlight: "Enter highlight text or remove the empty row.",
  editPromoBanner: "Edit banner",
  savePromoBanner: "Save banner",
  confirmDeleteVendorTitle: "Delete vendor?",
  confirmDeleteVendorBody:
    'Delete "{name}" and all associated media? This cannot be undone.',
  confirmDeleteReturnTitle: "Delete return?",
  confirmDeleteReturnBody:
    'Delete return for "{name}" and its photos? This cannot be undone.',
  categoryStatus: "Status",
  categoryStatusActive: "Active",
  categoryStatusArchived: "Archived",
  categorySeoTitle: "SEO title",
  categorySeoDescription: "SEO description",
  categoryCommissionRate: "Category commission %",
  categoryCommissionRateHint:
    "Optional override; leaves inherit from parents, then vendor default.",
  categoryCommissionPlaceholder: "0–100",
  categoryAttributes: "Filter attributes",
  categoryAttributesHint:
    "Define category-specific filters (Material, Size, etc.).",
  addCategoryAttribute: "Add attribute",
  attributeName: "Attribute name",
  attributeType: "Attribute type",
  attributeOptions: "Options (comma-separated)",
  attributeTypeEnum: "Enum",
  attributeTypeRange: "Range",
  attributeTypeBoolean: "Boolean",
  manageAttributes: "Attributes",
  editCategoryAttribute: "Edit attribute",
  saveCategoryAttribute: "Save attribute",
  cancelEditAttribute: "Cancel",
  couldNotReorderAttributes: "Could not save attribute order.",
  couldNotSaveAttribute: "Could not save attribute.",
  couldNotDeleteAttribute: "Could not delete attribute.",
  deleteCategoryAttribute: "Delete attribute",
  reassignProducts: "Reassign products",
  reassignProductsTitle: "Bulk reassign products",
  reassignProductsBody: "Move all products from one category to another.",
  reassignFrom: "From category",
  reassignTo: "To category",
  reassignConfirm: "Reassign",
  selectCategory: "Select category",
  archiveCategory: "Archive",
  reactivateCategory: "Reactivate",
  confirmArchiveCategoryTitle: "Archive this category?",
  confirmArchiveCategoryBody:
    'Archive "{name}"? It will leave navigation and filters. {count} product(s) stay visible via direct links.',
  confirmReactivateCategoryTitle: "Reactivate this category?",
  confirmReactivateCategoryBody:
    'Restore "{name}" to active navigation and filters?',
  categoryReorderHint: "Drag rows to change display order.",
  couldNotReorderCategories: "Could not save category order.",
  couldNotReassignProducts: "Could not reassign products.",
  productsReassigned: "Reassigned {count} product(s).",
  name: "Name",
  imageUrl: "Image",
  parentId: "Parent",
  parentName: "Parent",
  displayOrder: "Order",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  shopCategory: "Shop {name}",
  shopCategoryDescription: "Browse {name} on {site}.",
  filteredCategoryNoindex: "Filtered category results",
  categoryBreadcrumbHome: "Home",
  breadcrumb: "Breadcrumb",
  clearFacetFilters: "Clear filters",
  facetResults: "{count} results",
  facetDisabledHint: "No products match with current filters",
  allCategories: "All categories",
  categoryPlpEmpty: "No products in this category yet.",
  categoryPlpEmptyEyebrow: "Empty category",
  categoryPlpEmptyHeading: 'No products in "{name}"',
  categoryPlpEmptyBody:
    "This category has no items listed right now. Try a parent category, or browse the full catalog.",
  categoryPlpNoFilterMatchesEyebrow: "No matches",
  categoryPlpNoFilterMatchesHeading: 'Nothing matches in "{name}"',
  categoryPlpNoFilterMatchesBody:
    "No products in this category match your current filters. Clear filters to see everything available here.",
  browseParentCategory: "Back to {name}",
  categoryNotFound: "Category not found.",
  pageNotFound: "Page not found",
  pageNotFoundBody:
    "The page you're looking for doesn't exist or has been moved.",
  goToHomepage: "Go to homepage",
  dragToReorder: "Drag to reorder",
  featured: "Featured",
  shopNewArrivals: "Shop new arrivals",
  filters: "Filters",
  refine: "Refine",
  clearRating: "Clear rating",
  showResults: "Show results",
  resetFilters: "Reset filters",
  nothingInThisRange: "Nothing in this range",
  nothingInThisRangeHint:
    "No pieces match these filters. Reset them to browse the full collection.",
  noSearchResultsHeading: "No results",
  noSearchResultsHint:
    "Nothing matched “{search}”. Try another term or browse the full collection.",
  noCategoryProductsHeading: "No products here yet",
  noCategoryProductsHintNamed:
    "“{name}” doesn’t have any products right now. Browse the full collection instead.",
  noCategoryProductsHint:
    "This category doesn’t have any products right now. Browse the full collection instead.",
  noVendorProductsHeading: "No products from this vendor",
  noVendorProductsHint:
    "This vendor has nothing listed right now. Browse the full collection instead.",
  noProductsYetHeading: "No products yet",
  noProductsYetHint:
    "The collection is empty for now. Check back soon for new pieces.",
  browseAllProducts: "Browse all products",
  sort: "Sort",
  compare: "Compare",
  compareMinRequired: "Add at least 2 products to compare.",
  compareSelectionCount: "{count} of {max} selected",
  compareMaxReached:
    "Maximum of {max} products reached. Remove one to add another.",
  sortTrending: "Trending",
  sortNewest: "Newest",
  sortPriceLowHigh: "Price: Low to High",
  sortPriceHighLow: "Price: High to Low",
  sortTopRated: "Top Rated",
  productCountSingular: "{count} product",
  productCountPlural: "{count} products",
  updatingEllipsis: "Updating…",
  browseCollection: "Browse collection",
  starsAndUp: "{count}+ stars",
  kycVerificationProgress: "Verification progress",
  kycDocumentsVerifiedCount: "{verified} of {total} verified",
  kycSelectToUpload: "Click a document to upload or replace",
  kycReplaceDocumentNotice:
    "Uploading a new file will submit it for review and replace any existing file.",
  kycAllDocumentsVerified: "All required documents are verified and approved.",
  previewPdf: "PDF document",
  previewDocx: "Word document",
  previewImage: "Image file",
  previewDocument: "Document",
  openInNewTab: "Open in new tab",
  clickToUpload: "Click to upload",
  clickToCollapse: "Click to close",
  rejectionActionHint: "Upload a replacement file to request verification.",
} as const;
