/** Accessible names for tables that render without a visible title. */
export const tableAriaLabels = {
  rolesTableAria: "Roles",
  reportTableAria: "Report data",
  webVitalsTableAria: "Web vitals by route",
  cashDepositsTableAria: "COD cash deposits",
  vendorTopProductsTableAria: "Top products",
  earningsTableAria: "Earnings",
  payoutsTableAria: "Payouts",
  ordersTableAria: "Your orders",
  categoriesTableAria: "Categories",
  vendorCouponsTableAria: "Coupons",
  staleShipmentsTableAria: "Stale shipments",
  stalePickupsTableAria: "Stale pickups",
  deliveryPerformanceTableAria: "Agent delivery performance",
  vendorSettlementsTableAria: "Vendor settlements",
  bulkImportResultsTableAria: "Import results",
  lowStockTableAria: "Low stock products",
  walletLiabilityTableAria: "Wallet liability by user",
  agentDocsTableAria: "Agent verification documents",
  walletRechargeTableAria: "Wallet recharge history",
  adminCashDepositsTableAria: "COD cash deposits reconciliation",
  cashbackWriteOffTableAria: "Cashback write-off report",
  agentPayoutsTableAria: "Agent payouts",
  couponsTableAria: "Coupons",
  couponBatchesTableAria: "Coupon batches",
  rtoQueueTableAria: "RTO queue",
  productModerationTableAria: "Product approval queue",
  vendorApprovalTableAria: "Vendor approval queue",
} as const;
