/** Table cells, pagination and record-detail copy. Subset of LABELS; merged in labels/index.ts. */
export const tablesLabels = {
  refresh: "Refresh",
  loading: "Loading…",
  noRecordsFound: "No records found.",
  recordDetails: "Record details",
  recordDetailsHint:
    "Full fields for this row, including values not shown in the table.",
  noDetailFields: "No fields to display.",
  viewRecordDetails: "View record details",
  close: "Close",
  noCoupons: "No coupons",
  actions: "Actions",
  moreActions: "More actions",
  pageOf: "Page {current} of {total}",
  showingResults: "Showing {from}–{to} of {total}",
  previousPage: "Previous page",
  nextPage: "Next page",
  firstPageHint: "You're on the first page.",
  lastPageHint: "You're on the last page.",
  couldNotLoadData: "Could not load data",
  approve: "Approve",
  reject: "Reject",
  cancel: "Cancel",
  suspend: "Suspend",
  archive: "Archive",
  activate: "Activate",
  block: "Block",
  delete: "Delete",
  edit: "Edit",
  confirm: "Confirm",
  orderActionShip: "Ship",
  orderActionDeliver: "Deliver",
  updateStatus: "Update",
  selectStatus: "Select status",
  processPayouts: "Process payouts",
  commissions: "Commissions",
  couponCode: "Code",
  couponType: "Type",
  couponUsage: "Usage",
  status: "Status",
  expires: "Expires",
  businessName: "Business name",
  vendorName: "Vendor",
  productName: "Product",
  customerName: "Customer",
  actorName: "Actor",
  category: "Category",
  email: "Email",
  newsletterEmailPlaceholder: "Your email",
  subscribe: "Subscribe",
  newsletterInvalidEmail: "Enter a valid email address",
  enterNewsletterEmail: "Enter a valid email address to subscribe.",
  newsletterSuccess: "Thanks — you're on the list. We'll be in touch.",
  newsletterAlreadySubscribed: "You're already on the list. We'll be in touch.",
  newsletterCouldNotSubscribe:
    "Could not subscribe right now. Try again or contact support.",
  trackingNumber: "Tracking number",
  track: "Track",
  role: "Role",
  createdAt: "Created",
  basePrice: "Price",
  totalAmount: "Total",
  rating: "Rating",
  title: "Title",
  body: "Review",
  reason: "Reason",
  reasonCode: "Reason code",
  refundAmount: "Refund",
  saleAmount: "Sale amount",
  commissionRate: "Commission rate",
  commissionAmount: "Commission",
  amount: "Amount",
  periodStart: "Period start",
  periodEnd: "Period end",
  action: "Action",
  entityType: "Business entity type",
  hsnCode: "HSN",
  states: "States",
  pincodePrefixes: "Pincode prefixes",
  yes: "Yes",
  no: "No",
  slug: "Slug",
  rejectionReason: "Rejection reason",
  suspensionReason: "Suspension reason",
  product: "Product",
  price: "Price",
  rejectionNote: "Rejection note",
  reasonRequired: "Reason required",
  enterRejectionNote: "Enter a rejection note before rejecting.",
  enterRejectionReason: "Enter a rejection reason before rejecting.",
  vendorApprovalQueue: "Vendor Approval Queue",
  productModerationQueue: "Product Moderation Queue",
  noPendingVendorApprovals: "No pending vendor approvals",
  noPendingProductApprovals: "No pending product approvals",
  pendingReview: "Pending review",
  allVendors: "All vendors",
  countOverflow: "99+",
  confirmApproveVendorTitle: "Approve this vendor?",
  confirmApproveVendorBody:
    '"{name}" will be approved and can sell on the marketplace.',
  confirmRejectVendorTitle: "Reject this vendor?",
  confirmRejectVendorBody:
    '"{name}" will be rejected. Share a clear reason for the seller.',
  confirmApproveProductTitle: "Approve this product?",
  confirmApproveProductBody:
    '"{name}" will go live for customers once approved.',
  confirmRejectProductTitle: "Reject this product?",
  confirmRejectProductBody:
    '"{name}" will be sent back to the vendor. Include a rejection note.',
  thisItem: "this item",
  confirmSuspendVendorTitle: "Suspend this vendor?",
  confirmSuspendVendorBody:
    '"{name}" will be suspended and hidden from customers. Provide a reason.',
  confirmArchiveProductTitle: "Archive this product?",
  confirmArchiveProductBody:
    '"{name}" will be archived and removed from the live catalog.',
  confirmDeleteProductTitle: "Delete this product?",
  confirmDeleteProductBody: 'Delete "{name}"? This cannot be undone.',
  confirmDeleteProductFallback: "This cannot be undone.",
  confirmOrderTitle: "Confirm this order?",
  confirmOrderBody: 'Mark order "{name}" as confirmed?',
  kycDocuments: "KYC documents",
  viewKycDocuments: "Documents",
  noKycDocuments: "No KYC documents uploaded yet.",
  documentTypeGst: "GST certificate",
  documentTypePan: "PAN",
  documentTypeAadhaar: "Aadhaar",
  documentTypeBank: "Bank proof",
  documentTypeAddressProof: "Address proof",
  documentTypeIncorporationCert: "Incorporation certificate",
  documentTypePartnershipDeed: "Partnership deed",
  documentTypeAuthorizedSignatoryId: "Authorized signatory ID",
  documentTypeFssaiLicense: "FSSAI license",
  documentTypeCategoryTradeLicense: "Category / trade license",
  documentVerified: "Verified",
  documentPending: "Pending verification",
  documentNotUploaded: "Not uploaded",
  documentRejected: "Rejected",
  documentRejectionReason: "Rejection reason",
  verifyDocument: "Verify",
  rejectDocument: "Reject",
  uploadKycDocument: "Upload KYC document",
  uploadKycDocumentHint:
    "Upload each required document. Rejected documents can be replaced.",
  kycDocumentUploaded: "Document uploaded.",
  couldNotUploadKycDocument: "Could not upload document.",
  kycChecklist: "KYC checklist",
  kycChecklistHint: "Required documents for your business type and categories.",
  kycChecklistIncomplete:
    "Complete and verify all required documents before approval.",
  kycChecklistComplete: "All required documents are verified.",
  couldNotLoadKycChecklist: "Could not load KYC checklist.",
  kycApproveBlocked:
    "Cannot approve until all required KYC documents are verified.",
  kycNameMismatchWarningAcknowledged:
    "Name mismatch noted — review carefully when uploading documents.",
  submitForApproval: "Submit for approval",
  couldNotSubmitProduct: "Could not submit product for approval.",
  productSubmittedForApproval: "Product submitted for approval.",
  couldNotOpenDocument: "Could not open document.",
  saveCategories: "Save categories",
  categoriesSaved:
    "Categories updated. Check the KYC checklist for any new requirements.",
  couldNotSaveCategories: "Could not save categories.",
  entityTypeSole: "Sole proprietorship",
  entityTypePartnership: "Partnership",
  entityTypeLlp: "LLP",
  entityTypePrivateLimited: "Private limited",
  vendorCategories: "Selling categories",
  vendorCategoriesHint:
    "Select the categories you plan to sell in. Extra regulated categories may require more documents.",
  panHolderName: "Name on PAN",
  bankAccountHolderName: "Bank account holder name",
  kycNameMismatchWarning:
    "Bank account holder name does not match the name on PAN. This is a common rejection reason — double-check before submitting.",
  requiredDocuments: "Required documents",
  registerAsVendor: "Register as a vendor",
  registerAsVendorHint:
    "Tell us your entity type and categories first so we can list the documents you need.",
  registrationFailed: "Registration failed. Try again.",
  businessDescriptionOptional: "Description (optional)",
  gstNumberOptional: "GST number (optional)",
  startSelling: "Start selling on the marketplace",
  promoBanners: "Promo banners",
  promoBannersHint:
    "Homepage hero banners. Upload the image first, then save the banner.",
  promoBannerTitle: "Title",
  promoBannerImage: "Banner image",
  promoBannerLinkType: "Link type",
  promoBannerLinkTargetId: "Link target ID",
  promoBannerLinkUrl: "Link URL",
  promoBannerPriority: "Priority",
  promoBannerStatus: "Status",
  promoBannerStartDate: "Start date",
  promoBannerEndDate: "End date",
  createPromoBanner: "Create banner",
  noPromoBanners: "No promo banners yet.",
  couldNotLoadPromoBanners: "Could not load promo banners.",
  couldNotSavePromoBanner: "Could not save promo banner.",
  promoBannerSaved: "Promo banner saved.",
  promoBannerDeleted: "Promo banner deleted.",
  enterPromoBannerTitle: "Enter a banner title to continue.",
  uploadPromoBannerImage: "Upload a banner image to continue.",
  enterPromoBannerLinkUrl: "Enter a link URL to continue.",
  enterPromoBannerLinkTarget: "Enter a link target ID to continue.",
  confirmDeletePromoBannerTitle: "Delete this banner?",
  confirmDeletePromoBannerBody:
    'Delete "{name}"? The image will be removed from storage.',
  shopNow: "Shop now",
  promoBannerEyebrow: "Featured",
  confirmVerifyDocumentTitle: "Verify this document?",
  confirmVerifyDocumentBody: 'Mark "{type}" as verified for {name}.',
  confirmRejectDocumentTitle: "Reject this document?",
  confirmRejectDocumentBody:
    '"{type}" for {name} will be rejected and removed. The seller will be notified by email.',
  openDocument: "Open document",
  documentType: "Document type",
  couldNotLoadDocuments: "Could not load documents.",
  confirmApproveReturnTitle: "Approve this return?",
  confirmApproveReturnBody:
    'Approve return request "{name}" and continue the refund flow?',
  confirmApproveReviewTitle: "Approve this review?",
  confirmApproveReviewBody: 'Publish review "{name}" for shoppers to see?',
  confirmRejectReviewTitle: "Reject this review?",
  confirmRejectReviewBody:
    'Reject review "{name}"? It will not appear publicly.',
  confirmDeleteCategoryTitle: "Delete this category?",
  confirmDeleteCategoryBody:
    'Delete "{name}"? Categories with products or subcategories cannot be deleted.',
  confirmDeleteTaxTitle: "Delete this tax rule?",
  confirmDeleteTaxBody: 'Delete tax rule "{name}"? This cannot be undone.',
  confirmDeleteShippingTitle: "Delete this shipping zone?",
  confirmDeleteShippingBody:
    'Delete shipping zone "{name}"? Rates in this zone will be affected.',
  confirmBlockUserTitle: "Block this user?",
  confirmBlockUserBody:
    'Block "{name}"? They will no longer be able to sign in.',
  confirmActivateUserTitle: "Activate this user?",
  confirmActivateUserBody: 'Activate "{name}" and restore account access?',
  confirmDeleteUserTitle: "Delete this user?",
  confirmDeleteUserBody: 'Delete "{name}"? This cannot be undone.',
  confirmProcessPayoutsTitle: "Process payouts?",
  confirmProcessPayoutsBody:
    "Process pending payouts for eligible vendors now?",
  enterSuspendReason: "Enter a suspension reason before continuing.",
  create: "Create",
  save: "Save",
  newCategory: "New category",
  createCategory: "Create category",
  createCategoryHint:
    "Add a catalog category with optional parent, image, and status.",
  enterCategoryName: "Enter a category name to create.",
  editCategoryTitle: "Edit category",
  editCategoryBody: "Update name, parent, image, and status for this category.",
  categoryName: "Category name",
  categoryNameRequired: "Category name is required",
  enterCategoryNameToSave: "Enter a category name to save.",
  imageNotAvailable: "Image not available",
  parentCategory: "Parent category",
  parentCategoryNone: "None (top-level)",
  selectParentCategory: "Select a parent category",
  categoryImageUrl: "Image URL",
  categoryImageUrlPlaceholder: "https://…",
  categoryImageUrlInvalid: "Enter a valid image URL",
  categoryImageUpload: "Category image",
  uploadFile: "Upload file",
  uploadFiles: "Upload files",
  uploading: "Uploading…",
  uploadFailed: "Could not upload file.",
  uploadStorageUnavailable:
    "File upload is temporarily unavailable. Please try again later.",
  uploadForbidden: "You do not have permission to upload this file.",
  uploadTooLargeGeneric: "File is too large.",
  unexpectedError: "Something went wrong. Please try again.",
  unexpectedErrorHeading: "Something went wrong",
  backToHome: "Back to home",
  notFoundHeading: "Page not found",
  notFoundAdminBody:
    "This admin page does not exist. Use the sidebar to pick a section.",
  notFoundVendorBody:
    "This vendor page does not exist. Use the sidebar to pick a section.",
  unexpectedErrorBody:
    "Please try again. If the problem continues, contact support.",
  validationFailedGeneric: "Please check the form and try again.",
  uploadTooLargeMb: "File must be under {mb}MB.",
  uploadFileFailedAt: "File {index}: {message}",
  genericActionFailed: "Action failed. Please try again.",
  couldNotUpdateOrderStatus: "Could not update order status.",
  orderManagement: "Order Management",
  vendorColumn: "Vendor",
  noOrdersFound: "No orders found",
  errorRetryHint: "Something went wrong while loading this section.",
  retry: "Try again",
  uploadProfilePhoto: "Upload profile photo",
  uploadProfilePhotoHint:
    "Recommended 512×512 (1:1). PNG, JPEG, or WebP up to 1.5MB. Edit after selecting.",
  uploadInvalidImageType: "Please choose a PNG, JPEG, or WebP image.",
  imageCropTitle: "Edit image",
  imageCropHint: "Drag to reposition. Adjust zoom and rotation, then apply.",
  imageCropZoom: "Zoom",
  imageCropRotation: "Rotation",
  imageCropRotateLeft: "Rotate left",
  imageCropRotateRight: "Rotate right",
  imageCropReset: "Reset",
  imageCropConfirm: "Apply",
  imageCropProcessing: "Processing…",
  categoryFormSectionBasics: "Basics",
  categoryFormSectionImage: "Image",
  categoryFormSectionSeo: "SEO & commission",
  categoryFormSectionBasicsHint: "Name, parent, and visibility.",
  categoryFormSectionImageHint: "Upload and crop the category image.",
  categoryFormSectionSeoHint:
    "Optional search metadata and commission override.",
  productFormSectionDetails: "Product details",
  productFormSectionDetailsHint:
    "Name, selling price, MRP, brand, category, and description.",
  productFormSectionCatalog: "Catalog content",
  productFormSectionCatalogHint:
    "Tags, highlights, and specifications shown on the product page.",
  productFormSectionPolicies: "Delivery and returns",
  productFormSectionPoliciesHint:
    "Optional extra notes shown under the platform delivery and return policy.",
  productFormSectionImages: "Images",
  productFormSectionImagesHint: "Add one or more product photos.",
  productFormSectionMedia: "Video & size chart",
  productFormSectionMediaHint: "Optional media shown on the product page.",
  productFormSectionSeo: "Search listing",
  productFormSectionSeoHint:
    "Optional title and description for search engines. Leave blank to use the product name and description.",
  promoBannerFormSection: "Banner details",
  promoBannerFormSectionHint: "Title, image, link, status, and priority.",
  promoBannerEditSection: "Edit banner",
  promoBannerEditSectionHint: "Update banner content and link settings.",
  vendorRegisterSectionBasics: "Business details",
  vendorRegisterSectionBasicsHint: "How your shop appears on the marketplace.",
  vendorRegisterSectionCategories: "Categories",
  vendorRegisterSectionCategoriesHint: "Select the categories you sell in.",
  vendorRegisterSectionIdentity: "Identity & bank",
  vendorRegisterSectionIdentityHint: "Used for KYC and payouts.",
  imageUploadHintPromoBanner:
    "Recommended 1920×1080 (16:9). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintCategory:
    "Recommended 1200×900 (4:3). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintProduct:
    "Recommended 1200×1200 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintProductVideo:
    "MP4 or WebM up to {mb}MB. Crop is not required.",
  imageUploadHintSizeChart:
    "Recommended 1200×900 (4:3). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadInvalidVideoType: "Please choose an MP4 or WebM video.",
  imageUploadHintVendorLogo:
    "Recommended 512×512 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintVendorBanner:
    "Recommended 1680×525 (16:5). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintAvatar:
    "Recommended 512×512 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintReturnPhoto:
    "Recommended 1600×1200 (4:3). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintKyc: "PNG, JPEG, WebP, or PDF up to {mb}MB.",
  imageUploadHintTicketAttachment:
    "Up to 5 images (5MB each) and 1 video (60s / 50MB). PNG, JPEG, WebP, MP4, or WebM.",
  imageUploadHintBugAttachment:
    "Up to 5 screenshots (5MB each) and 1 screen recording (120s / 50MB). PNG, JPEG, WebP, MP4, or WebM.",
  imageUploadInvalidDocumentType:
    "Please choose a PNG, JPEG, WebP, or PDF file.",
  returnPhotosLabel: "Photos (optional)",
  productImagesLabel: "Product images",
  manageProductImages: "Manage product images",
  addProductImage: "Add image",
  productImageVariant: "Show for variant",
  productImageAllVariants: "All variants",
  replaceImage: "Replace image",
  deleteImage: "Delete image",
  setPrimaryImage: "Set as primary",
  primaryImage: "Primary image",
  couldNotLoadProduct: "Could not load product.",
  productNotFoundTitle: "Product Not Found",
  couldNotSaveProduct: "Could not save product.",
  couldNotSaveProductImages: "Could not save product images.",
  vendorProductsHint:
    "Manage your catalog — create, edit listing details, and delete products you own.",
  addProduct: "Add product",
  createProductBody:
    "Add a new product to your catalog. Upload images during creation or manage them later.",
  editProductTitle: "Edit product",
  editProductBody:
    "Update listing details, policies, and search settings for this product.",
  productBrandPlaceholder: "Brand name",
  productTagsHint: "Separate tags with commas.",
  productTagsPlaceholder: "cookware, steel, induction",
  addProductHighlight: "Add highlight",
  addProductSpecification: "Add specification",
  productSpecKey: "Label",
  productSpecValue: "Value",
  productDeliveryNote: "Delivery note",
  productReturnNote: "Return note",
  productDeliveryNoteHint:
    "Optional. Shown under the free-delivery policy on the product page.",
  productReturnNoteHint:
    "Optional. Shown under the returns policy on the product page.",
  productWarrantyMonths: "Warranty (months)",
  productWarrantyMonthsHint: "Leave blank to inherit the category default.",
  enterWarrantyMonths:
    "Enter warranty months from 0 to {max}, or leave blank to inherit.",
  productMediaUrlInvalid: "Enter a valid media URL or upload a file.",
  productWarrantyType: "Warranty type",
  productHsnCode: "HSN code",
  productHsnCodeHint:
    "Optional display override. Tax still follows category tax rules.",
  productSeoTitle: "SEO title",
  productSeoDescription: "SEO description",
  productVideoUrl: "Product video",
  productSizeChart: "Size chart",
  productCodEnabled: "Cash on delivery",
  productCodInherit: "Inherit from category and seller",
  productCodOn: "Allow COD",
  productCodOff: "Do not allow COD",
  inheritDefault: "Inherit default",
  categoryReturnWindowDays: "Return window (days)",
  categoryReturnWindowHint:
    "Blank inherits the parent, then the platform default. 0 means not returnable.",
  categoryCodEnabled: "Allow cash on delivery",
  categoryDefaultWarrantyMonths: "Default warranty (months)",
  categoryDefaultWarrantyType: "Default warranty type",
  categoryFormSectionPolicies: "Returns, COD & warranty",
  categoryFormSectionPoliciesHint:
    "Category defaults used on product pages when a listing does not override them.",
  settingsCod: "Cash on delivery",
  settingsCodHint:
    "Platform COD switch and order-value limits. Category, seller, and product flags must also allow COD.",
  settingsCodEnabled: "Enable cash on delivery",
  settingsCodMinOrder: "COD minimum order value",
  settingsCodMaxOrder: "COD maximum order value",
  vendorCodEnabled: "Accept cash on delivery",
  vendorCodEnabledHint:
    "Turn off to disable COD for every product from this shop.",
  productMrpHint: "Optional. Must be at least the selling price.",
  productFieldTooLong: "Must be {max} characters or fewer.",
  productListTooLong: "You can add at most {max} items.",
  productSpecPairRequired: "Each specification needs both a label and a value.",
  productSpecDuplicateKey: "Specification labels must be unique.",
  productCompareAtBelowPrice:
    "MRP must be greater than or equal to the selling price.",
  enterProductDescription: "Enter a product description to continue.",
  enterProductCompareAtPrice: "Enter a valid MRP or leave it blank.",
  enterProductHighlight: "Enter highlight text or remove the empty row.",
  editPromoBanner: "Edit banner",
  savePromoBanner: "Save banner",
  confirmDeleteVendorTitle: "Delete vendor?",
  confirmDeleteVendorBody:
    'Delete "{name}" and all associated media? This cannot be undone.',
  confirmDeleteReturnTitle: "Delete return?",
  confirmDeleteReturnBody:
    'Delete return for "{name}" and its photos? This cannot be undone.',
  categoryStatus: "Status",
  categoryStatusActive: "Active",
  categoryStatusArchived: "Archived",
  categorySeoTitle: "SEO title",
  categorySeoDescription: "SEO description",
  categoryCommissionRate: "Category commission %",
  categoryCommissionRateHint:
    "Optional override; leaves inherit from parents, then vendor default.",
  categoryCommissionPlaceholder: "0–100",
  categoryAttributes: "Filter attributes",
  categoryAttributesHint:
    "Define category-specific filters (Material, Size, etc.).",
  addCategoryAttribute: "Add attribute",
  attributeName: "Attribute name",
  attributeType: "Attribute type",
  attributeOptions: "Options (comma-separated)",
  attributeTypeEnum: "Enum",
  attributeTypeRange: "Range",
  attributeTypeBoolean: "Boolean",
  manageAttributes: "Attributes",
  editCategoryAttribute: "Edit attribute",
  saveCategoryAttribute: "Save attribute",
  cancelEditAttribute: "Cancel",
  couldNotReorderAttributes: "Could not save attribute order.",
  couldNotSaveAttribute: "Could not save attribute.",
  couldNotDeleteAttribute: "Could not delete attribute.",
  deleteCategoryAttribute: "Delete attribute",
  reassignProducts: "Reassign products",
  reassignProductsTitle: "Bulk reassign products",
  reassignProductsBody: "Move all products from one category to another.",
  reassignFrom: "From category",
  reassignTo: "To category",
  reassignConfirm: "Reassign",
  selectCategory: "Select category",
  archiveCategory: "Archive",
  reactivateCategory: "Reactivate",
  confirmArchiveCategoryTitle: "Archive this category?",
  confirmArchiveCategoryBody:
    'Archive "{name}"? It will leave navigation and filters. {count} product(s) stay visible via direct links.',
  confirmReactivateCategoryTitle: "Reactivate this category?",
  confirmReactivateCategoryBody:
    'Restore "{name}" to active navigation and filters?',
  categoryReorderHint: "Drag rows to change display order.",
  couldNotReorderCategories: "Could not save category order.",
  couldNotReassignProducts: "Could not reassign products.",
  productsReassigned: "Reassigned {count} product(s).",
  name: "Name",
  imageUrl: "Image",
  parentId: "Parent",
  parentName: "Parent",
  displayOrder: "Order",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  shopCategory: "Shop {name}",
  shopCategoryDescription: "Browse {name} on {site}.",
  filteredCategoryNoindex: "Filtered category results",
  categoryBreadcrumbHome: "Home",
  breadcrumb: "Breadcrumb",
  clearFacetFilters: "Clear filters",
  facetResults: "{count} results",
  facetDisabledHint: "No products match with current filters",
  allCategories: "All categories",
  categoryPlpEmpty: "No products in this category yet.",
  categoryPlpEmptyEyebrow: "Empty category",
  categoryPlpEmptyHeading: 'No products in "{name}"',
  categoryPlpEmptyBody:
    "This category has no items listed right now. Try a parent category, or browse the full catalog.",
  categoryPlpNoFilterMatchesEyebrow: "No matches",
  categoryPlpNoFilterMatchesHeading: 'Nothing matches in "{name}"',
  categoryPlpNoFilterMatchesBody:
    "No products in this category match your current filters. Clear filters to see everything available here.",
  browseParentCategory: "Back to {name}",
  categoryNotFound: "Category not found.",
  pageNotFound: "Page not found",
  pageNotFoundBody:
    "The page you're looking for doesn't exist or has been moved.",
  goToHomepage: "Go to homepage",
  dragToReorder: "Drag to reorder",
  featured: "Featured",
  shopNewArrivals: "Shop new arrivals",
  filters: "Filters",
  refine: "Refine",
  clearRating: "Clear rating",
  showResults: "Show results",
  resetFilters: "Reset filters",
  nothingInThisRange: "Nothing in this range",
  nothingInThisRangeHint:
    "No pieces match these filters. Reset them to browse the full collection.",
  noSearchResultsHeading: "No results",
  noSearchResultsHint:
    "Nothing matched “{search}”. Try another term or browse the full collection.",
  noCategoryProductsHeading: "No products here yet",
  noCategoryProductsHintNamed:
    "“{name}” doesn’t have any products right now. Browse the full collection instead.",
  noCategoryProductsHint:
    "This category doesn’t have any products right now. Browse the full collection instead.",
  noVendorProductsHeading: "No products from this vendor",
  noVendorProductsHint:
    "This vendor has nothing listed right now. Browse the full collection instead.",
  noProductsYetHeading: "No products yet",
  noProductsYetHint:
    "The collection is empty for now. Check back soon for new pieces.",
  browseAllProducts: "Browse all products",
  sort: "Sort",
  compare: "Compare",
  sortTrending: "Trending",
  sortNewest: "Newest",
  sortPriceLowHigh: "Price: Low to High",
  sortPriceHighLow: "Price: High to Low",
  sortTopRated: "Top Rated",
  productCountSingular: "{count} product",
  productCountPlural: "{count} products",
  updatingEllipsis: "Updating…",
  browseCollection: "Browse collection",
  starsAndUp: "{count}+ stars",
  // Platform settings
} as const;
