/** Table and pagination copy (part 2); merged via labels.ts. */
export const tables2Labels = {
  promoBannerPriority: "Priority",
  promoBannerStatus: "Status",
  promoBannerStartDate: "Start date",
  promoBannerEndDate: "End date",
  createPromoBanner: "Create banner",
  noPromoBanners: "No promo banners yet.",
  couldNotLoadPromoBanners: "Could not load promo banners.",
  couldNotSavePromoBanner: "Could not save promo banner.",
  promoBannerSaved: "Promo banner saved.",
  promoBannerDeleted: "Promo banner deleted.",
  enterPromoBannerTitle: "Enter a banner title to continue.",
  uploadPromoBannerImage: "Upload a banner image to continue.",
  enterPromoBannerLinkUrl: "Enter a link URL to continue.",
  enterPromoBannerLinkTarget: "Enter a link target ID to continue.",
  confirmDeletePromoBannerTitle: "Delete this banner?",
  confirmDeletePromoBannerBody:
    'Delete "{name}"? The image will be removed from storage.',
  shopNow: "Shop now",
  promoBannerEyebrow: "Featured",
  confirmVerifyDocumentTitle: "Verify this document?",
  confirmVerifyDocumentBody: 'Mark "{type}" as verified for {name}.',
  confirmRejectDocumentTitle: "Reject this document?",
  confirmRejectDocumentBody:
    '"{type}" for {name} will be rejected and removed. The seller will be notified by email.',
  openDocument: "Open document",
  documentType: "Document type",
  couldNotLoadDocuments: "Could not load documents.",
  confirmApproveReturnTitle: "Approve this return?",
  confirmApproveReturnBody:
    'Approve return request "{name}" and continue the refund flow?',
  confirmRejectReturnTitle: "Reject this return?",
  confirmRejectReturnBody:
    'Reject return request "{name}"? Your reason will be shown to the customer on their return.',
  confirmApproveReviewTitle: "Approve this review?",
  confirmApproveReviewBody: 'Publish review "{name}" for shoppers to see?',
  confirmRejectReviewTitle: "Reject this review?",
  confirmRejectReviewBody:
    'Reject review "{name}"? It will not appear publicly.',
  confirmDeleteCategoryTitle: "Delete this category?",
  confirmDeleteCategoryBody:
    'Delete "{name}"? Categories with products or subcategories cannot be deleted.',
  confirmDeleteTaxTitle: "Delete this tax rule?",
  confirmDeleteTaxBody: 'Delete tax rule "{name}"? This cannot be undone.',
  confirmDeleteShippingTitle: "Delete this shipping zone?",
  confirmDeleteShippingBody:
    'Delete shipping zone "{name}"? Rates in this zone will be affected.',
  confirmBlockUserTitle: "Block this user?",
  confirmBlockUserBody:
    'Block "{name}"? They will no longer be able to sign in.',
  confirmActivateUserTitle: "Activate this user?",
  confirmActivateUserBody: 'Activate "{name}" and restore account access?',
  confirmDeleteUserTitle: "Delete this user?",
  confirmDeleteUserBody: 'Delete "{name}"? This cannot be undone.',
  confirmProcessPayoutsTitle: "Process payouts?",
  confirmProcessPayoutsBody:
    "Process pending payouts for eligible vendors now?",
  enterSuspendReason: "Enter a suspension reason before continuing.",
  create: "Create",
  save: "Save",
  newCategory: "New category",
  createCategory: "Create category",
  createCategoryHint:
    "Add a catalog category with optional parent, image, and status.",
  enterCategoryName: "Enter a category name to create.",
  editCategoryTitle: "Edit category",
  editCategoryBody: "Update name, parent, image, and status for this category.",
  categoryName: "Category name",
  categoryNameRequired: "Category name is required",
  enterCategoryNameToSave: "Enter a category name to save.",
  imageNotAvailable: "Image not available",
  parentCategory: "Parent category",
  parentCategoryNone: "None (top-level)",
  selectParentCategory: "Select a parent category",
  categoryImageUrl: "Image URL",
  categoryImageUrlPlaceholder: "https://…",
  categoryImageUrlInvalid: "Enter a valid image URL",
  categoryImageUpload: "Category image",
  uploadFile: "Upload file",
  uploadFiles: "Upload files",
  uploading: "Uploading…",
  uploadFailed: "Could not upload file.",
  uploadStorageUnavailable:
    "File upload is temporarily unavailable. Please try again later.",
  uploadForbidden: "You do not have permission to upload this file.",
  uploadTooLargeGeneric: "File is too large.",
  unexpectedError: "Something went wrong. Please try again.",
  unexpectedErrorHeading: "Something went wrong",
  backToHome: "Back to home",
  notFoundHeading: "Page not found",
  notFoundAdminBody:
    "This admin page does not exist. Use the sidebar to pick a section.",
  notFoundVendorBody:
    "This vendor page does not exist. Use the sidebar to pick a section.",
  unexpectedErrorBody:
    "Please try again. If the problem continues, contact support.",
  validationFailedGeneric: "Please check the form and try again.",
  uploadTooLargeMb: "File must be under {mb}MB.",
  uploadFileFailedAt: "File {index}: {message}",
  genericActionFailed: "Action failed. Please try again.",
  couldNotUpdateOrderStatus: "Could not update order status.",
  orderManagement: "Order Management",
  vendorColumn: "Vendor",
  delivery: "Delivery",
  notShippedYet: "Not shipped yet",
  noOrdersFound: "No orders found",
  errorRetryHint: "Something went wrong while loading this section.",
  retry: "Try again",
  uploadProfilePhoto: "Upload profile photo",
  uploadProfilePhotoHint:
    "Recommended 512×512 (1:1). PNG, JPEG, or WebP up to 1.5MB. Edit after selecting.",
  uploadInvalidImageType: "Please choose a PNG, JPEG, or WebP image.",
  imageCropTitle: "Edit image",
  imageCropHint: "Drag to reposition. Adjust zoom and rotation, then apply.",
  imageCropZoom: "Zoom",
  imageCropRotation: "Rotation",
  imageCropRotateLeft: "Rotate left",
  imageCropRotateRight: "Rotate right",
  imageCropReset: "Reset",
  imageCropConfirm: "Apply",
  imageCropProcessing: "Processing…",
  categoryFormSectionBasics: "Basics",
  categoryFormSectionImage: "Image",
  categoryFormSectionSeo: "SEO & commission",
  categoryFormSectionBasicsHint: "Name, parent, and visibility.",
  categoryFormSectionImageHint: "Upload and crop the category image.",
  categoryFormSectionSeoHint:
    "Optional search metadata and commission override.",
  productFormSectionDetails: "Product details",
  productFormSectionDetailsHint:
    "Name, selling price, MRP, brand, category, and description.",
  productFormSectionCatalog: "Catalog content",
  productFormSectionCatalogHint:
    "Tags, highlights, and specifications shown on the product page.",
  productFormSectionPolicies: "Delivery and returns",
  productFormSectionPoliciesHint:
    "Optional extra notes shown under the platform delivery and return policy.",
  productFormSectionImages: "Images",
  productFormSectionImagesHint: "Add one or more product photos.",
  productFormSectionMedia: "Video & size chart",
  productFormSectionMediaHint: "Optional media shown on the product page.",
  productFormSectionSeo: "Search listing",
  productFormSectionSeoHint:
    "Optional title and description for search engines. Leave blank to use the product name and description.",
  promoBannerFormSection: "Banner details",
  promoBannerFormSectionHint: "Title, image, link, status, and priority.",
  promoBannerEditSection: "Edit banner",
  promoBannerEditSectionHint: "Update banner content and link settings.",
  vendorRegisterSectionBasics: "Business details",
  vendorRegisterSectionBasicsHint: "How your shop appears on the marketplace.",
  vendorRegisterSectionCategories: "Categories",
  vendorRegisterSectionCategoriesHint: "Select the categories you sell in.",
  vendorRegisterSectionIdentity: "Identity & bank",
  vendorRegisterSectionIdentityHint: "Used for KYC and payouts.",
  imageUploadHintPromoBanner:
    "Recommended 1920×1080 (16:9). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintCategory:
    "Recommended 1200×900 (4:3). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintProduct:
    "Recommended 1200×1200 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintProductVideo:
    "MP4 or WebM up to {mb}MB. Crop is not required.",
  imageUploadHintSizeChart:
    "Recommended 1200×900 (4:3). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadInvalidVideoType: "Please choose an MP4 or WebM video.",
  imageUploadHintVendorLogo:
    "Recommended 512×512 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintVendorBanner:
    "Recommended 1680×525 (16:5). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintAvatar:
    "Recommended 512×512 (1:1). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintReturnPhoto:
    "Recommended 1600×1200 (4:3). PNG, JPEG, or WebP up to {mb}MB. Edit after selecting.",
  imageUploadHintKyc: "PNG, JPEG, WebP, or PDF up to {mb}MB.",
  imageUploadHintTicketAttachment:
    "Up to 5 images (5MB each) and 1 video (60s / 50MB). PNG, JPEG, WebP, MP4, or WebM.",
  imageUploadHintBugAttachment:
    "Up to 5 screenshots (5MB each) and 1 screen recording (120s / 50MB). PNG, JPEG, WebP, MP4, or WebM.",
  imageUploadInvalidDocumentType:
    "Please choose a PNG, JPEG, WebP, or PDF file.",
  returnPhotosLabel: "Photos (optional)",
  productImagesLabel: "Product images",
  manageProductImages: "Manage product images",
  addProductImage: "Add image",
  productImageVariant: "Show for variant",
  productImageAllVariants: "All variants",
  replaceImage: "Replace image",
  deleteImage: "Delete image",
  setPrimaryImage: "Set as primary",
  primaryImage: "Primary image",
  couldNotLoadProduct: "Could not load product.",
  productNotFoundTitle: "Product Not Found",
  couldNotSaveProduct: "Could not save product.",
  couldNotSaveProductImages: "Could not save product images.",
  vendorProductsHint:
    "Manage your catalog — create, edit listing details, and delete products you own.",
} as const;
