/** Table and pagination copy (part 1); merged via labels.ts. */
export const tablesLabels = {
  refresh: "Refresh",
  loading: "Loading…",
  noRecordsFound: "No records found.",
  recordDetails: "Record details",
  recordDetailsHint:
    "Full fields for this row, including values not shown in the table.",
  noDetailFields: "No fields to display.",
  viewRecordDetails: "View record details",
  close: "Close",
  noCoupons: "No coupons",
  actions: "Actions",
  moreActions: "More actions",
  pageOf: "Page {current} of {total}",
  showingResults: "Showing {from}–{to} of {total}",
  previousPage: "Previous page",
  nextPage: "Next page",
  firstPageHint: "You're on the first page.",
  lastPageHint: "You're on the last page.",
  couldNotLoadData: "Could not load data",
  approve: "Approve",
  reject: "Reject",
  cancel: "Cancel",
  suspend: "Suspend",
  archive: "Archive",
  activate: "Activate",
  block: "Block",
  delete: "Delete",
  edit: "Edit",
  confirm: "Confirm",
  orderActionShip: "Ship",
  orderActionDeliver: "Deliver",
  updateStatus: "Update",
  selectStatus: "Select status",
  processPayouts: "Process payouts",
  commissions: "Commissions",
  couponCode: "Code",
  couponType: "Type",
  couponUsage: "Usage",
  status: "Status",
  expires: "Expires",
  businessName: "Business name",
  vendorName: "Vendor",
  productName: "Product",
  customerName: "Customer",
  actorName: "Actor",
  category: "Category",
  email: "Email",
  newsletterEmailPlaceholder: "Your email",
  subscribe: "Subscribe",
  newsletterInvalidEmail: "Enter a valid email address",
  enterNewsletterEmail: "Enter a valid email address to subscribe.",
  newsletterSuccess: "Thanks — you're on the list. We'll be in touch.",
  newsletterAlreadySubscribed: "You're already on the list. We'll be in touch.",
  newsletterCouldNotSubscribe:
    "Could not subscribe right now. Try again or contact support.",
  trackingNumber: "Tracking number",
  track: "Track",
  role: "Role",
  createdAt: "Created",
  basePrice: "Price",
  totalAmount: "Total",
  rating: "Rating",
  title: "Title",
  body: "Review",
  reason: "Reason",
  reasonCode: "Reason code",
  refundAmount: "Refund",
  saleAmount: "Sale amount",
  commissionRate: "Commission rate",
  commissionAmount: "Commission",
  amount: "Amount",
  periodStart: "Period start",
  periodEnd: "Period end",
  action: "Action",
  entityType: "Business entity type",
  hsnCode: "HSN",
  states: "States",
  pincodePrefixes: "Pincode prefixes",
  yes: "Yes",
  no: "No",
  slug: "Slug",
  rejectionReason: "Rejection reason",
  suspensionReason: "Suspension reason",
  product: "Product",
  price: "Price",
  rejectionNote: "Rejection note",
  reasonRequired: "Reason required",
  enterRejectionNote: "Enter a rejection note before rejecting.",
  enterRejectionReason: "Enter a rejection reason before rejecting.",
  vendorApprovalQueue: "Vendor Approval Queue",
  productModerationQueue: "Product Moderation Queue",
  noPendingVendorApprovals: "No pending vendor approvals",
  noPendingProductApprovals: "No pending product approvals",
  pendingReview: "Pending review",
  allVendors: "All vendors",
  countOverflow: "99+",
  confirmApproveVendorTitle: "Approve this vendor?",
  confirmApproveVendorBody:
    '"{name}" will be approved and can sell on the marketplace.',
  confirmRejectVendorTitle: "Reject this vendor?",
  confirmRejectVendorBody:
    '"{name}" will be rejected. Share a clear reason for the seller.',
  confirmApproveProductTitle: "Approve this product?",
  confirmApproveProductBody:
    '"{name}" will go live for customers once approved.',
  confirmRejectProductTitle: "Reject this product?",
  confirmRejectProductBody:
    '"{name}" will be sent back to the vendor. Include a rejection note.',
  thisItem: "this item",
  confirmSuspendVendorTitle: "Suspend this vendor?",
  confirmSuspendVendorBody:
    '"{name}" will be suspended and hidden from customers. Provide a reason.',
  confirmArchiveProductTitle: "Archive this product?",
  confirmArchiveProductBody:
    '"{name}" will be archived and removed from the live catalog.',
  confirmDeleteProductTitle: "Delete this product?",
  confirmDeleteProductBody: 'Delete "{name}"? This cannot be undone.',
  confirmDeleteProductFallback: "This cannot be undone.",
  confirmOrderTitle: "Confirm this order?",
  confirmOrderBody: 'Mark order "{name}" as confirmed?',
  kycDocuments: "KYC documents",
  viewKycDocuments: "Documents",
  noKycDocuments: "No KYC documents uploaded yet.",
  documentTypeGst: "GST certificate",
  documentTypePan: "PAN",
  documentTypeAadhaar: "Aadhaar",
  documentTypeBank: "Bank proof",
  documentTypeAddressProof: "Address proof",
  documentTypeIncorporationCert: "Incorporation certificate",
  documentTypePartnershipDeed: "Partnership deed",
  documentTypeAuthorizedSignatoryId: "Authorized signatory ID",
  documentTypeFssaiLicense: "FSSAI license",
  documentTypeCategoryTradeLicense: "Category / trade license",
  documentVerified: "Verified",
  documentPending: "Pending verification",
  documentNotUploaded: "Not uploaded",
  documentRejected: "Rejected",
  documentRejectionReason: "Rejection reason",
  verifyDocument: "Verify",
  rejectDocument: "Reject",
  uploadKycDocument: "Upload KYC document",
  uploadKycDocumentHint:
    "Upload each required document. Rejected documents can be replaced.",
  kycDocumentUploaded: "Document uploaded.",
  couldNotUploadKycDocument: "Could not upload document.",
  kycChecklist: "KYC checklist",
  kycChecklistHint: "Required documents for your business type and categories.",
  kycChecklistIncomplete:
    "Complete and verify all required documents before approval.",
  kycChecklistComplete: "All required documents are verified.",
  couldNotLoadKycChecklist: "Could not load KYC checklist.",
  kycApproveBlocked:
    "Cannot approve until all required KYC documents are verified.",
  kycNameMismatchWarningAcknowledged:
    "Name mismatch noted — review carefully when uploading documents.",
  submitForApproval: "Submit for approval",
  couldNotSubmitProduct: "Could not submit product for approval.",
  productSubmittedForApproval: "Product submitted for approval.",
  couldNotOpenDocument: "Could not open document.",
  saveCategories: "Save categories",
  categoriesSaved:
    "Categories updated. Check the KYC checklist for any new requirements.",
  couldNotSaveCategories: "Could not save categories.",
  entityTypeSole: "Sole proprietorship",
  entityTypePartnership: "Partnership",
  entityTypeLlp: "LLP",
  entityTypePrivateLimited: "Private limited",
  vendorCategories: "Selling categories",
  vendorCategoriesHint:
    "Select the categories you plan to sell in. Extra regulated categories may require more documents.",
  panHolderName: "Name on PAN",
  bankAccountHolderName: "Bank account holder name",
  kycNameMismatchWarning:
    "Bank account holder name does not match the name on PAN. This is a common rejection reason — double-check before submitting.",
  requiredDocuments: "Required documents",
  registerAsVendor: "Register as a vendor",
  registerAsVendorHint:
    "Tell us your entity type and categories first so we can list the documents you need.",
  registrationFailed: "Registration failed. Try again.",
  businessDescriptionOptional: "Description (optional)",
  gstNumberOptional: "GST number (optional)",
  startSelling: "Start selling on the marketplace",
  promoBanners: "Promo banners",
  promoBannersHint:
    "Homepage hero banners. Upload the image first, then save the banner.",
  promoBannerTitle: "Title",
  promoBannerImage: "Banner image",
  promoBannerLinkType: "Link type",
  promoBannerLinkTargetId: "Link target ID",
  promoBannerLinkUrl: "Link URL",
} as const;
