/** Table and pagination copy (part 4); merged via labels.ts. */
export const tables4Labels = {
  promoBannerLinkType: "Link type",
  promoBannerLinkTargetId: "Link target ID",
  promoBannerLinkUrl: "Link URL",
  sort: "Sort",
  compare: "Compare",
  compareMinRequired: "Add at least 2 products to compare.",
  compareSelectionCount: "{count} of {max} selected",
  compareMaxReached:
    "Maximum of {max} products reached. Remove one to add another.",
  sortTrending: "Trending",
  sortPopular: "Popular",
  sortNewest: "Newest",
  sortPriceLowHigh: "Price: Low to High",
  sortPriceHighLow: "Price: High to Low",
  sortTopRated: "Top Rated",
  productCountSingular: "{count} product",
  productCountPlural: "{count} products",
  updatingEllipsis: "Updating…",
  browseCollection: "Browse collection",
  starsAndUp: "{count}+ stars",
  kycVerificationProgress: "Verification progress",
  kycDocumentsVerifiedCount: "{verified} of {total} verified",
  kycSelectToUpload: "Click a document to upload or replace",
  kycReplaceDocumentNotice:
    "Uploading a new file will submit it for review and replace any existing file.",
  kycAllDocumentsVerified: "All required documents are verified and approved.",
  previewPdf: "PDF document",
  previewDocx: "Word document",
  previewImage: "Image file",
  previewDocument: "Document",
  openInNewTab: "Open in new tab",
  clickToUpload: "Click to upload",
  clickToCollapse: "Click to close",
  rejectionActionHint: "Upload a replacement file to request verification.",
} as const;
