/** Support ticket flows. Subset of LABELS; merged in labels/index.ts. */
export const ticketsLabels = {
  supportTickets: "Support tickets",
  supportTicket: "Support ticket",
  mySupportTickets: "My support tickets",
  supportTicketsPageDescription:
    "Open and track helpdesk conversations about orders, payments, and sellers.",
  supportTicketsEmpty: "No support tickets yet",
  supportTicketsEmptyMessage:
    "Create a ticket when you need help with an order or account issue.",
  createSupportTicket: "Create ticket",
  newSupportTicket: "New support ticket",
  newSupportTicketDescription:
    "Describe the issue. Attach screenshots or a short video if helpful.",
  ticketSubject: "Subject",
  ticketSubjectPlaceholder: "Short summary of the issue",
  ticketDescription: "Description",
  ticketDescriptionPlaceholder:
    "What happened, what you expected, and any error messages.",
  ticketCategory: "Category",
  ticketRelatedOrderId: "Related order ID (optional)",
  ticketRelatedVendorId: "Related vendor ID (optional)",
  ticketRelatedVendor: "Related vendor",
  ticketRelatedVendorHint:
    "Required when the issue is about a specific seller, or when your order has multiple sellers.",
  ticketSelectVendor: "Select a vendor",
  ticketVendorRequired: "Select the related vendor",
  ticketSearchVendors: "Search vendors…",
  ticketPriority: "Priority",
  ticketAttachments: "Attachments",
  ticketSubmit: "Submit ticket",
  ticketCreatedSuccess: "Ticket created.",
  ticketCouldNotCreate: "Could not create ticket.",
  ticketCouldNotLoad: "Could not load tickets.",
  ticketCouldNotLoadDetail: "Could not load this ticket.",
  ticketReplyPlaceholder: "Write a reply…",
  ticketSendReply: "Send reply",
  ticketCouldNotReply: "Could not send reply.",
  ticketCouldNotResolve: "Could not resolve ticket.",
  ticketCouldNotReopen: "Could not reopen ticket.",
  ticketCouldNotClose: "Could not close ticket.",
  ticketCouldNotReassign: "Could not reassign ticket.",
  ticketCouldNotUpdatePriority: "Could not update priority.",
  ticketCouldNotEscalate: "Could not escalate ticket.",
  ticketCouldNotRate: "Could not submit rating.",
  ticketReopenWindowExpired: "The reopen window for this ticket has ended.",
  ticketResolve: "Mark resolved",
  ticketReopen: "Reopen",
  ticketClose: "Close ticket",
  ticketReassign: "Reassign",
  ticketAssignee: "Assignee",
  ticketAssigneePlaceholder: "Select an assignee",
  ticketAssigneeNone: "Unassigned",
  ticketAssigneesEmpty: "No eligible assignees found.",
  ticketAssignedToId: "Assignee",
  ticketRate: "Rate this resolution",
  ticketRateSubmit: "Submit rating",
  ticketRatedThanks: "Thanks for your feedback.",
  ticketLoadEarlier: "Load earlier messages",
  ticketNoMessages: "No messages yet.",
  ticketLatestPreview: "Latest",
  ticketNumberLabel: "Ticket {number}",
  ticketNumber: "Ticket #",
  ticketCustomer: "Customer",
  ticketVendor: "Vendor",
  ticketView: "View",
  ticketConversation: "Conversation",
  ticketOriginalRequest: "Original request",
  ticketAboutTicket: "About this ticket",
  ticketBackToList: "Back to tickets",
  ticketShowDetails: "Ticket details",
  ticketHideDetails: "Hide details",
  ticketClosedNotice: "This ticket is closed. You can no longer send replies.",
  ticketMustReopenToReplyCustomer:
    "This ticket is resolved. Reopen it to send another reply.",
  ticketMustReopenToReplyStaff:
    "This ticket is resolved. The customer must reopen it before further replies.",
  ticketUnread: "Unread",
  ticketHasUnread: "New activity",
  ticketRateHint:
    "How was the resolution? Your rating helps us improve support.",
  ticketUpdatePriority: "Update priority",
  ticketPrioritySaved: "Priority updated.",
  ticketEscalate: "Escalate to urgent",
  ticketMessageYou: "You",
  ticketMessageSupport: "Support",
  ticketMessageCustomer: "Customer",
  ticketAvatarInitialsFallback: "?",
  ticketComposerHint: "Replies are visible to everyone on this ticket.",
  ticketBasicsSection: "Ticket details",
  ticketBasicsSectionHint: "Subject and category for routing.",
  ticketDescriptionSection: "Description",
  ticketDescriptionSectionHint:
    "Include enough detail for support to investigate.",
  ticketAttachmentsSection: "Attachments",
  ticketAttachmentsSectionHint: "Up to 5 images and 1 short video.",
  ticketOrderSection: "Related order",
  ticketOrderSectionHint: "Optionally link one of your orders (any status).",
  ticketShipmentSection: "Shipment",
  ticketShipmentEmpty: "No shipment recorded for this order yet.",
  ticketSelectOrder: "Select an order",
  ticketNoOrder: "No related order",
  ticketNoOrdersYet: "You have no orders to link yet.",
  ticketSubjectTooLong: "Subject must be {max} characters or fewer.",
  ticketDescriptionTooLong: "Description must be {max} characters or fewer.",
  ticketReplyTooLong: "Reply must be {max} characters or fewer.",
  ticketSubjectRequired: "Subject is required",
  ticketDescriptionRequired: "Description is required",
  enterTicketSubject: "Enter a subject to continue.",
  enterTicketDescription: "Enter a description to continue.",
  selectTicketVendor: "Select the related vendor to continue.",
  ticketCategoryRequired: "Category is required",
  ticketCharCounter: "{count} / {max}",
  attachmentCounter: "{count} / {max} images · {videoCount} / {videoMax} video",
  ticketStatusOpen: "Open",
  ticketStatusInProgress: "In progress",
  ticketStatusResolved: "Resolved",
  ticketStatusClosed: "Closed",
  ticketStatusReopened: "Reopened",
  ticketCategoryOrder: "Order",
  ticketCategoryProduct: "Product",
  ticketCategoryPayment: "Payment",
  ticketCategoryVendor: "Vendor",
  ticketCategoryOther: "Other",
  ticketPriorityLow: "Low",
  ticketPriorityMedium: "Medium",
  ticketPriorityHigh: "High",
  ticketPriorityUrgent: "Urgent",
  ticketFilterAllStatuses: "All statuses",
  ticketFilterAllPriorities: "All priorities",
  ticketFilterAllCategories: "All categories",
  ticketFilterVendorId: "Vendor",
  ticketFilterAllVendors: "All vendors",
  ticketAdminQueueDescription:
    "Platform helpdesk queue with filters and assignment.",
  ticketVendorQueueDescription: "Customer tickets related to your shop.",
  ticketSignInRequired: "Sign in to view and manage support tickets.",
  ticketAttachmentLimit: "You can attach up to 5 images and 1 video.",
  ticketVideoTooLong: "Video must be {seconds} seconds or less.",
  ticketVideoTooLarge: "Video must be under {mb}MB.",
  ticketCompressFailed:
    "Could not compress video. Try a shorter or smaller file.",
  ticketCompressingVideo: "Compressing video…",
  bugVideoTooLong: "Screen recording must be {seconds} seconds or less.",
  bugVideoTooLarge: "Screen recording must be under {mb}MB.",
  bugCompressFailed:
    "Could not compress the recording. Try a shorter or smaller file.",
  bugCompressingVideo: "Compressing recording…",
  ticketRemoveAttachment: "Remove",
  ticketAttachmentImage: "Image",
  ticketAttachmentVideo: "Video",
  loadMore: "Load more",

  // Bug reports
} as const;
