/** Admin wallet report copy. Subset of LABELS; merged in labels/index.ts. */
export const walletReportsLabels = {
  reportWalletLiability: "Wallet liability",
  reportWalletRecharge: "Points recharge",
  reportCashbackWriteOff: "Cashback write-offs",
  reportTotalLiability: "Total outstanding points",
  reportPurchasedPointsLiability: "Purchased points liability",
  reportPromotionalPointsLiability: "Promotional points liability",
  reportWalletCustomerCount: "Customers with balance",
  reportRecoveredTotal: "Recovered",
  reportWrittenOffTotal: "Written off",
  reportBornBy: "Born by",
  reportBornByAll: "All",
  reportBornByPlatform: "Platform",
  reportBornByVendor: "Vendor",
  reportUserId: "User ID",
  reportBalance: "Balance",
  reportPurchasedPoints: "Purchased",
  reportPromotionalPoints: "Promotional",
  reportAsOf: "As of",
  reportOriginalClawback: "Original clawback",
  reportRecoveredAmount: "Recovered amount",
  reportWrittenOffAmount: "Written off amount",
  reportRechargeInrCollected: "INR collected",
  reportPointsIssued: "Points issued",
  reportRechargeSuccessCount: "Successful recharges",
  reportRechargeFailedCount: "Failed / expired",
  reportAmountInr: "Amount (INR)",
  reportPointsCredited: "Points credited",
  reportStatus: "Status",
  reportPaidAt: "Paid at",
  reportLiabilityFifoNote:
    "Purchased vs promotional split follows FIFO (promotional first) from the ledger.",
  walletAdjustTitle: "Manual wallet adjustment",
  walletAdjustUserId: "Customer user ID",
  walletAdjustDirection: "Direction",
  walletAdjustAmount: "Points amount",
  walletAdjustReason: "Reason",
  walletAdjustPointSource: "Point source (credits only)",
  walletAdjustSubmit: "Apply adjustment",
  walletAdjustSuccess: "Wallet updated — new balance: {balance} pts",
  walletAdjustValidationError:
    "Enter user ID, a positive amount, and a reason (at least 3 characters).",
  walletAdjustFailed: "Could not adjust wallet",
} as const;
